//Generated by ErrorPro
dtmc
//Element consts
const int cfblk4_Output_1=0;
const int cfblk2_Output_2=1;
const int cfblk1_Output_3=2;
const int cfblk5_Output_4=3;
const int cfblk3_Output_5=4;
const int cfblk4_Update_6=5;
const int cfblk1_Update_7=6;
const int cfblk5_Update_8=7;
const int check_redandancy0=8;
const int cfblk4_Output_1_2=9;
const int cfblk4_Output_1_3=10;
const int compare0=11;
const int stop_system=12;
const int check_redandancy2=13;
const int cfblk1_Output_3_2=14;
const int cfblk1_Output_3_3=15;
const int compare2=16;
const int check_redandancy3=17;
const int cfblk3_Output_5_2=18;
const int cfblk3_Output_5_3=19;
const int compare3=20;
const int check_redandancy4=21;
const int cfblk4_Update_6_2=22;
const int cfblk4_Update_6_3=23;
const int compare4=24;
const int check_redandancy5=25;
const int cfblk1_Update_7_2=26;
const int cfblk1_Update_7_3=27;
const int compare5=28;
//Data values consts
const int v=0;
const int prop_2=1;
const int prop_1=2;
const int ok=3;
const int no=4;
const int error=5;
const int c=6;
//Control flow commands
module control_flow
	cf:[0..29] init cfblk4_Output_1;
	//Element cfblk4_Output_1, df inputs ['x_cfblk4_1_4177988455', 'y_cfblk1_2642350696'], cf transitions ['check_redandancy0']
	[cfblk4_Output_1] cf=cfblk4_Output_1 -> 1.0:(cf'=check_redandancy0);
	//Element cfblk2_Output_2, df inputs ['x_cfblk1_1_303584548_2_x_cfblk4_1_4177988455_2_y_cfblk3_2720621482_2_y_cfblk1_2642350696_2_y_cfblk4_2759756875'], cf transitions ['cfblk1_Output_3']
	[cfblk2_Output_2] cf=cfblk2_Output_2 -> 1.0:(cf'=cfblk1_Output_3);
	//Element cfblk1_Output_3, df inputs ['y_cfblk5_2798892268', 'x_cfblk1_1_303584548'], cf transitions ['check_redandancy2']
	[cfblk1_Output_3] cf=cfblk1_Output_3 -> 1.0:(cf'=check_redandancy2);
	//Element cfblk5_Output_4, df inputs ['x_cfblk5_1_1174489129', 'y_cfblk3_2720621482'], cf transitions ['cfblk3_Output_5']
	[cfblk5_Output_4] cf=cfblk5_Output_4 -> 1.0:(cf'=cfblk3_Output_5);
	//Element cfblk3_Output_5, df inputs ['y_cfblk5_2798892268', 'y_cfblk1_2642350696'], cf transitions ['check_redandancy3']
	[cfblk3_Output_5] cf=cfblk3_Output_5 -> 1.0:(cf'=check_redandancy3);
	//Element cfblk4_Update_6, df inputs ['x_cfblk4_1_4177988455', 'y_cfblk1_2642350696'], cf transitions ['check_redandancy4']
	[cfblk4_Update_6] cf=cfblk4_Update_6 -> 1.0:(cf'=check_redandancy4);
	//Element cfblk1_Update_7, df inputs ['y_cfblk5_2798892268', 'x_cfblk1_1_303584548'], cf transitions ['check_redandancy5']
	[cfblk1_Update_7] cf=cfblk1_Update_7 -> 1.0:(cf'=check_redandancy5);
	//Element cfblk5_Update_8, df inputs ['x_cfblk5_1_1174489129', 'y_cfblk3_2720621482'], cf transitions ['cfblk4_Output_1']
	[cfblk5_Update_8] cf=cfblk5_Update_8 -> 1.0:(cf'=cfblk4_Output_1);
	//Element check_redandancy0, df inputs ['redundancy_model1_cfblk4_0'], cf transitions ['cfblk4_Output_1_2', 'cfblk2_Output_2']
	[check_redandancy0] (cf=check_redandancy0) & (redundancy_model1_cfblk4_0=no) -> (cf'=cfblk2_Output_2);	// <-- 
	[check_redandancy0] (cf=check_redandancy0) & ((redundancy_model1_cfblk4_0=v)|(redundancy_model1_cfblk4_0=c)) -> (cf'=cfblk4_Output_1_2);	// <-- 
	//Element cfblk4_Output_1_2, df inputs ['x_cfblk4_1_4177988455', 'y_cfblk1_2642350696'], cf transitions ['compare0']
	[cfblk4_Output_1_2] cf=cfblk4_Output_1_2 -> 1.0:(cf'=compare0);
	//Element cfblk4_Output_1_3, df inputs ['x_cfblk4_1_4177988455', 'y_cfblk1_2642350696'], cf transitions ['cfblk2_Output_2']
	[cfblk4_Output_1_3] cf=cfblk4_Output_1_3 -> 1.0:(cf'=cfblk2_Output_2);
	//Element compare0, df inputs ['y_cfblk4_2759756875_2', 'redundancy_model1_cfblk4_0', 'x_cfblk1_1_303584548_2_x_cfblk4_1_4177988455_2_y_cfblk3_2720621482_2_y_cfblk1_2642350696_2_y_cfblk4_2759756875'], cf transitions ['cfblk4_Output_1_3', 'cfblk2_Output_2', 'stop_system']
	[compare0] (cf=compare0) & (redundancy_model1_cfblk4_0=c) & (x_cfblk1_1_303584548_2_x_cfblk4_1_4177988455_2_y_cfblk3_2720621482_2_y_cfblk1_2642350696_2_y_cfblk4_2759756875=prop_1) & (y_cfblk4_2759756875_2=ok) -> (cf'=cfblk2_Output_2);	// <-- 
	[compare0] (cf=compare0) & (redundancy_model1_cfblk4_0=c) & ((x_cfblk1_1_303584548_2_x_cfblk4_1_4177988455_2_y_cfblk3_2720621482_2_y_cfblk1_2642350696_2_y_cfblk4_2759756875=prop_2) | (y_cfblk4_2759756875_2=error)) -> (cf'=stop_system);	// <-- 
	[compare0] (cf=compare0) & (redundancy_model1_cfblk4_0=v) & (x_cfblk1_1_303584548_2_x_cfblk4_1_4177988455_2_y_cfblk3_2720621482_2_y_cfblk1_2642350696_2_y_cfblk4_2759756875=prop_1) & (y_cfblk4_2759756875_2=ok) -> (cf'=cfblk2_Output_2);	// <-- 
	[compare0] (cf=compare0) & (redundancy_model1_cfblk4_0=v) & ((x_cfblk1_1_303584548_2_x_cfblk4_1_4177988455_2_y_cfblk3_2720621482_2_y_cfblk1_2642350696_2_y_cfblk4_2759756875=prop_2) | (y_cfblk4_2759756875_2=error)) -> (cf'=cfblk4_Output_1_3);	// <-- 
	//Element stop_system, cf transitions ['cfblk4_Output_1']
	[stop_system] cf=stop_system -> 1.0:(cf'=cfblk4_Output_1);
	//Element check_redandancy2, df inputs ['redundancy_model1_cfblk1_2'], cf transitions ['cfblk1_Output_3_2', 'cfblk5_Output_4']
	[check_redandancy2] (cf=check_redandancy2) & (redundancy_model1_cfblk1_2=no) -> (cf'=cfblk5_Output_4);	// <-- 
	[check_redandancy2] (cf=check_redandancy2) & ((redundancy_model1_cfblk1_2=v)|(redundancy_model1_cfblk1_2=c)) -> (cf'=cfblk1_Output_3_2);	// <-- 
	//Element cfblk1_Output_3_2, df inputs ['y_cfblk5_2798892268', 'x_cfblk1_1_303584548'], cf transitions ['compare2']
	[cfblk1_Output_3_2] cf=cfblk1_Output_3_2 -> 1.0:(cf'=compare2);
	//Element cfblk1_Output_3_3, df inputs ['y_cfblk5_2798892268', 'x_cfblk1_1_303584548'], cf transitions ['cfblk5_Output_4']
	[cfblk1_Output_3_3] cf=cfblk1_Output_3_3 -> 1.0:(cf'=cfblk5_Output_4);
	//Element compare2, df inputs ['x_cfblk1_1_303584548_2_x_cfblk4_1_4177988455_2_y_cfblk3_2720621482_2_y_cfblk1_2642350696_2_y_cfblk4_2759756875', 'y_cfblk1_2642350696', 'redundancy_model1_cfblk1_2'], cf transitions ['cfblk1_Output_3_3', 'cfblk5_Output_4', 'stop_system']
	[compare2] (cf=compare2) & (redundancy_model1_cfblk1_2=c) & (y_cfblk1_2642350696=ok) & (x_cfblk1_1_303584548_2_x_cfblk4_1_4177988455_2_y_cfblk3_2720621482_2_y_cfblk1_2642350696_2_y_cfblk4_2759756875=prop_1) -> (cf'=cfblk5_Output_4);	// <-- 
	[compare2] (cf=compare2) & (redundancy_model1_cfblk1_2=c) & ((y_cfblk1_2642350696=error) | (x_cfblk1_1_303584548_2_x_cfblk4_1_4177988455_2_y_cfblk3_2720621482_2_y_cfblk1_2642350696_2_y_cfblk4_2759756875=prop_2)) -> (cf'=stop_system);	// <-- 
	[compare2] (cf=compare2) & (redundancy_model1_cfblk1_2=v) & (y_cfblk1_2642350696=ok) & (x_cfblk1_1_303584548_2_x_cfblk4_1_4177988455_2_y_cfblk3_2720621482_2_y_cfblk1_2642350696_2_y_cfblk4_2759756875=prop_1) -> (cf'=cfblk5_Output_4);	// <-- 
	[compare2] (cf=compare2) & (redundancy_model1_cfblk1_2=v) & ((y_cfblk1_2642350696=error) | (x_cfblk1_1_303584548_2_x_cfblk4_1_4177988455_2_y_cfblk3_2720621482_2_y_cfblk1_2642350696_2_y_cfblk4_2759756875=prop_2)) -> (cf'=cfblk1_Output_3_3);	// <-- 
	//Element check_redandancy3, df inputs ['redundancy_model1_cfblk3_3'], cf transitions ['cfblk3_Output_5_2', 'cfblk4_Update_6']
	[check_redandancy3] (cf=check_redandancy3) & (redundancy_model1_cfblk3_3=no) -> (cf'=cfblk4_Update_6);	// <-- 
	[check_redandancy3] (cf=check_redandancy3) & ((redundancy_model1_cfblk3_3=v)|(redundancy_model1_cfblk3_3=c)) -> (cf'=cfblk3_Output_5_2);	// <-- 
	//Element cfblk3_Output_5_2, df inputs ['y_cfblk5_2798892268', 'y_cfblk1_2642350696'], cf transitions ['compare3']
	[cfblk3_Output_5_2] cf=cfblk3_Output_5_2 -> 1.0:(cf'=compare3);
	//Element cfblk3_Output_5_3, df inputs ['y_cfblk5_2798892268', 'y_cfblk1_2642350696'], cf transitions ['cfblk4_Update_6']
	[cfblk3_Output_5_3] cf=cfblk3_Output_5_3 -> 1.0:(cf'=cfblk4_Update_6);
	//Element compare3, df inputs ['y_cfblk3_2720621482', 'x_cfblk1_1_303584548_2_x_cfblk4_1_4177988455_2_y_cfblk3_2720621482_2_y_cfblk1_2642350696_2_y_cfblk4_2759756875', 'redundancy_model1_cfblk3_3'], cf transitions ['cfblk3_Output_5_3', 'cfblk4_Update_6', 'stop_system']
	[compare3] (cf=compare3) & (redundancy_model1_cfblk3_3=c) & (y_cfblk3_2720621482=ok) & (x_cfblk1_1_303584548_2_x_cfblk4_1_4177988455_2_y_cfblk3_2720621482_2_y_cfblk1_2642350696_2_y_cfblk4_2759756875=prop_1) -> (cf'=cfblk4_Update_6);	// <-- 
	[compare3] (cf=compare3) & (redundancy_model1_cfblk3_3=c) & ((y_cfblk3_2720621482=error) | (x_cfblk1_1_303584548_2_x_cfblk4_1_4177988455_2_y_cfblk3_2720621482_2_y_cfblk1_2642350696_2_y_cfblk4_2759756875=prop_2)) -> (cf'=stop_system);	// <-- 
	[compare3] (cf=compare3) & (redundancy_model1_cfblk3_3=v) & (y_cfblk3_2720621482=ok) & (x_cfblk1_1_303584548_2_x_cfblk4_1_4177988455_2_y_cfblk3_2720621482_2_y_cfblk1_2642350696_2_y_cfblk4_2759756875=prop_1) -> (cf'=cfblk4_Update_6);	// <-- 
	[compare3] (cf=compare3) & (redundancy_model1_cfblk3_3=v) & ((y_cfblk3_2720621482=error) | (x_cfblk1_1_303584548_2_x_cfblk4_1_4177988455_2_y_cfblk3_2720621482_2_y_cfblk1_2642350696_2_y_cfblk4_2759756875=prop_2)) -> (cf'=cfblk3_Output_5_3);	// <-- 
	//Element check_redandancy4, df inputs ['redundancy_model1_cfblk4_0'], cf transitions ['cfblk4_Update_6_2', 'cfblk1_Update_7']
	[check_redandancy4] (cf=check_redandancy4) & (redundancy_model1_cfblk4_0=no) -> (cf'=cfblk1_Update_7);	// <-- 
	[check_redandancy4] (cf=check_redandancy4) & ((redundancy_model1_cfblk4_0=v)|(redundancy_model1_cfblk4_0=c)) -> (cf'=cfblk4_Update_6_2);	// <-- 
	//Element cfblk4_Update_6_2, df inputs ['x_cfblk4_1_4177988455', 'y_cfblk1_2642350696'], cf transitions ['compare4']
	[cfblk4_Update_6_2] cf=cfblk4_Update_6_2 -> 1.0:(cf'=compare4);
	//Element cfblk4_Update_6_3, df inputs ['x_cfblk4_1_4177988455', 'y_cfblk1_2642350696'], cf transitions ['cfblk1_Update_7']
	[cfblk4_Update_6_3] cf=cfblk4_Update_6_3 -> 1.0:(cf'=cfblk1_Update_7);
	//Element compare4, df inputs ['redundancy_model1_cfblk4_0', 'x_cfblk4_1_4177988455', 'x_cfblk1_1_303584548_2_x_cfblk4_1_4177988455_2_y_cfblk3_2720621482_2_y_cfblk1_2642350696_2_y_cfblk4_2759756875'], cf transitions ['cfblk4_Update_6_3', 'cfblk1_Update_7', 'stop_system']
	[compare4] (cf=compare4) & (redundancy_model1_cfblk4_0=c) & (x_cfblk4_1_4177988455=ok) & (x_cfblk1_1_303584548_2_x_cfblk4_1_4177988455_2_y_cfblk3_2720621482_2_y_cfblk1_2642350696_2_y_cfblk4_2759756875=prop_1) -> (cf'=cfblk1_Update_7);	// <-- 
	[compare4] (cf=compare4) & (redundancy_model1_cfblk4_0=c) & ((x_cfblk4_1_4177988455=error) | (x_cfblk1_1_303584548_2_x_cfblk4_1_4177988455_2_y_cfblk3_2720621482_2_y_cfblk1_2642350696_2_y_cfblk4_2759756875=prop_2)) -> (cf'=stop_system);	// <-- 
	[compare4] (cf=compare4) & (redundancy_model1_cfblk4_0=v) & (x_cfblk4_1_4177988455=ok) & (x_cfblk1_1_303584548_2_x_cfblk4_1_4177988455_2_y_cfblk3_2720621482_2_y_cfblk1_2642350696_2_y_cfblk4_2759756875=prop_1) -> (cf'=cfblk1_Update_7);	// <-- 
	[compare4] (cf=compare4) & (redundancy_model1_cfblk4_0=v) & ((x_cfblk4_1_4177988455=error) | (x_cfblk1_1_303584548_2_x_cfblk4_1_4177988455_2_y_cfblk3_2720621482_2_y_cfblk1_2642350696_2_y_cfblk4_2759756875=prop_2)) -> (cf'=cfblk4_Update_6_3);	// <-- 
	//Element check_redandancy5, df inputs ['redundancy_model1_cfblk1_2'], cf transitions ['cfblk1_Update_7_2', 'cfblk5_Update_8']
	[check_redandancy5] (cf=check_redandancy5) & (redundancy_model1_cfblk1_2=no) -> (cf'=cfblk5_Update_8);	// <-- 
	[check_redandancy5] (cf=check_redandancy5) & ((redundancy_model1_cfblk1_2=v)|(redundancy_model1_cfblk1_2=c)) -> (cf'=cfblk1_Update_7_2);	// <-- 
	//Element cfblk1_Update_7_2, df inputs ['y_cfblk5_2798892268', 'x_cfblk1_1_303584548'], cf transitions ['compare5']
	[cfblk1_Update_7_2] cf=cfblk1_Update_7_2 -> 1.0:(cf'=compare5);
	//Element cfblk1_Update_7_3, df inputs ['y_cfblk5_2798892268', 'x_cfblk1_1_303584548'], cf transitions ['cfblk5_Update_8']
	[cfblk1_Update_7_3] cf=cfblk1_Update_7_3 -> 1.0:(cf'=cfblk5_Update_8);
	//Element compare5, df inputs ['x_cfblk1_1_303584548_2_x_cfblk4_1_4177988455_2_y_cfblk3_2720621482_2_y_cfblk1_2642350696_2_y_cfblk4_2759756875', 'x_cfblk1_1_303584548', 'redundancy_model1_cfblk1_2'], cf transitions ['cfblk1_Update_7_3', 'cfblk5_Update_8', 'stop_system']
	[compare5] (cf=compare5) & (redundancy_model1_cfblk1_2=c) & (x_cfblk1_1_303584548=ok) & (x_cfblk1_1_303584548_2_x_cfblk4_1_4177988455_2_y_cfblk3_2720621482_2_y_cfblk1_2642350696_2_y_cfblk4_2759756875=prop_1) -> (cf'=cfblk5_Update_8);	// <-- 
	[compare5] (cf=compare5) & (redundancy_model1_cfblk1_2=c) & ((x_cfblk1_1_303584548=error) | (x_cfblk1_1_303584548_2_x_cfblk4_1_4177988455_2_y_cfblk3_2720621482_2_y_cfblk1_2642350696_2_y_cfblk4_2759756875=prop_2)) -> (cf'=stop_system);	// <-- 
	[compare5] (cf=compare5) & (redundancy_model1_cfblk1_2=v) & (x_cfblk1_1_303584548=ok) & (x_cfblk1_1_303584548_2_x_cfblk4_1_4177988455_2_y_cfblk3_2720621482_2_y_cfblk1_2642350696_2_y_cfblk4_2759756875=prop_1) -> (cf'=cfblk5_Update_8);	// <-- 
	[compare5] (cf=compare5) & (redundancy_model1_cfblk1_2=v) & ((x_cfblk1_1_303584548=error) | (x_cfblk1_1_303584548_2_x_cfblk4_1_4177988455_2_y_cfblk3_2720621482_2_y_cfblk1_2642350696_2_y_cfblk4_2759756875=prop_2)) -> (cf'=cfblk1_Update_7_3);	// <-- 
endmodule
//Error propagation commands
module error_propagation
	y_cfblk1_2642350696 : [0 .. 6] init ok;
	y_cfblk3_2720621482 : [0 .. 6] init ok;
	y_cfblk5_2798892268 : [0 .. 6] init ok;
	x_cfblk4_1_4177988455 : [0 .. 6] init ok;
	x_cfblk1_1_303584548 : [0 .. 6] init ok;
	x_cfblk5_1_1174489129 : [0 .. 6] init ok;
	redundancy_model1_cfblk4_0 : [0 .. 6] init no;
	y_cfblk4_2759756875_2 : [0 .. 6] init ok;
	redundancy_model1_cfblk1_2 : [0 .. 6] init no;
	redundancy_model1_cfblk3_3 : [0 .. 6] init v;
	x_cfblk1_1_303584548_2_x_cfblk4_1_4177988455_2_y_cfblk3_2720621482_2_y_cfblk1_2642350696_2_y_cfblk4_2759756875 : [0 .. 6] init prop_1;
	//Element cfblk4_Output_1, df inputs ['x_cfblk4_1_4177988455', 'y_cfblk1_2642350696'], df outputs ['x_cfblk1_1_303584548_2_x_cfblk4_1_4177988455_2_y_cfblk3_2720621482_2_y_cfblk1_2642350696_2_y_cfblk4_2759756875']
	[cfblk4_Output_1] (y_cfblk1_2642350696=ok) & (x_cfblk4_1_4177988455=ok) -> 0.98:(x_cfblk1_1_303584548_2_x_cfblk4_1_4177988455_2_y_cfblk3_2720621482_2_y_cfblk1_2642350696_2_y_cfblk4_2759756875'=prop_1) + 0.02:(x_cfblk1_1_303584548_2_x_cfblk4_1_4177988455_2_y_cfblk3_2720621482_2_y_cfblk1_2642350696_2_y_cfblk4_2759756875'=prop_2);	// <-- 
	[cfblk4_Output_1] (y_cfblk1_2642350696!=ok) | (x_cfblk4_1_4177988455!=ok) -> (x_cfblk1_1_303584548_2_x_cfblk4_1_4177988455_2_y_cfblk3_2720621482_2_y_cfblk1_2642350696_2_y_cfblk4_2759756875'=prop_2);	// <-- 
	//Element cfblk1_Output_3, df inputs ['y_cfblk5_2798892268', 'x_cfblk1_1_303584548'], df outputs ['y_cfblk1_2642350696']
	[cfblk1_Output_3] (y_cfblk5_2798892268=ok) & (x_cfblk1_1_303584548=ok) -> 0.98:(y_cfblk1_2642350696'=ok) + 0.02:(y_cfblk1_2642350696'=error);	// <-- 
	[cfblk1_Output_3] (y_cfblk5_2798892268!=ok) | (x_cfblk1_1_303584548!=ok) -> (y_cfblk1_2642350696'=error);	// <-- 
	//Element cfblk5_Output_4, df inputs ['x_cfblk5_1_1174489129', 'y_cfblk3_2720621482'], df outputs ['y_cfblk5_2798892268']
	[cfblk5_Output_4] (y_cfblk3_2720621482=ok) & (x_cfblk5_1_1174489129=ok) -> 0.98:(y_cfblk5_2798892268'=ok) + 0.02:(y_cfblk5_2798892268'=error);	// <-- 
	[cfblk5_Output_4] (y_cfblk3_2720621482!=ok) | (x_cfblk5_1_1174489129!=ok) -> (y_cfblk5_2798892268'=error);	// <-- 
	//Element cfblk3_Output_5, df inputs ['y_cfblk5_2798892268', 'y_cfblk1_2642350696'], df outputs ['y_cfblk3_2720621482']
	[cfblk3_Output_5] (y_cfblk1_2642350696=ok) & (y_cfblk5_2798892268=ok) -> 0.974002239936:(y_cfblk3_2720621482'=ok) + 0.025997760064:(y_cfblk3_2720621482'=error);	// <-- 
	[cfblk3_Output_5] (y_cfblk1_2642350696!=ok) | (y_cfblk5_2798892268!=ok) -> (y_cfblk3_2720621482'=error);	// <-- 
	//Element cfblk4_Update_6, df inputs ['x_cfblk4_1_4177988455', 'y_cfblk1_2642350696'], df outputs ['x_cfblk4_1_4177988455']
	[cfblk4_Update_6] (y_cfblk1_2642350696=ok) & (x_cfblk4_1_4177988455=ok) -> 0.98:(x_cfblk4_1_4177988455'=ok) + 0.02:(x_cfblk4_1_4177988455'=error);	// <-- 
	[cfblk4_Update_6] (y_cfblk1_2642350696!=ok) | (x_cfblk4_1_4177988455!=ok) -> (x_cfblk4_1_4177988455'=error);	// <-- 
	//Element cfblk1_Update_7, df inputs ['y_cfblk5_2798892268', 'x_cfblk1_1_303584548'], df outputs ['x_cfblk1_1_303584548']
	[cfblk1_Update_7] (y_cfblk5_2798892268=ok) & (x_cfblk1_1_303584548=ok) -> 0.98:(x_cfblk1_1_303584548'=ok) + 0.02:(x_cfblk1_1_303584548'=error);	// <-- 
	[cfblk1_Update_7] (y_cfblk5_2798892268!=ok) | (x_cfblk1_1_303584548!=ok) -> (x_cfblk1_1_303584548'=error);	// <-- 
	//Element cfblk5_Update_8, df inputs ['x_cfblk5_1_1174489129', 'y_cfblk3_2720621482'], df outputs ['x_cfblk5_1_1174489129']
	[cfblk5_Update_8] (y_cfblk3_2720621482=ok) & (x_cfblk5_1_1174489129=ok) -> 0.98:(x_cfblk5_1_1174489129'=ok) + 0.02:(x_cfblk5_1_1174489129'=error);	// <-- 
	[cfblk5_Update_8] (y_cfblk3_2720621482!=ok) | (x_cfblk5_1_1174489129!=ok) -> (x_cfblk5_1_1174489129'=error);	// <-- 
	//Element cfblk4_Output_1_2, df inputs ['x_cfblk4_1_4177988455', 'y_cfblk1_2642350696'], df outputs ['y_cfblk4_2759756875_2']
	[cfblk4_Output_1_2] (y_cfblk1_2642350696=ok) & (x_cfblk4_1_4177988455=ok) -> 0.98:(y_cfblk4_2759756875_2'=ok) + 0.02:(y_cfblk4_2759756875_2'=error);	// <-- 
	[cfblk4_Output_1_2] (y_cfblk1_2642350696!=ok) | (x_cfblk4_1_4177988455!=ok) -> (y_cfblk4_2759756875_2'=error);	// <-- 
	//Element cfblk4_Output_1_3, df inputs ['x_cfblk4_1_4177988455', 'y_cfblk1_2642350696'], df outputs ['x_cfblk1_1_303584548_2_x_cfblk4_1_4177988455_2_y_cfblk3_2720621482_2_y_cfblk1_2642350696_2_y_cfblk4_2759756875']
	[cfblk4_Output_1_3] (y_cfblk1_2642350696=ok) & (x_cfblk4_1_4177988455=ok) -> 0.98:(x_cfblk1_1_303584548_2_x_cfblk4_1_4177988455_2_y_cfblk3_2720621482_2_y_cfblk1_2642350696_2_y_cfblk4_2759756875'=prop_1) + 0.02:(x_cfblk1_1_303584548_2_x_cfblk4_1_4177988455_2_y_cfblk3_2720621482_2_y_cfblk1_2642350696_2_y_cfblk4_2759756875'=prop_2);	// <-- 
	[cfblk4_Output_1_3] (y_cfblk1_2642350696!=ok) | (x_cfblk4_1_4177988455!=ok) -> (x_cfblk1_1_303584548_2_x_cfblk4_1_4177988455_2_y_cfblk3_2720621482_2_y_cfblk1_2642350696_2_y_cfblk4_2759756875'=prop_2);	// <-- 
	//Element cfblk1_Output_3_2, df inputs ['y_cfblk5_2798892268', 'x_cfblk1_1_303584548'], df outputs ['x_cfblk1_1_303584548_2_x_cfblk4_1_4177988455_2_y_cfblk3_2720621482_2_y_cfblk1_2642350696_2_y_cfblk4_2759756875']
	[cfblk1_Output_3_2] (y_cfblk5_2798892268=ok) & (x_cfblk1_1_303584548=ok) -> 0.98:(x_cfblk1_1_303584548_2_x_cfblk4_1_4177988455_2_y_cfblk3_2720621482_2_y_cfblk1_2642350696_2_y_cfblk4_2759756875'=prop_1) + 0.02:(x_cfblk1_1_303584548_2_x_cfblk4_1_4177988455_2_y_cfblk3_2720621482_2_y_cfblk1_2642350696_2_y_cfblk4_2759756875'=prop_2);	// <-- 
	[cfblk1_Output_3_2] (y_cfblk5_2798892268!=ok) | (x_cfblk1_1_303584548!=ok) -> (x_cfblk1_1_303584548_2_x_cfblk4_1_4177988455_2_y_cfblk3_2720621482_2_y_cfblk1_2642350696_2_y_cfblk4_2759756875'=prop_2);	// <-- 
	//Element cfblk1_Output_3_3, df inputs ['y_cfblk5_2798892268', 'x_cfblk1_1_303584548'], df outputs ['y_cfblk1_2642350696']
	[cfblk1_Output_3_3] (y_cfblk5_2798892268=ok) & (x_cfblk1_1_303584548=ok) -> 0.98:(y_cfblk1_2642350696'=ok) + 0.02:(y_cfblk1_2642350696'=error);	// <-- 
	[cfblk1_Output_3_3] (y_cfblk5_2798892268!=ok) | (x_cfblk1_1_303584548!=ok) -> (y_cfblk1_2642350696'=error);	// <-- 
	//Element cfblk3_Output_5_2, df inputs ['y_cfblk5_2798892268', 'y_cfblk1_2642350696'], df outputs ['x_cfblk1_1_303584548_2_x_cfblk4_1_4177988455_2_y_cfblk3_2720621482_2_y_cfblk1_2642350696_2_y_cfblk4_2759756875']
	[cfblk3_Output_5_2] (y_cfblk1_2642350696=ok) & (y_cfblk5_2798892268=ok) -> 0.974002239936:(x_cfblk1_1_303584548_2_x_cfblk4_1_4177988455_2_y_cfblk3_2720621482_2_y_cfblk1_2642350696_2_y_cfblk4_2759756875'=prop_1) + 0.025997760064:(x_cfblk1_1_303584548_2_x_cfblk4_1_4177988455_2_y_cfblk3_2720621482_2_y_cfblk1_2642350696_2_y_cfblk4_2759756875'=prop_2);	// <-- 
	[cfblk3_Output_5_2] (y_cfblk1_2642350696!=ok) | (y_cfblk5_2798892268!=ok) -> (x_cfblk1_1_303584548_2_x_cfblk4_1_4177988455_2_y_cfblk3_2720621482_2_y_cfblk1_2642350696_2_y_cfblk4_2759756875'=prop_2);	// <-- 
	//Element cfblk3_Output_5_3, df inputs ['y_cfblk5_2798892268', 'y_cfblk1_2642350696'], df outputs ['y_cfblk3_2720621482']
	[cfblk3_Output_5_3] (y_cfblk1_2642350696=ok) & (y_cfblk5_2798892268=ok) -> 0.974002239936:(y_cfblk3_2720621482'=ok) + 0.025997760064:(y_cfblk3_2720621482'=error);	// <-- 
	[cfblk3_Output_5_3] (y_cfblk1_2642350696!=ok) | (y_cfblk5_2798892268!=ok) -> (y_cfblk3_2720621482'=error);	// <-- 
	//Element cfblk4_Update_6_2, df inputs ['x_cfblk4_1_4177988455', 'y_cfblk1_2642350696'], df outputs ['x_cfblk1_1_303584548_2_x_cfblk4_1_4177988455_2_y_cfblk3_2720621482_2_y_cfblk1_2642350696_2_y_cfblk4_2759756875']
	[cfblk4_Update_6_2] (y_cfblk1_2642350696=ok) & (x_cfblk4_1_4177988455=ok) -> 0.98:(x_cfblk1_1_303584548_2_x_cfblk4_1_4177988455_2_y_cfblk3_2720621482_2_y_cfblk1_2642350696_2_y_cfblk4_2759756875'=prop_1) + 0.02:(x_cfblk1_1_303584548_2_x_cfblk4_1_4177988455_2_y_cfblk3_2720621482_2_y_cfblk1_2642350696_2_y_cfblk4_2759756875'=prop_2);	// <-- 
	[cfblk4_Update_6_2] (y_cfblk1_2642350696!=ok) | (x_cfblk4_1_4177988455!=ok) -> (x_cfblk1_1_303584548_2_x_cfblk4_1_4177988455_2_y_cfblk3_2720621482_2_y_cfblk1_2642350696_2_y_cfblk4_2759756875'=prop_2);	// <-- 
	//Element cfblk4_Update_6_3, df inputs ['x_cfblk4_1_4177988455', 'y_cfblk1_2642350696'], df outputs ['x_cfblk4_1_4177988455']
	[cfblk4_Update_6_3] (y_cfblk1_2642350696=ok) & (x_cfblk4_1_4177988455=ok) -> 0.98:(x_cfblk4_1_4177988455'=ok) + 0.02:(x_cfblk4_1_4177988455'=error);	// <-- 
	[cfblk4_Update_6_3] (y_cfblk1_2642350696!=ok) | (x_cfblk4_1_4177988455!=ok) -> (x_cfblk4_1_4177988455'=error);	// <-- 
	//Element cfblk1_Update_7_2, df inputs ['y_cfblk5_2798892268', 'x_cfblk1_1_303584548'], df outputs ['x_cfblk1_1_303584548_2_x_cfblk4_1_4177988455_2_y_cfblk3_2720621482_2_y_cfblk1_2642350696_2_y_cfblk4_2759756875']
	[cfblk1_Update_7_2] (y_cfblk5_2798892268=ok) & (x_cfblk1_1_303584548=ok) -> 0.98:(x_cfblk1_1_303584548_2_x_cfblk4_1_4177988455_2_y_cfblk3_2720621482_2_y_cfblk1_2642350696_2_y_cfblk4_2759756875'=prop_1) + 0.02:(x_cfblk1_1_303584548_2_x_cfblk4_1_4177988455_2_y_cfblk3_2720621482_2_y_cfblk1_2642350696_2_y_cfblk4_2759756875'=prop_2);	// <-- 
	[cfblk1_Update_7_2] (y_cfblk5_2798892268!=ok) | (x_cfblk1_1_303584548!=ok) -> (x_cfblk1_1_303584548_2_x_cfblk4_1_4177988455_2_y_cfblk3_2720621482_2_y_cfblk1_2642350696_2_y_cfblk4_2759756875'=prop_2);	// <-- 
	//Element cfblk1_Update_7_3, df inputs ['y_cfblk5_2798892268', 'x_cfblk1_1_303584548'], df outputs ['x_cfblk1_1_303584548']
	[cfblk1_Update_7_3] (y_cfblk5_2798892268=ok) & (x_cfblk1_1_303584548=ok) -> 0.98:(x_cfblk1_1_303584548'=ok) + 0.02:(x_cfblk1_1_303584548'=error);	// <-- 
	[cfblk1_Update_7_3] (y_cfblk5_2798892268!=ok) | (x_cfblk1_1_303584548!=ok) -> (x_cfblk1_1_303584548'=error);	// <-- 
endmodule

//Failure formulas
formula failure = x_cfblk5_1_1174489129 = error;

rewards "time" true : 1; endrewards
