//Generated by ErrorPro
dtmc
//Element consts
const int cfblk3_Output_1=0;
const int cfblk5_Output_2=1;
const int cfblk4_Output_3=2;
const int cfblk1_Output_4=3;
const int cfblk2_Output_5=4;
const int cfblk3_Update_6=5;
const int cfblk1_Update_7=6;
const int cfblk2_Update_8=7;
const int check_redandancy0=8;
const int cfblk3_Output_1_2=9;
const int cfblk3_Output_1_3=10;
const int compare0=11;
const int stop_system=12;
const int check_redandancy2=13;
const int cfblk1_Output_4_2=14;
const int cfblk1_Output_4_3=15;
const int compare2=16;
const int check_redandancy3=17;
const int cfblk2_Output_5_2=18;
const int cfblk2_Output_5_3=19;
const int compare3=20;
const int check_redandancy4=21;
const int cfblk3_Update_6_2=22;
const int cfblk3_Update_6_3=23;
const int compare4=24;
const int check_redandancy5=25;
const int cfblk1_Update_7_2=26;
const int cfblk1_Update_7_3=27;
const int compare5=28;
const int check_redandancy6=29;
const int cfblk2_Update_8_2=30;
const int cfblk2_Update_8_3=31;
const int compare6=32;
//Data values consts
const int v=0;
const int prop_2=1;
const int prop_1=2;
const int ok=3;
const int no=4;
const int error=5;
const int c=6;
//Control flow commands
module control_flow
	cf:[0..33] init cfblk3_Output_1;
	//Element cfblk3_Output_1, df inputs ['x_cfblk3_1_2227462984', 'y_cfblk2_1804319944'], cf transitions ['check_redandancy0']
	[cfblk3_Output_1] cf=cfblk3_Output_1 -> 1.0:(cf'=check_redandancy0);
	//Element cfblk5_Output_2, df inputs ['y_cfblk5_1921726123_y_cfblk3_1843455337_y_cfblk1_1765184551'], cf transitions ['cfblk4_Output_3']
	[cfblk5_Output_2] cf=cfblk5_Output_2 -> 1.0:(cf'=cfblk4_Output_3);
	//Element cfblk4_Output_3, df inputs ['y_cfblk5_1921726123_y_cfblk3_1843455337_y_cfblk1_1765184551'], cf transitions ['cfblk1_Output_4']
	[cfblk4_Output_3] cf=cfblk4_Output_3 -> 1.0:(cf'=cfblk1_Output_4);
	//Element cfblk1_Output_4, df inputs ['x_cfblk1_1_3939494341', 'y_cfblk2_1804319944'], cf transitions ['check_redandancy2']
	[cfblk1_Output_4] cf=cfblk1_Output_4 -> 1.0:(cf'=check_redandancy2);
	//Element cfblk2_Output_5, df inputs ['x_cfblk2_1_935995015', 'y_cfblk5_1921726123_y_cfblk3_1843455337_y_cfblk1_1765184551'], cf transitions ['check_redandancy3']
	[cfblk2_Output_5] cf=cfblk2_Output_5 -> 1.0:(cf'=check_redandancy3);
	//Element cfblk3_Update_6, df inputs ['x_cfblk3_1_2227462984', 'y_cfblk2_1804319944'], cf transitions ['check_redandancy4']
	[cfblk3_Update_6] cf=cfblk3_Update_6 -> 1.0:(cf'=check_redandancy4);
	//Element cfblk1_Update_7, df inputs ['x_cfblk1_1_3939494341', 'y_cfblk2_1804319944'], cf transitions ['check_redandancy5']
	[cfblk1_Update_7] cf=cfblk1_Update_7 -> 1.0:(cf'=check_redandancy5);
	//Element cfblk2_Update_8, df inputs ['x_cfblk2_1_935995015', 'y_cfblk5_1921726123_y_cfblk3_1843455337_y_cfblk1_1765184551'], cf transitions ['check_redandancy6']
	[cfblk2_Update_8] cf=cfblk2_Update_8 -> 1.0:(cf'=check_redandancy6);
	//Element check_redandancy0, df inputs ['redundancy_model35_cfblk3_0'], cf transitions ['cfblk3_Output_1_2', 'cfblk5_Output_2']
	[check_redandancy0] (cf=check_redandancy0) & (redundancy_model35_cfblk3_0=no) -> (cf'=cfblk5_Output_2);	// <-- 
	[check_redandancy0] (cf=check_redandancy0) & ((redundancy_model35_cfblk3_0=v)|(redundancy_model35_cfblk3_0=c)) -> (cf'=cfblk3_Output_1_2);	// <-- 
	//Element cfblk3_Output_1_2, df inputs ['x_cfblk3_1_2227462984', 'y_cfblk2_1804319944'], cf transitions ['compare0']
	[cfblk3_Output_1_2] cf=cfblk3_Output_1_2 -> 1.0:(cf'=compare0);
	//Element cfblk3_Output_1_3, df inputs ['x_cfblk3_1_2227462984', 'y_cfblk2_1804319944'], cf transitions ['cfblk5_Output_2']
	[cfblk3_Output_1_3] cf=cfblk3_Output_1_3 -> 1.0:(cf'=cfblk5_Output_2);
	//Element compare0, df inputs ['y_cfblk5_1921726123_y_cfblk3_1843455337_y_cfblk1_1765184551', 'redundancy_model35_cfblk3_0', 'x_cfblk2_1_935995015_2_x_cfblk1_1_3939494341_2_x_cfblk3_1_2227462984_2_y_cfblk2_1804319944_2_y_cfblk1_1765184551_2_y_cfblk3_1843455337_2'], cf transitions ['cfblk3_Output_1_3', 'cfblk5_Output_2', 'stop_system']
	[compare0] (cf=compare0) & (redundancy_model35_cfblk3_0=c) & (y_cfblk5_1921726123_y_cfblk3_1843455337_y_cfblk1_1765184551=prop_1) & (x_cfblk2_1_935995015_2_x_cfblk1_1_3939494341_2_x_cfblk3_1_2227462984_2_y_cfblk2_1804319944_2_y_cfblk1_1765184551_2_y_cfblk3_1843455337_2=prop_1) -> (cf'=cfblk5_Output_2);	// <-- 
	[compare0] (cf=compare0) & (redundancy_model35_cfblk3_0=c) & ((y_cfblk5_1921726123_y_cfblk3_1843455337_y_cfblk1_1765184551=prop_2) | (x_cfblk2_1_935995015_2_x_cfblk1_1_3939494341_2_x_cfblk3_1_2227462984_2_y_cfblk2_1804319944_2_y_cfblk1_1765184551_2_y_cfblk3_1843455337_2=prop_2)) -> (cf'=stop_system);	// <-- 
	[compare0] (cf=compare0) & (redundancy_model35_cfblk3_0=v) & (y_cfblk5_1921726123_y_cfblk3_1843455337_y_cfblk1_1765184551=prop_1) & (x_cfblk2_1_935995015_2_x_cfblk1_1_3939494341_2_x_cfblk3_1_2227462984_2_y_cfblk2_1804319944_2_y_cfblk1_1765184551_2_y_cfblk3_1843455337_2=prop_1) -> (cf'=cfblk5_Output_2);	// <-- 
	[compare0] (cf=compare0) & (redundancy_model35_cfblk3_0=v) & ((y_cfblk5_1921726123_y_cfblk3_1843455337_y_cfblk1_1765184551=prop_2) | (x_cfblk2_1_935995015_2_x_cfblk1_1_3939494341_2_x_cfblk3_1_2227462984_2_y_cfblk2_1804319944_2_y_cfblk1_1765184551_2_y_cfblk3_1843455337_2=prop_2)) -> (cf'=cfblk3_Output_1_3);	// <-- 
	//Element stop_system, cf transitions ['cfblk3_Output_1']
	[stop_system] cf=stop_system -> 1.0:(cf'=cfblk3_Output_1);
	//Element check_redandancy2, df inputs ['redundancy_model35_cfblk1_2'], cf transitions ['cfblk1_Output_4_2', 'cfblk2_Output_5']
	[check_redandancy2] (cf=check_redandancy2) & (redundancy_model35_cfblk1_2=no) -> (cf'=cfblk2_Output_5);	// <-- 
	[check_redandancy2] (cf=check_redandancy2) & ((redundancy_model35_cfblk1_2=v)|(redundancy_model35_cfblk1_2=c)) -> (cf'=cfblk1_Output_4_2);	// <-- 
	//Element cfblk1_Output_4_2, df inputs ['x_cfblk1_1_3939494341', 'y_cfblk2_1804319944'], cf transitions ['compare2']
	[cfblk1_Output_4_2] cf=cfblk1_Output_4_2 -> 1.0:(cf'=compare2);
	//Element cfblk1_Output_4_3, df inputs ['x_cfblk1_1_3939494341', 'y_cfblk2_1804319944'], cf transitions ['cfblk2_Output_5']
	[cfblk1_Output_4_3] cf=cfblk1_Output_4_3 -> 1.0:(cf'=cfblk2_Output_5);
	//Element compare2, df inputs ['y_cfblk5_1921726123_y_cfblk3_1843455337_y_cfblk1_1765184551', 'x_cfblk2_1_935995015_2_x_cfblk1_1_3939494341_2_x_cfblk3_1_2227462984_2_y_cfblk2_1804319944_2_y_cfblk1_1765184551_2_y_cfblk3_1843455337_2', 'redundancy_model35_cfblk1_2'], cf transitions ['cfblk1_Output_4_3', 'cfblk2_Output_5', 'stop_system']
	[compare2] (cf=compare2) & (redundancy_model35_cfblk1_2=c) & (y_cfblk5_1921726123_y_cfblk3_1843455337_y_cfblk1_1765184551=prop_1) & (x_cfblk2_1_935995015_2_x_cfblk1_1_3939494341_2_x_cfblk3_1_2227462984_2_y_cfblk2_1804319944_2_y_cfblk1_1765184551_2_y_cfblk3_1843455337_2=prop_1) -> (cf'=cfblk2_Output_5);	// <-- 
	[compare2] (cf=compare2) & (redundancy_model35_cfblk1_2=c) & ((y_cfblk5_1921726123_y_cfblk3_1843455337_y_cfblk1_1765184551=prop_2) | (x_cfblk2_1_935995015_2_x_cfblk1_1_3939494341_2_x_cfblk3_1_2227462984_2_y_cfblk2_1804319944_2_y_cfblk1_1765184551_2_y_cfblk3_1843455337_2=prop_2)) -> (cf'=stop_system);	// <-- 
	[compare2] (cf=compare2) & (redundancy_model35_cfblk1_2=v) & (y_cfblk5_1921726123_y_cfblk3_1843455337_y_cfblk1_1765184551=prop_1) & (x_cfblk2_1_935995015_2_x_cfblk1_1_3939494341_2_x_cfblk3_1_2227462984_2_y_cfblk2_1804319944_2_y_cfblk1_1765184551_2_y_cfblk3_1843455337_2=prop_1) -> (cf'=cfblk2_Output_5);	// <-- 
	[compare2] (cf=compare2) & (redundancy_model35_cfblk1_2=v) & ((y_cfblk5_1921726123_y_cfblk3_1843455337_y_cfblk1_1765184551=prop_2) | (x_cfblk2_1_935995015_2_x_cfblk1_1_3939494341_2_x_cfblk3_1_2227462984_2_y_cfblk2_1804319944_2_y_cfblk1_1765184551_2_y_cfblk3_1843455337_2=prop_2)) -> (cf'=cfblk1_Output_4_3);	// <-- 
	//Element check_redandancy3, df inputs ['redundancy_model35_cfblk2_3'], cf transitions ['cfblk2_Output_5_2', 'cfblk3_Update_6']
	[check_redandancy3] (cf=check_redandancy3) & (redundancy_model35_cfblk2_3=no) -> (cf'=cfblk3_Update_6);	// <-- 
	[check_redandancy3] (cf=check_redandancy3) & ((redundancy_model35_cfblk2_3=v)|(redundancy_model35_cfblk2_3=c)) -> (cf'=cfblk2_Output_5_2);	// <-- 
	//Element cfblk2_Output_5_2, df inputs ['x_cfblk2_1_935995015', 'y_cfblk5_1921726123_y_cfblk3_1843455337_y_cfblk1_1765184551'], cf transitions ['compare3']
	[cfblk2_Output_5_2] cf=cfblk2_Output_5_2 -> 1.0:(cf'=compare3);
	//Element cfblk2_Output_5_3, df inputs ['x_cfblk2_1_935995015', 'y_cfblk5_1921726123_y_cfblk3_1843455337_y_cfblk1_1765184551'], cf transitions ['cfblk3_Update_6']
	[cfblk2_Output_5_3] cf=cfblk2_Output_5_3 -> 1.0:(cf'=cfblk3_Update_6);
	//Element compare3, df inputs ['redundancy_model35_cfblk2_3', 'x_cfblk2_1_935995015_2_x_cfblk1_1_3939494341_2_x_cfblk3_1_2227462984_2_y_cfblk2_1804319944_2_y_cfblk1_1765184551_2_y_cfblk3_1843455337_2', 'y_cfblk2_1804319944'], cf transitions ['cfblk2_Output_5_3', 'cfblk3_Update_6', 'stop_system']
	[compare3] (cf=compare3) & (redundancy_model35_cfblk2_3=c) & (y_cfblk2_1804319944=ok) & (x_cfblk2_1_935995015_2_x_cfblk1_1_3939494341_2_x_cfblk3_1_2227462984_2_y_cfblk2_1804319944_2_y_cfblk1_1765184551_2_y_cfblk3_1843455337_2=prop_1) -> (cf'=cfblk3_Update_6);	// <-- 
	[compare3] (cf=compare3) & (redundancy_model35_cfblk2_3=c) & ((y_cfblk2_1804319944=error) | (x_cfblk2_1_935995015_2_x_cfblk1_1_3939494341_2_x_cfblk3_1_2227462984_2_y_cfblk2_1804319944_2_y_cfblk1_1765184551_2_y_cfblk3_1843455337_2=prop_2)) -> (cf'=stop_system);	// <-- 
	[compare3] (cf=compare3) & (redundancy_model35_cfblk2_3=v) & (y_cfblk2_1804319944=ok) & (x_cfblk2_1_935995015_2_x_cfblk1_1_3939494341_2_x_cfblk3_1_2227462984_2_y_cfblk2_1804319944_2_y_cfblk1_1765184551_2_y_cfblk3_1843455337_2=prop_1) -> (cf'=cfblk3_Update_6);	// <-- 
	[compare3] (cf=compare3) & (redundancy_model35_cfblk2_3=v) & ((y_cfblk2_1804319944=error) | (x_cfblk2_1_935995015_2_x_cfblk1_1_3939494341_2_x_cfblk3_1_2227462984_2_y_cfblk2_1804319944_2_y_cfblk1_1765184551_2_y_cfblk3_1843455337_2=prop_2)) -> (cf'=cfblk2_Output_5_3);	// <-- 
	//Element check_redandancy4, df inputs ['redundancy_model35_cfblk3_0'], cf transitions ['cfblk3_Update_6_2', 'cfblk1_Update_7']
	[check_redandancy4] (cf=check_redandancy4) & (redundancy_model35_cfblk3_0=no) -> (cf'=cfblk1_Update_7);	// <-- 
	[check_redandancy4] (cf=check_redandancy4) & ((redundancy_model35_cfblk3_0=v)|(redundancy_model35_cfblk3_0=c)) -> (cf'=cfblk3_Update_6_2);	// <-- 
	//Element cfblk3_Update_6_2, df inputs ['x_cfblk3_1_2227462984', 'y_cfblk2_1804319944'], cf transitions ['compare4']
	[cfblk3_Update_6_2] cf=cfblk3_Update_6_2 -> 1.0:(cf'=compare4);
	//Element cfblk3_Update_6_3, df inputs ['x_cfblk3_1_2227462984', 'y_cfblk2_1804319944'], cf transitions ['cfblk1_Update_7']
	[cfblk3_Update_6_3] cf=cfblk3_Update_6_3 -> 1.0:(cf'=cfblk1_Update_7);
	//Element compare4, df inputs ['x_cfblk2_1_935995015_2_x_cfblk1_1_3939494341_2_x_cfblk3_1_2227462984_2_y_cfblk2_1804319944_2_y_cfblk1_1765184551_2_y_cfblk3_1843455337_2', 'x_cfblk3_1_2227462984', 'redundancy_model35_cfblk3_0'], cf transitions ['cfblk3_Update_6_3', 'cfblk1_Update_7', 'stop_system']
	[compare4] (cf=compare4) & (redundancy_model35_cfblk3_0=c) & (x_cfblk3_1_2227462984=ok) & (x_cfblk2_1_935995015_2_x_cfblk1_1_3939494341_2_x_cfblk3_1_2227462984_2_y_cfblk2_1804319944_2_y_cfblk1_1765184551_2_y_cfblk3_1843455337_2=prop_1) -> (cf'=cfblk1_Update_7);	// <-- 
	[compare4] (cf=compare4) & (redundancy_model35_cfblk3_0=c) & ((x_cfblk3_1_2227462984=error) | (x_cfblk2_1_935995015_2_x_cfblk1_1_3939494341_2_x_cfblk3_1_2227462984_2_y_cfblk2_1804319944_2_y_cfblk1_1765184551_2_y_cfblk3_1843455337_2=prop_2)) -> (cf'=stop_system);	// <-- 
	[compare4] (cf=compare4) & (redundancy_model35_cfblk3_0=v) & (x_cfblk3_1_2227462984=ok) & (x_cfblk2_1_935995015_2_x_cfblk1_1_3939494341_2_x_cfblk3_1_2227462984_2_y_cfblk2_1804319944_2_y_cfblk1_1765184551_2_y_cfblk3_1843455337_2=prop_1) -> (cf'=cfblk1_Update_7);	// <-- 
	[compare4] (cf=compare4) & (redundancy_model35_cfblk3_0=v) & ((x_cfblk3_1_2227462984=error) | (x_cfblk2_1_935995015_2_x_cfblk1_1_3939494341_2_x_cfblk3_1_2227462984_2_y_cfblk2_1804319944_2_y_cfblk1_1765184551_2_y_cfblk3_1843455337_2=prop_2)) -> (cf'=cfblk3_Update_6_3);	// <-- 
	//Element check_redandancy5, df inputs ['redundancy_model35_cfblk1_2'], cf transitions ['cfblk1_Update_7_2', 'cfblk2_Update_8']
	[check_redandancy5] (cf=check_redandancy5) & (redundancy_model35_cfblk1_2=no) -> (cf'=cfblk2_Update_8);	// <-- 
	[check_redandancy5] (cf=check_redandancy5) & ((redundancy_model35_cfblk1_2=v)|(redundancy_model35_cfblk1_2=c)) -> (cf'=cfblk1_Update_7_2);	// <-- 
	//Element cfblk1_Update_7_2, df inputs ['x_cfblk1_1_3939494341', 'y_cfblk2_1804319944'], cf transitions ['compare5']
	[cfblk1_Update_7_2] cf=cfblk1_Update_7_2 -> 1.0:(cf'=compare5);
	//Element cfblk1_Update_7_3, df inputs ['x_cfblk1_1_3939494341', 'y_cfblk2_1804319944'], cf transitions ['cfblk2_Update_8']
	[cfblk1_Update_7_3] cf=cfblk1_Update_7_3 -> 1.0:(cf'=cfblk2_Update_8);
	//Element compare5, df inputs ['x_cfblk2_1_935995015_2_x_cfblk1_1_3939494341_2_x_cfblk3_1_2227462984_2_y_cfblk2_1804319944_2_y_cfblk1_1765184551_2_y_cfblk3_1843455337_2', 'x_cfblk1_1_3939494341', 'redundancy_model35_cfblk1_2'], cf transitions ['cfblk1_Update_7_3', 'cfblk2_Update_8', 'stop_system']
	[compare5] (cf=compare5) & (redundancy_model35_cfblk1_2=c) & (x_cfblk1_1_3939494341=ok) & (x_cfblk2_1_935995015_2_x_cfblk1_1_3939494341_2_x_cfblk3_1_2227462984_2_y_cfblk2_1804319944_2_y_cfblk1_1765184551_2_y_cfblk3_1843455337_2=prop_1) -> (cf'=cfblk2_Update_8);	// <-- 
	[compare5] (cf=compare5) & (redundancy_model35_cfblk1_2=c) & ((x_cfblk1_1_3939494341=error) | (x_cfblk2_1_935995015_2_x_cfblk1_1_3939494341_2_x_cfblk3_1_2227462984_2_y_cfblk2_1804319944_2_y_cfblk1_1765184551_2_y_cfblk3_1843455337_2=prop_2)) -> (cf'=stop_system);	// <-- 
	[compare5] (cf=compare5) & (redundancy_model35_cfblk1_2=v) & (x_cfblk1_1_3939494341=ok) & (x_cfblk2_1_935995015_2_x_cfblk1_1_3939494341_2_x_cfblk3_1_2227462984_2_y_cfblk2_1804319944_2_y_cfblk1_1765184551_2_y_cfblk3_1843455337_2=prop_1) -> (cf'=cfblk2_Update_8);	// <-- 
	[compare5] (cf=compare5) & (redundancy_model35_cfblk1_2=v) & ((x_cfblk1_1_3939494341=error) | (x_cfblk2_1_935995015_2_x_cfblk1_1_3939494341_2_x_cfblk3_1_2227462984_2_y_cfblk2_1804319944_2_y_cfblk1_1765184551_2_y_cfblk3_1843455337_2=prop_2)) -> (cf'=cfblk1_Update_7_3);	// <-- 
	//Element check_redandancy6, df inputs ['redundancy_model35_cfblk2_3'], cf transitions ['cfblk2_Update_8_2', 'cfblk3_Output_1']
	[check_redandancy6] (cf=check_redandancy6) & (redundancy_model35_cfblk2_3=no) -> (cf'=cfblk3_Output_1);	// <-- 
	[check_redandancy6] (cf=check_redandancy6) & ((redundancy_model35_cfblk2_3=v)|(redundancy_model35_cfblk2_3=c)) -> (cf'=cfblk2_Update_8_2);	// <-- 
	//Element cfblk2_Update_8_2, df inputs ['x_cfblk2_1_935995015', 'y_cfblk5_1921726123_y_cfblk3_1843455337_y_cfblk1_1765184551'], cf transitions ['compare6']
	[cfblk2_Update_8_2] cf=cfblk2_Update_8_2 -> 1.0:(cf'=compare6);
	//Element cfblk2_Update_8_3, df inputs ['x_cfblk2_1_935995015', 'y_cfblk5_1921726123_y_cfblk3_1843455337_y_cfblk1_1765184551'], cf transitions ['cfblk3_Output_1']
	[cfblk2_Update_8_3] cf=cfblk2_Update_8_3 -> 1.0:(cf'=cfblk3_Output_1);
	//Element compare6, df inputs ['redundancy_model35_cfblk2_3', 'x_cfblk2_1_935995015', 'x_cfblk2_1_935995015_2_x_cfblk1_1_3939494341_2_x_cfblk3_1_2227462984_2_y_cfblk2_1804319944_2_y_cfblk1_1765184551_2_y_cfblk3_1843455337_2'], cf transitions ['cfblk2_Update_8_3', 'cfblk3_Output_1', 'stop_system']
	[compare6] (cf=compare6) & (redundancy_model35_cfblk2_3=c) & (x_cfblk2_1_935995015=ok) & (x_cfblk2_1_935995015_2_x_cfblk1_1_3939494341_2_x_cfblk3_1_2227462984_2_y_cfblk2_1804319944_2_y_cfblk1_1765184551_2_y_cfblk3_1843455337_2=prop_1) -> (cf'=cfblk3_Output_1);	// <-- 
	[compare6] (cf=compare6) & (redundancy_model35_cfblk2_3=c) & ((x_cfblk2_1_935995015=error) | (x_cfblk2_1_935995015_2_x_cfblk1_1_3939494341_2_x_cfblk3_1_2227462984_2_y_cfblk2_1804319944_2_y_cfblk1_1765184551_2_y_cfblk3_1843455337_2=prop_2)) -> (cf'=stop_system);	// <-- 
	[compare6] (cf=compare6) & (redundancy_model35_cfblk2_3=v) & (x_cfblk2_1_935995015=ok) & (x_cfblk2_1_935995015_2_x_cfblk1_1_3939494341_2_x_cfblk3_1_2227462984_2_y_cfblk2_1804319944_2_y_cfblk1_1765184551_2_y_cfblk3_1843455337_2=prop_1) -> (cf'=cfblk3_Output_1);	// <-- 
	[compare6] (cf=compare6) & (redundancy_model35_cfblk2_3=v) & ((x_cfblk2_1_935995015=error) | (x_cfblk2_1_935995015_2_x_cfblk1_1_3939494341_2_x_cfblk3_1_2227462984_2_y_cfblk2_1804319944_2_y_cfblk1_1765184551_2_y_cfblk3_1843455337_2=prop_2)) -> (cf'=cfblk2_Update_8_3);	// <-- 
endmodule
//Error propagation commands
module error_propagation
	y_cfblk2_1804319944 : [0 .. 6] init ok;
	x_cfblk3_1_2227462984 : [0 .. 6] init ok;
	x_cfblk1_1_3939494341 : [0 .. 6] init ok;
	x_cfblk2_1_935995015 : [0 .. 6] init ok;
	redundancy_model35_cfblk3_0 : [0 .. 6] init no;
	redundancy_model35_cfblk1_2 : [0 .. 6] init c;
	redundancy_model35_cfblk2_3 : [0 .. 6] init c;
	x_cfblk2_1_935995015_2_x_cfblk1_1_3939494341_2_x_cfblk3_1_2227462984_2_y_cfblk2_1804319944_2_y_cfblk1_1765184551_2_y_cfblk3_1843455337_2 : [0 .. 6] init prop_1;
	y_cfblk5_1921726123_y_cfblk3_1843455337_y_cfblk1_1765184551 : [0 .. 6] init prop_1;
	//Element cfblk3_Output_1, df inputs ['x_cfblk3_1_2227462984', 'y_cfblk2_1804319944'], df outputs ['y_cfblk5_1921726123_y_cfblk3_1843455337_y_cfblk1_1765184551']
	[cfblk3_Output_1] (y_cfblk2_1804319944=ok) & (x_cfblk3_1_2227462984=ok) -> 0.98:(y_cfblk5_1921726123_y_cfblk3_1843455337_y_cfblk1_1765184551'=prop_1) + 0.02:(y_cfblk5_1921726123_y_cfblk3_1843455337_y_cfblk1_1765184551'=prop_2);	// <-- 
	[cfblk3_Output_1] (y_cfblk2_1804319944!=ok) | (x_cfblk3_1_2227462984!=ok) -> (y_cfblk5_1921726123_y_cfblk3_1843455337_y_cfblk1_1765184551'=prop_2);	// <-- 
	//Element cfblk5_Output_2, df inputs ['y_cfblk5_1921726123_y_cfblk3_1843455337_y_cfblk1_1765184551'], df outputs ['y_cfblk5_1921726123_y_cfblk3_1843455337_y_cfblk1_1765184551']
	[cfblk5_Output_2] (y_cfblk5_1921726123_y_cfblk3_1843455337_y_cfblk1_1765184551=prop_1) -> 0.969003039904:(y_cfblk5_1921726123_y_cfblk3_1843455337_y_cfblk1_1765184551'=prop_1) + 0.030996960095999997:(y_cfblk5_1921726123_y_cfblk3_1843455337_y_cfblk1_1765184551'=prop_2);	// <-- 
	[cfblk5_Output_2] (y_cfblk5_1921726123_y_cfblk3_1843455337_y_cfblk1_1765184551!=prop_1) -> (y_cfblk5_1921726123_y_cfblk3_1843455337_y_cfblk1_1765184551'=prop_2);	// <-- 
	//Element cfblk1_Output_4, df inputs ['x_cfblk1_1_3939494341', 'y_cfblk2_1804319944'], df outputs ['y_cfblk5_1921726123_y_cfblk3_1843455337_y_cfblk1_1765184551']
	[cfblk1_Output_4] (y_cfblk2_1804319944=ok) & (x_cfblk1_1_3939494341=ok) -> 0.98:(y_cfblk5_1921726123_y_cfblk3_1843455337_y_cfblk1_1765184551'=prop_1) + 0.02:(y_cfblk5_1921726123_y_cfblk3_1843455337_y_cfblk1_1765184551'=prop_2);	// <-- 
	[cfblk1_Output_4] (y_cfblk2_1804319944!=ok) | (x_cfblk1_1_3939494341!=ok) -> (y_cfblk5_1921726123_y_cfblk3_1843455337_y_cfblk1_1765184551'=prop_2);	// <-- 
	//Element cfblk2_Output_5, df inputs ['x_cfblk2_1_935995015', 'y_cfblk5_1921726123_y_cfblk3_1843455337_y_cfblk1_1765184551'], df outputs ['y_cfblk2_1804319944']
	[cfblk2_Output_5] (y_cfblk5_1921726123_y_cfblk3_1843455337_y_cfblk1_1765184551=prop_1) & (x_cfblk2_1_935995015=ok) -> 0.98:(y_cfblk2_1804319944'=ok) + 0.02:(y_cfblk2_1804319944'=error);	// <-- 
	[cfblk2_Output_5] (y_cfblk5_1921726123_y_cfblk3_1843455337_y_cfblk1_1765184551!=prop_1) | (x_cfblk2_1_935995015!=ok) -> (y_cfblk2_1804319944'=error);	// <-- 
	//Element cfblk3_Update_6, df inputs ['x_cfblk3_1_2227462984', 'y_cfblk2_1804319944'], df outputs ['x_cfblk3_1_2227462984']
	[cfblk3_Update_6] (y_cfblk2_1804319944=ok) & (x_cfblk3_1_2227462984=ok) -> 0.98:(x_cfblk3_1_2227462984'=ok) + 0.02:(x_cfblk3_1_2227462984'=error);	// <-- 
	[cfblk3_Update_6] (y_cfblk2_1804319944!=ok) | (x_cfblk3_1_2227462984!=ok) -> (x_cfblk3_1_2227462984'=error);	// <-- 
	//Element cfblk1_Update_7, df inputs ['x_cfblk1_1_3939494341', 'y_cfblk2_1804319944'], df outputs ['x_cfblk1_1_3939494341']
	[cfblk1_Update_7] (y_cfblk2_1804319944=ok) & (x_cfblk1_1_3939494341=ok) -> 0.98:(x_cfblk1_1_3939494341'=ok) + 0.02:(x_cfblk1_1_3939494341'=error);	// <-- 
	[cfblk1_Update_7] (y_cfblk2_1804319944!=ok) | (x_cfblk1_1_3939494341!=ok) -> (x_cfblk1_1_3939494341'=error);	// <-- 
	//Element cfblk2_Update_8, df inputs ['x_cfblk2_1_935995015', 'y_cfblk5_1921726123_y_cfblk3_1843455337_y_cfblk1_1765184551'], df outputs ['x_cfblk2_1_935995015']
	[cfblk2_Update_8] (y_cfblk5_1921726123_y_cfblk3_1843455337_y_cfblk1_1765184551=prop_1) & (x_cfblk2_1_935995015=ok) -> 0.98:(x_cfblk2_1_935995015'=ok) + 0.02:(x_cfblk2_1_935995015'=error);	// <-- 
	[cfblk2_Update_8] (y_cfblk5_1921726123_y_cfblk3_1843455337_y_cfblk1_1765184551!=prop_1) | (x_cfblk2_1_935995015!=ok) -> (x_cfblk2_1_935995015'=error);	// <-- 
	//Element cfblk3_Output_1_2, df inputs ['x_cfblk3_1_2227462984', 'y_cfblk2_1804319944'], df outputs ['x_cfblk2_1_935995015_2_x_cfblk1_1_3939494341_2_x_cfblk3_1_2227462984_2_y_cfblk2_1804319944_2_y_cfblk1_1765184551_2_y_cfblk3_1843455337_2']
	[cfblk3_Output_1_2] (y_cfblk2_1804319944=ok) & (x_cfblk3_1_2227462984=ok) -> 0.98:(x_cfblk2_1_935995015_2_x_cfblk1_1_3939494341_2_x_cfblk3_1_2227462984_2_y_cfblk2_1804319944_2_y_cfblk1_1765184551_2_y_cfblk3_1843455337_2'=prop_1) + 0.02:(x_cfblk2_1_935995015_2_x_cfblk1_1_3939494341_2_x_cfblk3_1_2227462984_2_y_cfblk2_1804319944_2_y_cfblk1_1765184551_2_y_cfblk3_1843455337_2'=prop_2);	// <-- 
	[cfblk3_Output_1_2] (y_cfblk2_1804319944!=ok) | (x_cfblk3_1_2227462984!=ok) -> (x_cfblk2_1_935995015_2_x_cfblk1_1_3939494341_2_x_cfblk3_1_2227462984_2_y_cfblk2_1804319944_2_y_cfblk1_1765184551_2_y_cfblk3_1843455337_2'=prop_2);	// <-- 
	//Element cfblk3_Output_1_3, df inputs ['x_cfblk3_1_2227462984', 'y_cfblk2_1804319944'], df outputs ['y_cfblk5_1921726123_y_cfblk3_1843455337_y_cfblk1_1765184551']
	[cfblk3_Output_1_3] (y_cfblk2_1804319944=ok) & (x_cfblk3_1_2227462984=ok) -> 0.98:(y_cfblk5_1921726123_y_cfblk3_1843455337_y_cfblk1_1765184551'=prop_1) + 0.02:(y_cfblk5_1921726123_y_cfblk3_1843455337_y_cfblk1_1765184551'=prop_2);	// <-- 
	[cfblk3_Output_1_3] (y_cfblk2_1804319944!=ok) | (x_cfblk3_1_2227462984!=ok) -> (y_cfblk5_1921726123_y_cfblk3_1843455337_y_cfblk1_1765184551'=prop_2);	// <-- 
	//Element cfblk1_Output_4_2, df inputs ['x_cfblk1_1_3939494341', 'y_cfblk2_1804319944'], df outputs ['x_cfblk2_1_935995015_2_x_cfblk1_1_3939494341_2_x_cfblk3_1_2227462984_2_y_cfblk2_1804319944_2_y_cfblk1_1765184551_2_y_cfblk3_1843455337_2']
	[cfblk1_Output_4_2] (y_cfblk2_1804319944=ok) & (x_cfblk1_1_3939494341=ok) -> 0.98:(x_cfblk2_1_935995015_2_x_cfblk1_1_3939494341_2_x_cfblk3_1_2227462984_2_y_cfblk2_1804319944_2_y_cfblk1_1765184551_2_y_cfblk3_1843455337_2'=prop_1) + 0.02:(x_cfblk2_1_935995015_2_x_cfblk1_1_3939494341_2_x_cfblk3_1_2227462984_2_y_cfblk2_1804319944_2_y_cfblk1_1765184551_2_y_cfblk3_1843455337_2'=prop_2);	// <-- 
	[cfblk1_Output_4_2] (y_cfblk2_1804319944!=ok) | (x_cfblk1_1_3939494341!=ok) -> (x_cfblk2_1_935995015_2_x_cfblk1_1_3939494341_2_x_cfblk3_1_2227462984_2_y_cfblk2_1804319944_2_y_cfblk1_1765184551_2_y_cfblk3_1843455337_2'=prop_2);	// <-- 
	//Element cfblk1_Output_4_3, df inputs ['x_cfblk1_1_3939494341', 'y_cfblk2_1804319944'], df outputs ['y_cfblk5_1921726123_y_cfblk3_1843455337_y_cfblk1_1765184551']
	[cfblk1_Output_4_3] (y_cfblk2_1804319944=ok) & (x_cfblk1_1_3939494341=ok) -> 0.98:(y_cfblk5_1921726123_y_cfblk3_1843455337_y_cfblk1_1765184551'=prop_1) + 0.02:(y_cfblk5_1921726123_y_cfblk3_1843455337_y_cfblk1_1765184551'=prop_2);	// <-- 
	[cfblk1_Output_4_3] (y_cfblk2_1804319944!=ok) | (x_cfblk1_1_3939494341!=ok) -> (y_cfblk5_1921726123_y_cfblk3_1843455337_y_cfblk1_1765184551'=prop_2);	// <-- 
	//Element cfblk2_Output_5_2, df inputs ['x_cfblk2_1_935995015', 'y_cfblk5_1921726123_y_cfblk3_1843455337_y_cfblk1_1765184551'], df outputs ['x_cfblk2_1_935995015_2_x_cfblk1_1_3939494341_2_x_cfblk3_1_2227462984_2_y_cfblk2_1804319944_2_y_cfblk1_1765184551_2_y_cfblk3_1843455337_2']
	[cfblk2_Output_5_2] (y_cfblk5_1921726123_y_cfblk3_1843455337_y_cfblk1_1765184551=prop_1) & (x_cfblk2_1_935995015=ok) -> 0.98:(x_cfblk2_1_935995015_2_x_cfblk1_1_3939494341_2_x_cfblk3_1_2227462984_2_y_cfblk2_1804319944_2_y_cfblk1_1765184551_2_y_cfblk3_1843455337_2'=prop_1) + 0.02:(x_cfblk2_1_935995015_2_x_cfblk1_1_3939494341_2_x_cfblk3_1_2227462984_2_y_cfblk2_1804319944_2_y_cfblk1_1765184551_2_y_cfblk3_1843455337_2'=prop_2);	// <-- 
	[cfblk2_Output_5_2] (y_cfblk5_1921726123_y_cfblk3_1843455337_y_cfblk1_1765184551!=prop_1) | (x_cfblk2_1_935995015!=ok) -> (x_cfblk2_1_935995015_2_x_cfblk1_1_3939494341_2_x_cfblk3_1_2227462984_2_y_cfblk2_1804319944_2_y_cfblk1_1765184551_2_y_cfblk3_1843455337_2'=prop_2);	// <-- 
	//Element cfblk2_Output_5_3, df inputs ['x_cfblk2_1_935995015', 'y_cfblk5_1921726123_y_cfblk3_1843455337_y_cfblk1_1765184551'], df outputs ['y_cfblk2_1804319944']
	[cfblk2_Output_5_3] (y_cfblk5_1921726123_y_cfblk3_1843455337_y_cfblk1_1765184551=prop_1) & (x_cfblk2_1_935995015=ok) -> 0.98:(y_cfblk2_1804319944'=ok) + 0.02:(y_cfblk2_1804319944'=error);	// <-- 
	[cfblk2_Output_5_3] (y_cfblk5_1921726123_y_cfblk3_1843455337_y_cfblk1_1765184551!=prop_1) | (x_cfblk2_1_935995015!=ok) -> (y_cfblk2_1804319944'=error);	// <-- 
	//Element cfblk3_Update_6_2, df inputs ['x_cfblk3_1_2227462984', 'y_cfblk2_1804319944'], df outputs ['x_cfblk2_1_935995015_2_x_cfblk1_1_3939494341_2_x_cfblk3_1_2227462984_2_y_cfblk2_1804319944_2_y_cfblk1_1765184551_2_y_cfblk3_1843455337_2']
	[cfblk3_Update_6_2] (y_cfblk2_1804319944=ok) & (x_cfblk3_1_2227462984=ok) -> 0.98:(x_cfblk2_1_935995015_2_x_cfblk1_1_3939494341_2_x_cfblk3_1_2227462984_2_y_cfblk2_1804319944_2_y_cfblk1_1765184551_2_y_cfblk3_1843455337_2'=prop_1) + 0.02:(x_cfblk2_1_935995015_2_x_cfblk1_1_3939494341_2_x_cfblk3_1_2227462984_2_y_cfblk2_1804319944_2_y_cfblk1_1765184551_2_y_cfblk3_1843455337_2'=prop_2);	// <-- 
	[cfblk3_Update_6_2] (y_cfblk2_1804319944!=ok) | (x_cfblk3_1_2227462984!=ok) -> (x_cfblk2_1_935995015_2_x_cfblk1_1_3939494341_2_x_cfblk3_1_2227462984_2_y_cfblk2_1804319944_2_y_cfblk1_1765184551_2_y_cfblk3_1843455337_2'=prop_2);	// <-- 
	//Element cfblk3_Update_6_3, df inputs ['x_cfblk3_1_2227462984', 'y_cfblk2_1804319944'], df outputs ['x_cfblk3_1_2227462984']
	[cfblk3_Update_6_3] (y_cfblk2_1804319944=ok) & (x_cfblk3_1_2227462984=ok) -> 0.98:(x_cfblk3_1_2227462984'=ok) + 0.02:(x_cfblk3_1_2227462984'=error);	// <-- 
	[cfblk3_Update_6_3] (y_cfblk2_1804319944!=ok) | (x_cfblk3_1_2227462984!=ok) -> (x_cfblk3_1_2227462984'=error);	// <-- 
	//Element cfblk1_Update_7_2, df inputs ['x_cfblk1_1_3939494341', 'y_cfblk2_1804319944'], df outputs ['x_cfblk2_1_935995015_2_x_cfblk1_1_3939494341_2_x_cfblk3_1_2227462984_2_y_cfblk2_1804319944_2_y_cfblk1_1765184551_2_y_cfblk3_1843455337_2']
	[cfblk1_Update_7_2] (y_cfblk2_1804319944=ok) & (x_cfblk1_1_3939494341=ok) -> 0.98:(x_cfblk2_1_935995015_2_x_cfblk1_1_3939494341_2_x_cfblk3_1_2227462984_2_y_cfblk2_1804319944_2_y_cfblk1_1765184551_2_y_cfblk3_1843455337_2'=prop_1) + 0.02:(x_cfblk2_1_935995015_2_x_cfblk1_1_3939494341_2_x_cfblk3_1_2227462984_2_y_cfblk2_1804319944_2_y_cfblk1_1765184551_2_y_cfblk3_1843455337_2'=prop_2);	// <-- 
	[cfblk1_Update_7_2] (y_cfblk2_1804319944!=ok) | (x_cfblk1_1_3939494341!=ok) -> (x_cfblk2_1_935995015_2_x_cfblk1_1_3939494341_2_x_cfblk3_1_2227462984_2_y_cfblk2_1804319944_2_y_cfblk1_1765184551_2_y_cfblk3_1843455337_2'=prop_2);	// <-- 
	//Element cfblk1_Update_7_3, df inputs ['x_cfblk1_1_3939494341', 'y_cfblk2_1804319944'], df outputs ['x_cfblk1_1_3939494341']
	[cfblk1_Update_7_3] (y_cfblk2_1804319944=ok) & (x_cfblk1_1_3939494341=ok) -> 0.98:(x_cfblk1_1_3939494341'=ok) + 0.02:(x_cfblk1_1_3939494341'=error);	// <-- 
	[cfblk1_Update_7_3] (y_cfblk2_1804319944!=ok) | (x_cfblk1_1_3939494341!=ok) -> (x_cfblk1_1_3939494341'=error);	// <-- 
	//Element cfblk2_Update_8_2, df inputs ['x_cfblk2_1_935995015', 'y_cfblk5_1921726123_y_cfblk3_1843455337_y_cfblk1_1765184551'], df outputs ['x_cfblk2_1_935995015_2_x_cfblk1_1_3939494341_2_x_cfblk3_1_2227462984_2_y_cfblk2_1804319944_2_y_cfblk1_1765184551_2_y_cfblk3_1843455337_2']
	[cfblk2_Update_8_2] (y_cfblk5_1921726123_y_cfblk3_1843455337_y_cfblk1_1765184551=prop_1) & (x_cfblk2_1_935995015=ok) -> 0.98:(x_cfblk2_1_935995015_2_x_cfblk1_1_3939494341_2_x_cfblk3_1_2227462984_2_y_cfblk2_1804319944_2_y_cfblk1_1765184551_2_y_cfblk3_1843455337_2'=prop_1) + 0.02:(x_cfblk2_1_935995015_2_x_cfblk1_1_3939494341_2_x_cfblk3_1_2227462984_2_y_cfblk2_1804319944_2_y_cfblk1_1765184551_2_y_cfblk3_1843455337_2'=prop_2);	// <-- 
	[cfblk2_Update_8_2] (y_cfblk5_1921726123_y_cfblk3_1843455337_y_cfblk1_1765184551!=prop_1) | (x_cfblk2_1_935995015!=ok) -> (x_cfblk2_1_935995015_2_x_cfblk1_1_3939494341_2_x_cfblk3_1_2227462984_2_y_cfblk2_1804319944_2_y_cfblk1_1765184551_2_y_cfblk3_1843455337_2'=prop_2);	// <-- 
	//Element cfblk2_Update_8_3, df inputs ['x_cfblk2_1_935995015', 'y_cfblk5_1921726123_y_cfblk3_1843455337_y_cfblk1_1765184551'], df outputs ['x_cfblk2_1_935995015']
	[cfblk2_Update_8_3] (y_cfblk5_1921726123_y_cfblk3_1843455337_y_cfblk1_1765184551=prop_1) & (x_cfblk2_1_935995015=ok) -> 0.98:(x_cfblk2_1_935995015'=ok) + 0.02:(x_cfblk2_1_935995015'=error);	// <-- 
	[cfblk2_Update_8_3] (y_cfblk5_1921726123_y_cfblk3_1843455337_y_cfblk1_1765184551!=prop_1) | (x_cfblk2_1_935995015!=ok) -> (x_cfblk2_1_935995015'=error);	// <-- 
endmodule

//Failure formulas
formula failure = x_cfblk2_1_935995015 = error;

rewards "time" true : 1; endrewards
