//Generated by ErrorPro
dtmc
//Element consts
const int cfblk1_Output_1=0;
const int cfblk4_Output_2=1;
const int cfblk5_Output_3=2;
const int cfblk3_Output_4=3;
const int cfblk2_Output_5=4;
const int cfblk1_Update_6=5;
const int check_redandancy0=6;
const int cfblk1_Output_1_2=7;
const int cfblk1_Output_1_3=8;
const int compare0=9;
const int stop_system=10;
const int check_redandancy1=11;
const int cfblk4_Output_2_2=12;
const int cfblk4_Output_2_3=13;
const int compare1=14;
const int check_redandancy2=15;
const int cfblk3_Output_4_2=16;
const int cfblk3_Output_4_3=17;
const int compare2=18;
const int check_redandancy4=19;
const int cfblk1_Update_6_2=20;
const int cfblk1_Update_6_3=21;
const int compare4=22;
//Data values consts
const int v=0;
const int ok=1;
const int no=2;
const int error=3;
const int c=4;
//Control flow commands
module control_flow
	cf:[0..23] init cfblk1_Output_1;
	//Element cfblk1_Output_1, df inputs ['y_cfblk5_2786651446', 'x_cfblk1_1_2417258935'], cf transitions ['check_redandancy0']
	[cfblk1_Output_1] cf=cfblk1_Output_1 -> 1.0:(cf'=check_redandancy0);
	//Element cfblk4_Output_2, cf transitions ['check_redandancy1']
	[cfblk4_Output_2] cf=cfblk4_Output_2 -> 1.0:(cf'=check_redandancy1);
	//Element cfblk5_Output_3, df inputs ['y_cfblk1_2630109874', 'y_cfblk4_2747516053'], cf transitions ['cfblk3_Output_4']
	[cfblk5_Output_3] cf=cfblk5_Output_3 -> 1.0:(cf'=cfblk3_Output_4);
	//Element cfblk3_Output_4, cf transitions ['check_redandancy2']
	[cfblk3_Output_4] cf=cfblk3_Output_4 -> 1.0:(cf'=check_redandancy2);
	//Element cfblk2_Output_5, df inputs ['y_cfblk3_2708380660'], cf transitions ['cfblk1_Update_6']
	[cfblk2_Output_5] cf=cfblk2_Output_5 -> 1.0:(cf'=cfblk1_Update_6);
	//Element cfblk1_Update_6, df inputs ['y_cfblk5_2786651446', 'x_cfblk1_1_2417258935'], cf transitions ['check_redandancy4']
	[cfblk1_Update_6] cf=cfblk1_Update_6 -> 1.0:(cf'=check_redandancy4);
	//Element check_redandancy0, df inputs ['redundancy_model38_cfblk1_0'], cf transitions ['cfblk1_Output_1_2', 'cfblk4_Output_2']
	[check_redandancy0] (cf=check_redandancy0) & (redundancy_model38_cfblk1_0=no) -> (cf'=cfblk4_Output_2);	// <-- 
	[check_redandancy0] (cf=check_redandancy0) & ((redundancy_model38_cfblk1_0=v)|(redundancy_model38_cfblk1_0=c)) -> (cf'=cfblk1_Output_1_2);	// <-- 
	//Element cfblk1_Output_1_2, df inputs ['y_cfblk5_2786651446', 'x_cfblk1_1_2417258935'], cf transitions ['compare0']
	[cfblk1_Output_1_2] cf=cfblk1_Output_1_2 -> 1.0:(cf'=compare0);
	//Element cfblk1_Output_1_3, df inputs ['y_cfblk5_2786651446', 'x_cfblk1_1_2417258935'], cf transitions ['cfblk4_Output_2']
	[cfblk1_Output_1_3] cf=cfblk1_Output_1_3 -> 1.0:(cf'=cfblk4_Output_2);
	//Element compare0, df inputs ['redundancy_model38_cfblk1_0', 'y_cfblk1_2630109874_2', 'y_cfblk1_2630109874'], cf transitions ['cfblk1_Output_1_3', 'cfblk4_Output_2', 'stop_system']
	[compare0] (cf=compare0) & (redundancy_model38_cfblk1_0=c) & (y_cfblk1_2630109874=ok) & (y_cfblk1_2630109874_2=ok) -> (cf'=cfblk4_Output_2);	// <-- 
	[compare0] (cf=compare0) & (redundancy_model38_cfblk1_0=c) & ((y_cfblk1_2630109874=error) | (y_cfblk1_2630109874_2=error)) -> (cf'=stop_system);	// <-- 
	[compare0] (cf=compare0) & (redundancy_model38_cfblk1_0=v) & (y_cfblk1_2630109874=ok) & (y_cfblk1_2630109874_2=ok) -> (cf'=cfblk4_Output_2);	// <-- 
	[compare0] (cf=compare0) & (redundancy_model38_cfblk1_0=v) & ((y_cfblk1_2630109874=error) | (y_cfblk1_2630109874_2=error)) -> (cf'=cfblk1_Output_1_3);	// <-- 
	//Element stop_system, cf transitions ['cfblk1_Output_1']
	[stop_system] cf=stop_system -> 1.0:(cf'=cfblk1_Output_1);
	//Element check_redandancy1, df inputs ['redundancy_model38_cfblk4_1'], cf transitions ['cfblk4_Output_2_2', 'cfblk5_Output_3']
	[check_redandancy1] (cf=check_redandancy1) & (redundancy_model38_cfblk4_1=no) -> (cf'=cfblk5_Output_3);	// <-- 
	[check_redandancy1] (cf=check_redandancy1) & ((redundancy_model38_cfblk4_1=v)|(redundancy_model38_cfblk4_1=c)) -> (cf'=cfblk4_Output_2_2);	// <-- 
	//Element cfblk4_Output_2_2, cf transitions ['compare1']
	[cfblk4_Output_2_2] cf=cfblk4_Output_2_2 -> 1.0:(cf'=compare1);
	//Element cfblk4_Output_2_3, cf transitions ['cfblk5_Output_3']
	[cfblk4_Output_2_3] cf=cfblk4_Output_2_3 -> 1.0:(cf'=cfblk5_Output_3);
	//Element compare1, df inputs ['redundancy_model38_cfblk4_1', 'y_cfblk4_2747516053_2', 'y_cfblk4_2747516053'], cf transitions ['cfblk4_Output_2_3', 'cfblk5_Output_3', 'stop_system']
	[compare1] (cf=compare1) & (redundancy_model38_cfblk4_1=c) & (y_cfblk4_2747516053=ok) & (y_cfblk4_2747516053_2=ok) -> (cf'=cfblk5_Output_3);	// <-- 
	[compare1] (cf=compare1) & (redundancy_model38_cfblk4_1=c) & ((y_cfblk4_2747516053=error) | (y_cfblk4_2747516053_2=error)) -> (cf'=stop_system);	// <-- 
	[compare1] (cf=compare1) & (redundancy_model38_cfblk4_1=v) & (y_cfblk4_2747516053=ok) & (y_cfblk4_2747516053_2=ok) -> (cf'=cfblk5_Output_3);	// <-- 
	[compare1] (cf=compare1) & (redundancy_model38_cfblk4_1=v) & ((y_cfblk4_2747516053=error) | (y_cfblk4_2747516053_2=error)) -> (cf'=cfblk4_Output_2_3);	// <-- 
	//Element check_redandancy2, df inputs ['redundancy_model38_cfblk3_2'], cf transitions ['cfblk3_Output_4_2', 'cfblk2_Output_5']
	[check_redandancy2] (cf=check_redandancy2) & (redundancy_model38_cfblk3_2=no) -> (cf'=cfblk2_Output_5);	// <-- 
	[check_redandancy2] (cf=check_redandancy2) & ((redundancy_model38_cfblk3_2=v)|(redundancy_model38_cfblk3_2=c)) -> (cf'=cfblk3_Output_4_2);	// <-- 
	//Element cfblk3_Output_4_2, cf transitions ['compare2']
	[cfblk3_Output_4_2] cf=cfblk3_Output_4_2 -> 1.0:(cf'=compare2);
	//Element cfblk3_Output_4_3, cf transitions ['cfblk2_Output_5']
	[cfblk3_Output_4_3] cf=cfblk3_Output_4_3 -> 1.0:(cf'=cfblk2_Output_5);
	//Element compare2, df inputs ['redundancy_model38_cfblk3_2', 'y_cfblk3_2708380660_2', 'y_cfblk3_2708380660'], cf transitions ['cfblk3_Output_4_3', 'cfblk2_Output_5', 'stop_system']
	[compare2] (cf=compare2) & (redundancy_model38_cfblk3_2=c) & (y_cfblk3_2708380660=ok) & (y_cfblk3_2708380660_2=ok) -> (cf'=cfblk2_Output_5);	// <-- 
	[compare2] (cf=compare2) & (redundancy_model38_cfblk3_2=c) & ((y_cfblk3_2708380660=error) | (y_cfblk3_2708380660_2=error)) -> (cf'=stop_system);	// <-- 
	[compare2] (cf=compare2) & (redundancy_model38_cfblk3_2=v) & (y_cfblk3_2708380660=ok) & (y_cfblk3_2708380660_2=ok) -> (cf'=cfblk2_Output_5);	// <-- 
	[compare2] (cf=compare2) & (redundancy_model38_cfblk3_2=v) & ((y_cfblk3_2708380660=error) | (y_cfblk3_2708380660_2=error)) -> (cf'=cfblk3_Output_4_3);	// <-- 
	//Element check_redandancy4, df inputs ['redundancy_model38_cfblk1_0'], cf transitions ['cfblk1_Update_6_2', 'cfblk1_Output_1']
	[check_redandancy4] (cf=check_redandancy4) & (redundancy_model38_cfblk1_0=no) -> (cf'=cfblk1_Output_1);	// <-- 
	[check_redandancy4] (cf=check_redandancy4) & ((redundancy_model38_cfblk1_0=v)|(redundancy_model38_cfblk1_0=c)) -> (cf'=cfblk1_Update_6_2);	// <-- 
	//Element cfblk1_Update_6_2, df inputs ['y_cfblk5_2786651446', 'x_cfblk1_1_2417258935'], cf transitions ['compare4']
	[cfblk1_Update_6_2] cf=cfblk1_Update_6_2 -> 1.0:(cf'=compare4);
	//Element cfblk1_Update_6_3, df inputs ['y_cfblk5_2786651446', 'x_cfblk1_1_2417258935'], cf transitions ['cfblk1_Output_1']
	[cfblk1_Update_6_3] cf=cfblk1_Update_6_3 -> 1.0:(cf'=cfblk1_Output_1);
	//Element compare4, df inputs ['redundancy_model38_cfblk1_0', 'x_cfblk1_1_2417258935_2', 'x_cfblk1_1_2417258935'], cf transitions ['cfblk1_Update_6_3', 'cfblk1_Output_1', 'stop_system']
	[compare4] (cf=compare4) & (redundancy_model38_cfblk1_0=c) & (x_cfblk1_1_2417258935=ok) & (x_cfblk1_1_2417258935_2=ok) -> (cf'=cfblk1_Output_1);	// <-- 
	[compare4] (cf=compare4) & (redundancy_model38_cfblk1_0=c) & ((x_cfblk1_1_2417258935=error) | (x_cfblk1_1_2417258935_2=error)) -> (cf'=stop_system);	// <-- 
	[compare4] (cf=compare4) & (redundancy_model38_cfblk1_0=v) & (x_cfblk1_1_2417258935=ok) & (x_cfblk1_1_2417258935_2=ok) -> (cf'=cfblk1_Output_1);	// <-- 
	[compare4] (cf=compare4) & (redundancy_model38_cfblk1_0=v) & ((x_cfblk1_1_2417258935=error) | (x_cfblk1_1_2417258935_2=error)) -> (cf'=cfblk1_Update_6_3);	// <-- 
endmodule
//Error propagation commands
module error_propagation
	y_cfblk1_2630109874 : [0 .. 4] init ok;
	y_cfblk3_2708380660 : [0 .. 4] init ok;
	y_cfblk4_2747516053 : [0 .. 4] init ok;
	y_cfblk5_2786651446 : [0 .. 4] init ok;
	x_cfblk1_1_2417258935 : [0 .. 4] init ok;
	redundancy_model38_cfblk1_0 : [0 .. 4] init no;
	y_cfblk1_2630109874_2 : [0 .. 4] init ok;
	redundancy_model38_cfblk4_1 : [0 .. 4] init v;
	y_cfblk4_2747516053_2 : [0 .. 4] init ok;
	redundancy_model38_cfblk3_2 : [0 .. 4] init c;
	y_cfblk3_2708380660_2 : [0 .. 4] init ok;
	x_cfblk1_1_2417258935_2 : [0 .. 4] init ok;
	//Element cfblk1_Output_1, df inputs ['y_cfblk5_2786651446', 'x_cfblk1_1_2417258935'], df outputs ['y_cfblk1_2630109874']
	[cfblk1_Output_1] (y_cfblk5_2786651446=ok) & (x_cfblk1_1_2417258935=ok) -> 0.98:(y_cfblk1_2630109874'=ok) + 0.02:(y_cfblk1_2630109874'=error);	// <-- 
	[cfblk1_Output_1] (y_cfblk5_2786651446!=ok) | (x_cfblk1_1_2417258935!=ok) -> (y_cfblk1_2630109874'=error);	// <-- 
	//Element cfblk4_Output_2, df outputs ['y_cfblk4_2747516053']
	[cfblk4_Output_2] (true) -> 1:(y_cfblk4_2747516053'=ok);	// <-- 
	//Element cfblk5_Output_3, df inputs ['y_cfblk1_2630109874', 'y_cfblk4_2747516053'], df outputs ['y_cfblk5_2786651446']
	[cfblk5_Output_3] (y_cfblk1_2630109874=ok) & (y_cfblk4_2747516053=ok) -> 0.974002239936:(y_cfblk5_2786651446'=ok) + 0.025997760064:(y_cfblk5_2786651446'=error);	// <-- 
	[cfblk5_Output_3] (y_cfblk1_2630109874!=ok) | (y_cfblk4_2747516053!=ok) -> (y_cfblk5_2786651446'=error);	// <-- 
	//Element cfblk3_Output_4, df outputs ['y_cfblk3_2708380660']
	[cfblk3_Output_4] (true) -> 1:(y_cfblk3_2708380660'=ok);	// <-- 
	//Element cfblk1_Update_6, df inputs ['y_cfblk5_2786651446', 'x_cfblk1_1_2417258935'], df outputs ['x_cfblk1_1_2417258935']
	[cfblk1_Update_6] (y_cfblk5_2786651446=ok) & (x_cfblk1_1_2417258935=ok) -> 0.98:(x_cfblk1_1_2417258935'=ok) + 0.02:(x_cfblk1_1_2417258935'=error);	// <-- 
	[cfblk1_Update_6] (y_cfblk5_2786651446!=ok) | (x_cfblk1_1_2417258935!=ok) -> (x_cfblk1_1_2417258935'=error);	// <-- 
	//Element cfblk1_Output_1_2, df inputs ['y_cfblk5_2786651446', 'x_cfblk1_1_2417258935'], df outputs ['y_cfblk1_2630109874_2']
	[cfblk1_Output_1_2] (y_cfblk5_2786651446=ok) & (x_cfblk1_1_2417258935=ok) -> 0.98:(y_cfblk1_2630109874_2'=ok) + 0.02:(y_cfblk1_2630109874_2'=error);	// <-- 
	[cfblk1_Output_1_2] (y_cfblk5_2786651446!=ok) | (x_cfblk1_1_2417258935!=ok) -> (y_cfblk1_2630109874_2'=error);	// <-- 
	//Element cfblk1_Output_1_3, df inputs ['y_cfblk5_2786651446', 'x_cfblk1_1_2417258935'], df outputs ['y_cfblk1_2630109874']
	[cfblk1_Output_1_3] (y_cfblk5_2786651446=ok) & (x_cfblk1_1_2417258935=ok) -> 0.98:(y_cfblk1_2630109874'=ok) + 0.02:(y_cfblk1_2630109874'=error);	// <-- 
	[cfblk1_Output_1_3] (y_cfblk5_2786651446!=ok) | (x_cfblk1_1_2417258935!=ok) -> (y_cfblk1_2630109874'=error);	// <-- 
	//Element cfblk4_Output_2_2, df outputs ['y_cfblk4_2747516053_2']
	[cfblk4_Output_2_2] (true) -> 1:(y_cfblk4_2747516053_2'=ok);	// <-- 
	//Element cfblk4_Output_2_3, df outputs ['y_cfblk4_2747516053']
	[cfblk4_Output_2_3] (true) -> 1:(y_cfblk4_2747516053'=ok);	// <-- 
	//Element cfblk3_Output_4_2, df outputs ['y_cfblk3_2708380660_2']
	[cfblk3_Output_4_2] (true) -> 1:(y_cfblk3_2708380660_2'=ok);	// <-- 
	//Element cfblk3_Output_4_3, df outputs ['y_cfblk3_2708380660']
	[cfblk3_Output_4_3] (true) -> 1:(y_cfblk3_2708380660'=ok);	// <-- 
	//Element cfblk1_Update_6_2, df inputs ['y_cfblk5_2786651446', 'x_cfblk1_1_2417258935'], df outputs ['x_cfblk1_1_2417258935_2']
	[cfblk1_Update_6_2] (y_cfblk5_2786651446=ok) & (x_cfblk1_1_2417258935=ok) -> 0.98:(x_cfblk1_1_2417258935_2'=ok) + 0.02:(x_cfblk1_1_2417258935_2'=error);	// <-- 
	[cfblk1_Update_6_2] (y_cfblk5_2786651446!=ok) | (x_cfblk1_1_2417258935!=ok) -> (x_cfblk1_1_2417258935_2'=error);	// <-- 
	//Element cfblk1_Update_6_3, df inputs ['y_cfblk5_2786651446', 'x_cfblk1_1_2417258935'], df outputs ['x_cfblk1_1_2417258935']
	[cfblk1_Update_6_3] (y_cfblk5_2786651446=ok) & (x_cfblk1_1_2417258935=ok) -> 0.98:(x_cfblk1_1_2417258935'=ok) + 0.02:(x_cfblk1_1_2417258935'=error);	// <-- 
	[cfblk1_Update_6_3] (y_cfblk5_2786651446!=ok) | (x_cfblk1_1_2417258935!=ok) -> (x_cfblk1_1_2417258935'=error);	// <-- 
endmodule

//Failure formulas
formula failure = x_cfblk1_1_2417258935 = error;

rewards "time" true : 1; endrewards
