//Generated by ErrorPro
dtmc
//Element consts
const int cfblk4_Output_1=0;
const int cfblk5_Output_2=1;
const int cfblk2_Output_3=2;
const int cfblk3_Output_4=3;
const int cfblk1_Output_5=4;
const int cfblk4_Update_6=5;
const int cfblk5_Update_7=6;
const int check_redandancy0=7;
const int cfblk4_Output_1_2=8;
const int cfblk4_Output_1_3=9;
const int compare0=10;
const int stop_system=11;
const int check_redandancy1=12;
const int cfblk2_Output_3_2=13;
const int cfblk2_Output_3_3=14;
const int compare1=15;
const int check_redandancy2=16;
const int cfblk3_Output_4_2=17;
const int cfblk3_Output_4_3=18;
const int compare2=19;
const int check_redandancy3=20;
const int cfblk1_Output_5_2=21;
const int cfblk1_Output_5_3=22;
const int compare3=23;
const int check_redandancy4=24;
const int cfblk4_Update_6_2=25;
const int cfblk4_Update_6_3=26;
const int compare4=27;
//Data values consts
const int v=0;
const int prop_2=1;
const int prop_1=2;
const int ok=3;
const int no=4;
const int error=5;
const int c=6;
//Control flow commands
module control_flow
	cf:[0..28] init cfblk4_Output_1;
	//Element cfblk4_Output_1, df inputs ['y_cfblk1_2551018354', 'x_cfblk4_1_3681642682'], cf transitions ['check_redandancy0']
	[cfblk4_Output_1] cf=cfblk4_Output_1 -> 1.0:(cf'=check_redandancy0);
	//Element cfblk5_Output_2, df inputs ['y_cfblk3_2629289140', 'x_cfblk5_1_678143356'], cf transitions ['cfblk2_Output_3']
	[cfblk5_Output_2] cf=cfblk5_Output_2 -> 1.0:(cf'=cfblk2_Output_3);
	//Element cfblk2_Output_3, df inputs ['y_cfblk3_2629289140_2_y_cfblk5_2707559926', 'x_cfblk4_1_3681642682_2_y_cfblk4_2668424533'], cf transitions ['check_redandancy1']
	[cfblk2_Output_3] cf=cfblk2_Output_3 -> 1.0:(cf'=check_redandancy1);
	//Element cfblk3_Output_4, df inputs ['x_cfblk4_1_3681642682_2_y_cfblk4_2668424533', 'y_cfblk1_2551018354_2_y_cfblk4_2668424533_2_y_cfblk2_2590153747'], cf transitions ['check_redandancy2']
	[cfblk3_Output_4] cf=cfblk3_Output_4 -> 1.0:(cf'=check_redandancy2);
	//Element cfblk1_Output_5, df inputs ['y_cfblk3_2629289140', 'x_cfblk4_1_3681642682_2_y_cfblk4_2668424533'], cf transitions ['check_redandancy3']
	[cfblk1_Output_5] cf=cfblk1_Output_5 -> 1.0:(cf'=check_redandancy3);
	//Element cfblk4_Update_6, df inputs ['y_cfblk1_2551018354', 'x_cfblk4_1_3681642682'], cf transitions ['check_redandancy4']
	[cfblk4_Update_6] cf=cfblk4_Update_6 -> 1.0:(cf'=check_redandancy4);
	//Element cfblk5_Update_7, df inputs ['y_cfblk3_2629289140', 'x_cfblk5_1_678143356'], cf transitions ['cfblk4_Output_1']
	[cfblk5_Update_7] cf=cfblk5_Update_7 -> 1.0:(cf'=cfblk4_Output_1);
	//Element check_redandancy0, df inputs ['redundancy_model21_cfblk4_0'], cf transitions ['cfblk4_Output_1_2', 'cfblk5_Output_2']
	[check_redandancy0] (cf=check_redandancy0) & (redundancy_model21_cfblk4_0=no) -> (cf'=cfblk5_Output_2);	// <-- 
	[check_redandancy0] (cf=check_redandancy0) & ((redundancy_model21_cfblk4_0=v)|(redundancy_model21_cfblk4_0=c)) -> (cf'=cfblk4_Output_1_2);	// <-- 
	//Element cfblk4_Output_1_2, df inputs ['y_cfblk1_2551018354', 'x_cfblk4_1_3681642682'], cf transitions ['compare0']
	[cfblk4_Output_1_2] cf=cfblk4_Output_1_2 -> 1.0:(cf'=compare0);
	//Element cfblk4_Output_1_3, df inputs ['y_cfblk1_2551018354', 'x_cfblk4_1_3681642682'], cf transitions ['cfblk5_Output_2']
	[cfblk4_Output_1_3] cf=cfblk4_Output_1_3 -> 1.0:(cf'=cfblk5_Output_2);
	//Element compare0, df inputs ['redundancy_model21_cfblk4_0', 'x_cfblk4_1_3681642682_2_y_cfblk4_2668424533', 'y_cfblk1_2551018354_2_y_cfblk4_2668424533_2_y_cfblk2_2590153747'], cf transitions ['cfblk4_Output_1_3', 'cfblk5_Output_2', 'stop_system']
	[compare0] (cf=compare0) & (redundancy_model21_cfblk4_0=c) & (x_cfblk4_1_3681642682_2_y_cfblk4_2668424533=prop_1) & (y_cfblk1_2551018354_2_y_cfblk4_2668424533_2_y_cfblk2_2590153747=prop_1) -> (cf'=cfblk5_Output_2);	// <-- 
	[compare0] (cf=compare0) & (redundancy_model21_cfblk4_0=c) & ((x_cfblk4_1_3681642682_2_y_cfblk4_2668424533=prop_2) | (y_cfblk1_2551018354_2_y_cfblk4_2668424533_2_y_cfblk2_2590153747=prop_2)) -> (cf'=stop_system);	// <-- 
	[compare0] (cf=compare0) & (redundancy_model21_cfblk4_0=v) & (x_cfblk4_1_3681642682_2_y_cfblk4_2668424533=prop_1) & (y_cfblk1_2551018354_2_y_cfblk4_2668424533_2_y_cfblk2_2590153747=prop_1) -> (cf'=cfblk5_Output_2);	// <-- 
	[compare0] (cf=compare0) & (redundancy_model21_cfblk4_0=v) & ((x_cfblk4_1_3681642682_2_y_cfblk4_2668424533=prop_2) | (y_cfblk1_2551018354_2_y_cfblk4_2668424533_2_y_cfblk2_2590153747=prop_2)) -> (cf'=cfblk4_Output_1_3);	// <-- 
	//Element stop_system, cf transitions ['cfblk4_Output_1']
	[stop_system] cf=stop_system -> 1.0:(cf'=cfblk4_Output_1);
	//Element check_redandancy1, df inputs ['redundancy_model21_cfblk2_1'], cf transitions ['cfblk2_Output_3_2', 'cfblk3_Output_4']
	[check_redandancy1] (cf=check_redandancy1) & (redundancy_model21_cfblk2_1=no) -> (cf'=cfblk3_Output_4);	// <-- 
	[check_redandancy1] (cf=check_redandancy1) & ((redundancy_model21_cfblk2_1=v)|(redundancy_model21_cfblk2_1=c)) -> (cf'=cfblk2_Output_3_2);	// <-- 
	//Element cfblk2_Output_3_2, df inputs ['y_cfblk3_2629289140_2_y_cfblk5_2707559926', 'x_cfblk4_1_3681642682_2_y_cfblk4_2668424533'], cf transitions ['compare1']
	[cfblk2_Output_3_2] cf=cfblk2_Output_3_2 -> 1.0:(cf'=compare1);
	//Element cfblk2_Output_3_3, df inputs ['y_cfblk3_2629289140_2_y_cfblk5_2707559926', 'x_cfblk4_1_3681642682_2_y_cfblk4_2668424533'], cf transitions ['cfblk3_Output_4']
	[cfblk2_Output_3_3] cf=cfblk2_Output_3_3 -> 1.0:(cf'=cfblk3_Output_4);
	//Element compare1, df inputs ['redundancy_model21_cfblk2_1', 'y_cfblk2_2590153747_2', 'y_cfblk1_2551018354_2_y_cfblk4_2668424533_2_y_cfblk2_2590153747'], cf transitions ['cfblk2_Output_3_3', 'cfblk3_Output_4', 'stop_system']
	[compare1] (cf=compare1) & (redundancy_model21_cfblk2_1=c) & (y_cfblk1_2551018354_2_y_cfblk4_2668424533_2_y_cfblk2_2590153747=prop_1) & (y_cfblk2_2590153747_2=ok) -> (cf'=cfblk3_Output_4);	// <-- 
	[compare1] (cf=compare1) & (redundancy_model21_cfblk2_1=c) & ((y_cfblk1_2551018354_2_y_cfblk4_2668424533_2_y_cfblk2_2590153747=prop_2) | (y_cfblk2_2590153747_2=error)) -> (cf'=stop_system);	// <-- 
	[compare1] (cf=compare1) & (redundancy_model21_cfblk2_1=v) & (y_cfblk1_2551018354_2_y_cfblk4_2668424533_2_y_cfblk2_2590153747=prop_1) & (y_cfblk2_2590153747_2=ok) -> (cf'=cfblk3_Output_4);	// <-- 
	[compare1] (cf=compare1) & (redundancy_model21_cfblk2_1=v) & ((y_cfblk1_2551018354_2_y_cfblk4_2668424533_2_y_cfblk2_2590153747=prop_2) | (y_cfblk2_2590153747_2=error)) -> (cf'=cfblk2_Output_3_3);	// <-- 
	//Element check_redandancy2, df inputs ['redundancy_model21_cfblk3_2'], cf transitions ['cfblk3_Output_4_2', 'cfblk1_Output_5']
	[check_redandancy2] (cf=check_redandancy2) & (redundancy_model21_cfblk3_2=no) -> (cf'=cfblk1_Output_5);	// <-- 
	[check_redandancy2] (cf=check_redandancy2) & ((redundancy_model21_cfblk3_2=v)|(redundancy_model21_cfblk3_2=c)) -> (cf'=cfblk3_Output_4_2);	// <-- 
	//Element cfblk3_Output_4_2, df inputs ['x_cfblk4_1_3681642682_2_y_cfblk4_2668424533', 'y_cfblk1_2551018354_2_y_cfblk4_2668424533_2_y_cfblk2_2590153747'], cf transitions ['compare2']
	[cfblk3_Output_4_2] cf=cfblk3_Output_4_2 -> 1.0:(cf'=compare2);
	//Element cfblk3_Output_4_3, df inputs ['x_cfblk4_1_3681642682_2_y_cfblk4_2668424533', 'y_cfblk1_2551018354_2_y_cfblk4_2668424533_2_y_cfblk2_2590153747'], cf transitions ['cfblk1_Output_5']
	[cfblk3_Output_4_3] cf=cfblk3_Output_4_3 -> 1.0:(cf'=cfblk1_Output_5);
	//Element compare2, df inputs ['y_cfblk3_2629289140', 'y_cfblk3_2629289140_2_y_cfblk5_2707559926', 'redundancy_model21_cfblk3_2'], cf transitions ['cfblk3_Output_4_3', 'cfblk1_Output_5', 'stop_system']
	[compare2] (cf=compare2) & (redundancy_model21_cfblk3_2=c) & (y_cfblk3_2629289140=ok) & (y_cfblk3_2629289140_2_y_cfblk5_2707559926=prop_1) -> (cf'=cfblk1_Output_5);	// <-- 
	[compare2] (cf=compare2) & (redundancy_model21_cfblk3_2=c) & ((y_cfblk3_2629289140=error) | (y_cfblk3_2629289140_2_y_cfblk5_2707559926=prop_2)) -> (cf'=stop_system);	// <-- 
	[compare2] (cf=compare2) & (redundancy_model21_cfblk3_2=v) & (y_cfblk3_2629289140=ok) & (y_cfblk3_2629289140_2_y_cfblk5_2707559926=prop_1) -> (cf'=cfblk1_Output_5);	// <-- 
	[compare2] (cf=compare2) & (redundancy_model21_cfblk3_2=v) & ((y_cfblk3_2629289140=error) | (y_cfblk3_2629289140_2_y_cfblk5_2707559926=prop_2)) -> (cf'=cfblk3_Output_4_3);	// <-- 
	//Element check_redandancy3, df inputs ['redundancy_model21_cfblk1_3'], cf transitions ['cfblk1_Output_5_2', 'cfblk4_Update_6']
	[check_redandancy3] (cf=check_redandancy3) & (redundancy_model21_cfblk1_3=no) -> (cf'=cfblk4_Update_6);	// <-- 
	[check_redandancy3] (cf=check_redandancy3) & ((redundancy_model21_cfblk1_3=v)|(redundancy_model21_cfblk1_3=c)) -> (cf'=cfblk1_Output_5_2);	// <-- 
	//Element cfblk1_Output_5_2, df inputs ['y_cfblk3_2629289140', 'x_cfblk4_1_3681642682_2_y_cfblk4_2668424533'], cf transitions ['compare3']
	[cfblk1_Output_5_2] cf=cfblk1_Output_5_2 -> 1.0:(cf'=compare3);
	//Element cfblk1_Output_5_3, df inputs ['y_cfblk3_2629289140', 'x_cfblk4_1_3681642682_2_y_cfblk4_2668424533'], cf transitions ['cfblk4_Update_6']
	[cfblk1_Output_5_3] cf=cfblk1_Output_5_3 -> 1.0:(cf'=cfblk4_Update_6);
	//Element compare3, df inputs ['y_cfblk1_2551018354_2_y_cfblk4_2668424533_2_y_cfblk2_2590153747', 'y_cfblk1_2551018354', 'redundancy_model21_cfblk1_3'], cf transitions ['cfblk1_Output_5_3', 'cfblk4_Update_6', 'stop_system']
	[compare3] (cf=compare3) & (redundancy_model21_cfblk1_3=c) & (y_cfblk1_2551018354=ok) & (y_cfblk1_2551018354_2_y_cfblk4_2668424533_2_y_cfblk2_2590153747=prop_1) -> (cf'=cfblk4_Update_6);	// <-- 
	[compare3] (cf=compare3) & (redundancy_model21_cfblk1_3=c) & ((y_cfblk1_2551018354=error) | (y_cfblk1_2551018354_2_y_cfblk4_2668424533_2_y_cfblk2_2590153747=prop_2)) -> (cf'=stop_system);	// <-- 
	[compare3] (cf=compare3) & (redundancy_model21_cfblk1_3=v) & (y_cfblk1_2551018354=ok) & (y_cfblk1_2551018354_2_y_cfblk4_2668424533_2_y_cfblk2_2590153747=prop_1) -> (cf'=cfblk4_Update_6);	// <-- 
	[compare3] (cf=compare3) & (redundancy_model21_cfblk1_3=v) & ((y_cfblk1_2551018354=error) | (y_cfblk1_2551018354_2_y_cfblk4_2668424533_2_y_cfblk2_2590153747=prop_2)) -> (cf'=cfblk1_Output_5_3);	// <-- 
	//Element check_redandancy4, df inputs ['redundancy_model21_cfblk4_0'], cf transitions ['cfblk4_Update_6_2', 'cfblk5_Update_7']
	[check_redandancy4] (cf=check_redandancy4) & (redundancy_model21_cfblk4_0=no) -> (cf'=cfblk5_Update_7);	// <-- 
	[check_redandancy4] (cf=check_redandancy4) & ((redundancy_model21_cfblk4_0=v)|(redundancy_model21_cfblk4_0=c)) -> (cf'=cfblk4_Update_6_2);	// <-- 
	//Element cfblk4_Update_6_2, df inputs ['y_cfblk1_2551018354', 'x_cfblk4_1_3681642682'], cf transitions ['compare4']
	[cfblk4_Update_6_2] cf=cfblk4_Update_6_2 -> 1.0:(cf'=compare4);
	//Element cfblk4_Update_6_3, df inputs ['y_cfblk1_2551018354', 'x_cfblk4_1_3681642682'], cf transitions ['cfblk5_Update_7']
	[cfblk4_Update_6_3] cf=cfblk4_Update_6_3 -> 1.0:(cf'=cfblk5_Update_7);
	//Element compare4, df inputs ['redundancy_model21_cfblk4_0', 'x_cfblk4_1_3681642682_2_y_cfblk4_2668424533', 'x_cfblk4_1_3681642682'], cf transitions ['cfblk4_Update_6_3', 'cfblk5_Update_7', 'stop_system']
	[compare4] (cf=compare4) & (redundancy_model21_cfblk4_0=c) & (x_cfblk4_1_3681642682=ok) & (x_cfblk4_1_3681642682_2_y_cfblk4_2668424533=prop_1) -> (cf'=cfblk5_Update_7);	// <-- 
	[compare4] (cf=compare4) & (redundancy_model21_cfblk4_0=c) & ((x_cfblk4_1_3681642682=error) | (x_cfblk4_1_3681642682_2_y_cfblk4_2668424533=prop_2)) -> (cf'=stop_system);	// <-- 
	[compare4] (cf=compare4) & (redundancy_model21_cfblk4_0=v) & (x_cfblk4_1_3681642682=ok) & (x_cfblk4_1_3681642682_2_y_cfblk4_2668424533=prop_1) -> (cf'=cfblk5_Update_7);	// <-- 
	[compare4] (cf=compare4) & (redundancy_model21_cfblk4_0=v) & ((x_cfblk4_1_3681642682=error) | (x_cfblk4_1_3681642682_2_y_cfblk4_2668424533=prop_2)) -> (cf'=cfblk4_Update_6_3);	// <-- 
endmodule
//Error propagation commands
module error_propagation
	y_cfblk1_2551018354 : [0 .. 6] init ok;
	y_cfblk3_2629289140 : [0 .. 6] init ok;
	x_cfblk4_1_3681642682 : [0 .. 6] init ok;
	x_cfblk5_1_678143356 : [0 .. 6] init ok;
	redundancy_model21_cfblk4_0 : [0 .. 6] init no;
	redundancy_model21_cfblk2_1 : [0 .. 6] init c;
	y_cfblk2_2590153747_2 : [0 .. 6] init ok;
	redundancy_model21_cfblk3_2 : [0 .. 6] init no;
	redundancy_model21_cfblk1_3 : [0 .. 6] init c;
	y_cfblk3_2629289140_2_y_cfblk5_2707559926 : [0 .. 6] init prop_1;
	y_cfblk1_2551018354_2_y_cfblk4_2668424533_2_y_cfblk2_2590153747 : [0 .. 6] init prop_1;
	x_cfblk4_1_3681642682_2_y_cfblk4_2668424533 : [0 .. 6] init prop_1;
	//Element cfblk4_Output_1, df inputs ['y_cfblk1_2551018354', 'x_cfblk4_1_3681642682'], df outputs ['x_cfblk4_1_3681642682_2_y_cfblk4_2668424533']
	[cfblk4_Output_1] (y_cfblk1_2551018354=ok) & (x_cfblk4_1_3681642682=ok) -> 0.98:(x_cfblk4_1_3681642682_2_y_cfblk4_2668424533'=prop_1) + 0.02:(x_cfblk4_1_3681642682_2_y_cfblk4_2668424533'=prop_2);	// <-- 
	[cfblk4_Output_1] (y_cfblk1_2551018354!=ok) | (x_cfblk4_1_3681642682!=ok) -> (x_cfblk4_1_3681642682_2_y_cfblk4_2668424533'=prop_2);	// <-- 
	//Element cfblk5_Output_2, df inputs ['y_cfblk3_2629289140', 'x_cfblk5_1_678143356'], df outputs ['y_cfblk3_2629289140_2_y_cfblk5_2707559926']
	[cfblk5_Output_2] (y_cfblk3_2629289140=ok) & (x_cfblk5_1_678143356=ok) -> 0.98:(y_cfblk3_2629289140_2_y_cfblk5_2707559926'=prop_1) + 0.02:(y_cfblk3_2629289140_2_y_cfblk5_2707559926'=prop_2);	// <-- 
	[cfblk5_Output_2] (y_cfblk3_2629289140!=ok) | (x_cfblk5_1_678143356!=ok) -> (y_cfblk3_2629289140_2_y_cfblk5_2707559926'=prop_2);	// <-- 
	//Element cfblk2_Output_3, df inputs ['y_cfblk3_2629289140_2_y_cfblk5_2707559926', 'x_cfblk4_1_3681642682_2_y_cfblk4_2668424533'], df outputs ['y_cfblk1_2551018354_2_y_cfblk4_2668424533_2_y_cfblk2_2590153747']
	[cfblk2_Output_3] (x_cfblk4_1_3681642682_2_y_cfblk4_2668424533=prop_1) & (y_cfblk3_2629289140_2_y_cfblk5_2707559926=prop_1) -> 0.974002239936:(y_cfblk1_2551018354_2_y_cfblk4_2668424533_2_y_cfblk2_2590153747'=prop_1) + 0.025997760064:(y_cfblk1_2551018354_2_y_cfblk4_2668424533_2_y_cfblk2_2590153747'=prop_2);	// <-- 
	[cfblk2_Output_3] (x_cfblk4_1_3681642682_2_y_cfblk4_2668424533!=prop_1) | (y_cfblk3_2629289140_2_y_cfblk5_2707559926!=prop_1) -> (y_cfblk1_2551018354_2_y_cfblk4_2668424533_2_y_cfblk2_2590153747'=prop_2);	// <-- 
	//Element cfblk3_Output_4, df inputs ['x_cfblk4_1_3681642682_2_y_cfblk4_2668424533', 'y_cfblk1_2551018354_2_y_cfblk4_2668424533_2_y_cfblk2_2590153747'], df outputs ['y_cfblk3_2629289140']
	[cfblk3_Output_4] (y_cfblk1_2551018354_2_y_cfblk4_2668424533_2_y_cfblk2_2590153747=prop_1) & (x_cfblk4_1_3681642682_2_y_cfblk4_2668424533=prop_1) -> 0.974002239936:(y_cfblk3_2629289140'=ok) + 0.025997760064:(y_cfblk3_2629289140'=error);	// <-- 
	[cfblk3_Output_4] (y_cfblk1_2551018354_2_y_cfblk4_2668424533_2_y_cfblk2_2590153747!=prop_1) | (x_cfblk4_1_3681642682_2_y_cfblk4_2668424533!=prop_1) -> (y_cfblk3_2629289140'=error);	// <-- 
	//Element cfblk1_Output_5, df inputs ['y_cfblk3_2629289140', 'x_cfblk4_1_3681642682_2_y_cfblk4_2668424533'], df outputs ['y_cfblk1_2551018354']
	[cfblk1_Output_5] (y_cfblk3_2629289140=ok) & (x_cfblk4_1_3681642682_2_y_cfblk4_2668424533=prop_1) -> 0.974002239936:(y_cfblk1_2551018354'=ok) + 0.025997760064:(y_cfblk1_2551018354'=error);	// <-- 
	[cfblk1_Output_5] (y_cfblk3_2629289140!=ok) | (x_cfblk4_1_3681642682_2_y_cfblk4_2668424533!=prop_1) -> (y_cfblk1_2551018354'=error);	// <-- 
	//Element cfblk4_Update_6, df inputs ['y_cfblk1_2551018354', 'x_cfblk4_1_3681642682'], df outputs ['x_cfblk4_1_3681642682']
	[cfblk4_Update_6] (y_cfblk1_2551018354=ok) & (x_cfblk4_1_3681642682=ok) -> 0.98:(x_cfblk4_1_3681642682'=ok) + 0.02:(x_cfblk4_1_3681642682'=error);	// <-- 
	[cfblk4_Update_6] (y_cfblk1_2551018354!=ok) | (x_cfblk4_1_3681642682!=ok) -> (x_cfblk4_1_3681642682'=error);	// <-- 
	//Element cfblk5_Update_7, df inputs ['y_cfblk3_2629289140', 'x_cfblk5_1_678143356'], df outputs ['x_cfblk5_1_678143356']
	[cfblk5_Update_7] (y_cfblk3_2629289140=ok) & (x_cfblk5_1_678143356=ok) -> 0.98:(x_cfblk5_1_678143356'=ok) + 0.02:(x_cfblk5_1_678143356'=error);	// <-- 
	[cfblk5_Update_7] (y_cfblk3_2629289140!=ok) | (x_cfblk5_1_678143356!=ok) -> (x_cfblk5_1_678143356'=error);	// <-- 
	//Element cfblk4_Output_1_2, df inputs ['y_cfblk1_2551018354', 'x_cfblk4_1_3681642682'], df outputs ['y_cfblk1_2551018354_2_y_cfblk4_2668424533_2_y_cfblk2_2590153747']
	[cfblk4_Output_1_2] (y_cfblk1_2551018354=ok) & (x_cfblk4_1_3681642682=ok) -> 0.98:(y_cfblk1_2551018354_2_y_cfblk4_2668424533_2_y_cfblk2_2590153747'=prop_1) + 0.02:(y_cfblk1_2551018354_2_y_cfblk4_2668424533_2_y_cfblk2_2590153747'=prop_2);	// <-- 
	[cfblk4_Output_1_2] (y_cfblk1_2551018354!=ok) | (x_cfblk4_1_3681642682!=ok) -> (y_cfblk1_2551018354_2_y_cfblk4_2668424533_2_y_cfblk2_2590153747'=prop_2);	// <-- 
	//Element cfblk4_Output_1_3, df inputs ['y_cfblk1_2551018354', 'x_cfblk4_1_3681642682'], df outputs ['x_cfblk4_1_3681642682_2_y_cfblk4_2668424533']
	[cfblk4_Output_1_3] (y_cfblk1_2551018354=ok) & (x_cfblk4_1_3681642682=ok) -> 0.98:(x_cfblk4_1_3681642682_2_y_cfblk4_2668424533'=prop_1) + 0.02:(x_cfblk4_1_3681642682_2_y_cfblk4_2668424533'=prop_2);	// <-- 
	[cfblk4_Output_1_3] (y_cfblk1_2551018354!=ok) | (x_cfblk4_1_3681642682!=ok) -> (x_cfblk4_1_3681642682_2_y_cfblk4_2668424533'=prop_2);	// <-- 
	//Element cfblk2_Output_3_2, df inputs ['y_cfblk3_2629289140_2_y_cfblk5_2707559926', 'x_cfblk4_1_3681642682_2_y_cfblk4_2668424533'], df outputs ['y_cfblk2_2590153747_2']
	[cfblk2_Output_3_2] (x_cfblk4_1_3681642682_2_y_cfblk4_2668424533=prop_1) & (y_cfblk3_2629289140_2_y_cfblk5_2707559926=prop_1) -> 0.974002239936:(y_cfblk2_2590153747_2'=ok) + 0.025997760064:(y_cfblk2_2590153747_2'=error);	// <-- 
	[cfblk2_Output_3_2] (x_cfblk4_1_3681642682_2_y_cfblk4_2668424533!=prop_1) | (y_cfblk3_2629289140_2_y_cfblk5_2707559926!=prop_1) -> (y_cfblk2_2590153747_2'=error);	// <-- 
	//Element cfblk2_Output_3_3, df inputs ['y_cfblk3_2629289140_2_y_cfblk5_2707559926', 'x_cfblk4_1_3681642682_2_y_cfblk4_2668424533'], df outputs ['y_cfblk1_2551018354_2_y_cfblk4_2668424533_2_y_cfblk2_2590153747']
	[cfblk2_Output_3_3] (x_cfblk4_1_3681642682_2_y_cfblk4_2668424533=prop_1) & (y_cfblk3_2629289140_2_y_cfblk5_2707559926=prop_1) -> 0.974002239936:(y_cfblk1_2551018354_2_y_cfblk4_2668424533_2_y_cfblk2_2590153747'=prop_1) + 0.025997760064:(y_cfblk1_2551018354_2_y_cfblk4_2668424533_2_y_cfblk2_2590153747'=prop_2);	// <-- 
	[cfblk2_Output_3_3] (x_cfblk4_1_3681642682_2_y_cfblk4_2668424533!=prop_1) | (y_cfblk3_2629289140_2_y_cfblk5_2707559926!=prop_1) -> (y_cfblk1_2551018354_2_y_cfblk4_2668424533_2_y_cfblk2_2590153747'=prop_2);	// <-- 
	//Element cfblk3_Output_4_2, df inputs ['x_cfblk4_1_3681642682_2_y_cfblk4_2668424533', 'y_cfblk1_2551018354_2_y_cfblk4_2668424533_2_y_cfblk2_2590153747'], df outputs ['y_cfblk3_2629289140_2_y_cfblk5_2707559926']
	[cfblk3_Output_4_2] (y_cfblk1_2551018354_2_y_cfblk4_2668424533_2_y_cfblk2_2590153747=prop_1) & (x_cfblk4_1_3681642682_2_y_cfblk4_2668424533=prop_1) -> 0.974002239936:(y_cfblk3_2629289140_2_y_cfblk5_2707559926'=prop_1) + 0.025997760064:(y_cfblk3_2629289140_2_y_cfblk5_2707559926'=prop_2);	// <-- 
	[cfblk3_Output_4_2] (y_cfblk1_2551018354_2_y_cfblk4_2668424533_2_y_cfblk2_2590153747!=prop_1) | (x_cfblk4_1_3681642682_2_y_cfblk4_2668424533!=prop_1) -> (y_cfblk3_2629289140_2_y_cfblk5_2707559926'=prop_2);	// <-- 
	//Element cfblk3_Output_4_3, df inputs ['x_cfblk4_1_3681642682_2_y_cfblk4_2668424533', 'y_cfblk1_2551018354_2_y_cfblk4_2668424533_2_y_cfblk2_2590153747'], df outputs ['y_cfblk3_2629289140']
	[cfblk3_Output_4_3] (y_cfblk1_2551018354_2_y_cfblk4_2668424533_2_y_cfblk2_2590153747=prop_1) & (x_cfblk4_1_3681642682_2_y_cfblk4_2668424533=prop_1) -> 0.974002239936:(y_cfblk3_2629289140'=ok) + 0.025997760064:(y_cfblk3_2629289140'=error);	// <-- 
	[cfblk3_Output_4_3] (y_cfblk1_2551018354_2_y_cfblk4_2668424533_2_y_cfblk2_2590153747!=prop_1) | (x_cfblk4_1_3681642682_2_y_cfblk4_2668424533!=prop_1) -> (y_cfblk3_2629289140'=error);	// <-- 
	//Element cfblk1_Output_5_2, df inputs ['y_cfblk3_2629289140', 'x_cfblk4_1_3681642682_2_y_cfblk4_2668424533'], df outputs ['y_cfblk1_2551018354_2_y_cfblk4_2668424533_2_y_cfblk2_2590153747']
	[cfblk1_Output_5_2] (y_cfblk3_2629289140=ok) & (x_cfblk4_1_3681642682_2_y_cfblk4_2668424533=prop_1) -> 0.974002239936:(y_cfblk1_2551018354_2_y_cfblk4_2668424533_2_y_cfblk2_2590153747'=prop_1) + 0.025997760064:(y_cfblk1_2551018354_2_y_cfblk4_2668424533_2_y_cfblk2_2590153747'=prop_2);	// <-- 
	[cfblk1_Output_5_2] (y_cfblk3_2629289140!=ok) | (x_cfblk4_1_3681642682_2_y_cfblk4_2668424533!=prop_1) -> (y_cfblk1_2551018354_2_y_cfblk4_2668424533_2_y_cfblk2_2590153747'=prop_2);	// <-- 
	//Element cfblk1_Output_5_3, df inputs ['y_cfblk3_2629289140', 'x_cfblk4_1_3681642682_2_y_cfblk4_2668424533'], df outputs ['y_cfblk1_2551018354']
	[cfblk1_Output_5_3] (y_cfblk3_2629289140=ok) & (x_cfblk4_1_3681642682_2_y_cfblk4_2668424533=prop_1) -> 0.974002239936:(y_cfblk1_2551018354'=ok) + 0.025997760064:(y_cfblk1_2551018354'=error);	// <-- 
	[cfblk1_Output_5_3] (y_cfblk3_2629289140!=ok) | (x_cfblk4_1_3681642682_2_y_cfblk4_2668424533!=prop_1) -> (y_cfblk1_2551018354'=error);	// <-- 
	//Element cfblk4_Update_6_2, df inputs ['y_cfblk1_2551018354', 'x_cfblk4_1_3681642682'], df outputs ['x_cfblk4_1_3681642682_2_y_cfblk4_2668424533']
	[cfblk4_Update_6_2] (y_cfblk1_2551018354=ok) & (x_cfblk4_1_3681642682=ok) -> 0.98:(x_cfblk4_1_3681642682_2_y_cfblk4_2668424533'=prop_1) + 0.02:(x_cfblk4_1_3681642682_2_y_cfblk4_2668424533'=prop_2);	// <-- 
	[cfblk4_Update_6_2] (y_cfblk1_2551018354!=ok) | (x_cfblk4_1_3681642682!=ok) -> (x_cfblk4_1_3681642682_2_y_cfblk4_2668424533'=prop_2);	// <-- 
	//Element cfblk4_Update_6_3, df inputs ['y_cfblk1_2551018354', 'x_cfblk4_1_3681642682'], df outputs ['x_cfblk4_1_3681642682']
	[cfblk4_Update_6_3] (y_cfblk1_2551018354=ok) & (x_cfblk4_1_3681642682=ok) -> 0.98:(x_cfblk4_1_3681642682'=ok) + 0.02:(x_cfblk4_1_3681642682'=error);	// <-- 
	[cfblk4_Update_6_3] (y_cfblk1_2551018354!=ok) | (x_cfblk4_1_3681642682!=ok) -> (x_cfblk4_1_3681642682'=error);	// <-- 
endmodule

//Failure formulas
formula failure = x_cfblk5_1_678143356 = error;

rewards "time" true : 1; endrewards
