# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
    - '*'
    exclude:
    - artifacts


stages:
 - stage: distribute_generated_models
 
   jobs:
    - job: Cloud_Ubuntu
      # This job builds the prism binaries on an ubuntu cloud vm
      # and uploads the binaries back into the git repository.
      # This job is intended to run once to get prism binaries in the repository forever.
      strategy:
        matrix:
          ubuntu_20_04:
            imageName: 'ubuntu-20.04'
            the_name: 'Azure Pipelines'
      pool:
        vmImage: $(imageName)
        name: $(the_name)
      
      timeoutInMinutes: 60
      steps:
       - script: ./script/ci/distribute_models.sh "$(USER_NAME)" "$(PERSONAL_ACCESS_TOKEN)" "$BUILD_SOURCEBRANCH"
         displayName: "Run distribute_models.sh "
         condition: succeeded()
       - script: echo $BUILD_SOURCEBRANCH
         displayName: "cHECK BRANCH VIA AZURE VARIABLES"
         condition: succeeded()
       #- script: sudo apt-get install -y openjdk-8-jdk
       #  displayName: "Install custom Java version"
       #  condition: succeeded()
       