# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
    - '*'
    exclude:
    - artifacts


stages:
 - stage: run_prism
 
   jobs:
    - job: Prism_Cloud
    
      strategy:
        matrix:
          ubuntu_20_04:
            imageName: 'ubuntu-20.04'
            the_name: 'Azure Pipelines'
      pool:
        vmImage: $(imageName)
        name: $(the_name)
      
      timeoutInMinutes: 180

      steps:
       #real Tasks:
       - script: |
           cd artifacts/prism-sttt17/prism/bin/
           ls -la
           ./prism '../../../../RESULTS/prism_model/reduced_model.prism' -pf 'filter(printall, Pmax=? [ F<100 "deadlock" ], "init")' -mtbdd -cuddmaxmem 10g > log.txt
           cat log.txt
         displayName: 'Run PRISM on reduced_model'
         condition: succeeded()