//Generated by ErrorPro
dtmc
//Element consts
const int cfblk1_Output_1=0;
const int cfblk5_Output_2=1;
const int cfblk3_Output_3=2;
const int cfblk2_Output_4=3;
const int cfblk4_Output_5=4;
const int cfblk1_Update_6=5;
const int cfblk2_Update_7=6;
const int check_redandancy0=7;
const int cfblk1_Output_1_2=8;
const int cfblk1_Output_1_3=9;
const int compare0=10;
const int stop_system=11;
const int check_redandancy2=12;
const int cfblk2_Output_4_2=13;
const int cfblk2_Output_4_3=14;
const int compare2=15;
const int check_redandancy4=16;
const int cfblk1_Update_6_2=17;
const int cfblk1_Update_6_3=18;
const int compare4=19;
const int check_redandancy5=20;
const int cfblk2_Update_7_2=21;
const int cfblk2_Update_7_3=22;
const int compare5=23;
//Data values consts
const int v=0;
const int prop_2=1;
const int prop_1=2;
const int ok=3;
const int no=4;
const int error=5;
const int c=6;
//Control flow commands
module control_flow
	cf:[0..24] init cfblk1_Output_1;
	//Element cfblk1_Output_1, df inputs ['x_cfblk1_1_896681653', 'y_cfblk5_528014437'], cf transitions ['check_redandancy0']
	[cfblk1_Output_1] cf=cfblk1_Output_1 -> 1.0:(cf'=check_redandancy0);
	//Element cfblk5_Output_2, df inputs ['x_cfblk2_1_2188149622_2_x_cfblk1_1_896681653_2_y_cfblk2_410608258_y_cfblk1_371472865'], cf transitions ['cfblk3_Output_3']
	[cfblk5_Output_2] cf=cfblk5_Output_2 -> 1.0:(cf'=cfblk3_Output_3);
	//Element cfblk3_Output_3, df inputs ['y_cfblk5_528014437'], cf transitions ['cfblk2_Output_4']
	[cfblk3_Output_3] cf=cfblk3_Output_3 -> 1.0:(cf'=cfblk2_Output_4);
	//Element cfblk2_Output_4, df inputs ['x_cfblk2_1_2188149622', 'y_cfblk5_528014437'], cf transitions ['check_redandancy2']
	[cfblk2_Output_4] cf=cfblk2_Output_4 -> 1.0:(cf'=check_redandancy2);
	//Element cfblk4_Output_5, df inputs ['x_cfblk2_1_2188149622_2_x_cfblk1_1_896681653_2_y_cfblk2_410608258_y_cfblk1_371472865'], cf transitions ['cfblk1_Update_6']
	[cfblk4_Output_5] cf=cfblk4_Output_5 -> 1.0:(cf'=cfblk1_Update_6);
	//Element cfblk1_Update_6, df inputs ['x_cfblk1_1_896681653', 'y_cfblk5_528014437'], cf transitions ['check_redandancy4']
	[cfblk1_Update_6] cf=cfblk1_Update_6 -> 1.0:(cf'=check_redandancy4);
	//Element cfblk2_Update_7, df inputs ['x_cfblk2_1_2188149622', 'y_cfblk5_528014437'], cf transitions ['check_redandancy5']
	[cfblk2_Update_7] cf=cfblk2_Update_7 -> 1.0:(cf'=check_redandancy5);
	//Element check_redandancy0, df inputs ['redundancy_model84_cfblk1_0'], cf transitions ['cfblk1_Output_1_2', 'cfblk5_Output_2']
	[check_redandancy0] (cf=check_redandancy0) & (redundancy_model84_cfblk1_0=no) -> (cf'=cfblk5_Output_2);	// <-- 
	[check_redandancy0] (cf=check_redandancy0) & ((redundancy_model84_cfblk1_0=v)|(redundancy_model84_cfblk1_0=c)) -> (cf'=cfblk1_Output_1_2);	// <-- 
	//Element cfblk1_Output_1_2, df inputs ['x_cfblk1_1_896681653', 'y_cfblk5_528014437'], cf transitions ['compare0']
	[cfblk1_Output_1_2] cf=cfblk1_Output_1_2 -> 1.0:(cf'=compare0);
	//Element cfblk1_Output_1_3, df inputs ['x_cfblk1_1_896681653', 'y_cfblk5_528014437'], cf transitions ['cfblk5_Output_2']
	[cfblk1_Output_1_3] cf=cfblk1_Output_1_3 -> 1.0:(cf'=cfblk5_Output_2);
	//Element compare0, df inputs ['redundancy_model84_cfblk1_0', 'y_cfblk2_410608258_2_y_cfblk1_371472865_2', 'x_cfblk2_1_2188149622_2_x_cfblk1_1_896681653_2_y_cfblk2_410608258_y_cfblk1_371472865'], cf transitions ['cfblk1_Output_1_3', 'cfblk5_Output_2', 'stop_system']
	[compare0] (cf=compare0) & (redundancy_model84_cfblk1_0=c) & (x_cfblk2_1_2188149622_2_x_cfblk1_1_896681653_2_y_cfblk2_410608258_y_cfblk1_371472865=prop_1) & (y_cfblk2_410608258_2_y_cfblk1_371472865_2=prop_1) -> (cf'=cfblk5_Output_2);	// <-- 
	[compare0] (cf=compare0) & (redundancy_model84_cfblk1_0=c) & ((x_cfblk2_1_2188149622_2_x_cfblk1_1_896681653_2_y_cfblk2_410608258_y_cfblk1_371472865=prop_2) | (y_cfblk2_410608258_2_y_cfblk1_371472865_2=prop_2)) -> (cf'=stop_system);	// <-- 
	[compare0] (cf=compare0) & (redundancy_model84_cfblk1_0=v) & (x_cfblk2_1_2188149622_2_x_cfblk1_1_896681653_2_y_cfblk2_410608258_y_cfblk1_371472865=prop_1) & (y_cfblk2_410608258_2_y_cfblk1_371472865_2=prop_1) -> (cf'=cfblk5_Output_2);	// <-- 
	[compare0] (cf=compare0) & (redundancy_model84_cfblk1_0=v) & ((x_cfblk2_1_2188149622_2_x_cfblk1_1_896681653_2_y_cfblk2_410608258_y_cfblk1_371472865=prop_2) | (y_cfblk2_410608258_2_y_cfblk1_371472865_2=prop_2)) -> (cf'=cfblk1_Output_1_3);	// <-- 
	//Element stop_system, cf transitions ['cfblk1_Output_1']
	[stop_system] cf=stop_system -> 1.0:(cf'=cfblk1_Output_1);
	//Element check_redandancy2, df inputs ['redundancy_model84_cfblk2_2'], cf transitions ['cfblk2_Output_4_2', 'cfblk4_Output_5']
	[check_redandancy2] (cf=check_redandancy2) & (redundancy_model84_cfblk2_2=no) -> (cf'=cfblk4_Output_5);	// <-- 
	[check_redandancy2] (cf=check_redandancy2) & ((redundancy_model84_cfblk2_2=v)|(redundancy_model84_cfblk2_2=c)) -> (cf'=cfblk2_Output_4_2);	// <-- 
	//Element cfblk2_Output_4_2, df inputs ['x_cfblk2_1_2188149622', 'y_cfblk5_528014437'], cf transitions ['compare2']
	[cfblk2_Output_4_2] cf=cfblk2_Output_4_2 -> 1.0:(cf'=compare2);
	//Element cfblk2_Output_4_3, df inputs ['x_cfblk2_1_2188149622', 'y_cfblk5_528014437'], cf transitions ['cfblk4_Output_5']
	[cfblk2_Output_4_3] cf=cfblk2_Output_4_3 -> 1.0:(cf'=cfblk4_Output_5);
	//Element compare2, df inputs ['y_cfblk2_410608258_2_y_cfblk1_371472865_2', 'x_cfblk2_1_2188149622_2_x_cfblk1_1_896681653_2_y_cfblk2_410608258_y_cfblk1_371472865', 'redundancy_model84_cfblk2_2'], cf transitions ['cfblk2_Output_4_3', 'cfblk4_Output_5', 'stop_system']
	[compare2] (cf=compare2) & (redundancy_model84_cfblk2_2=c) & (x_cfblk2_1_2188149622_2_x_cfblk1_1_896681653_2_y_cfblk2_410608258_y_cfblk1_371472865=prop_1) & (y_cfblk2_410608258_2_y_cfblk1_371472865_2=prop_1) -> (cf'=cfblk4_Output_5);	// <-- 
	[compare2] (cf=compare2) & (redundancy_model84_cfblk2_2=c) & ((x_cfblk2_1_2188149622_2_x_cfblk1_1_896681653_2_y_cfblk2_410608258_y_cfblk1_371472865=prop_2) | (y_cfblk2_410608258_2_y_cfblk1_371472865_2=prop_2)) -> (cf'=stop_system);	// <-- 
	[compare2] (cf=compare2) & (redundancy_model84_cfblk2_2=v) & (x_cfblk2_1_2188149622_2_x_cfblk1_1_896681653_2_y_cfblk2_410608258_y_cfblk1_371472865=prop_1) & (y_cfblk2_410608258_2_y_cfblk1_371472865_2=prop_1) -> (cf'=cfblk4_Output_5);	// <-- 
	[compare2] (cf=compare2) & (redundancy_model84_cfblk2_2=v) & ((x_cfblk2_1_2188149622_2_x_cfblk1_1_896681653_2_y_cfblk2_410608258_y_cfblk1_371472865=prop_2) | (y_cfblk2_410608258_2_y_cfblk1_371472865_2=prop_2)) -> (cf'=cfblk2_Output_4_3);	// <-- 
	//Element check_redandancy4, df inputs ['redundancy_model84_cfblk1_0'], cf transitions ['cfblk1_Update_6_2', 'cfblk2_Update_7']
	[check_redandancy4] (cf=check_redandancy4) & (redundancy_model84_cfblk1_0=no) -> (cf'=cfblk2_Update_7);	// <-- 
	[check_redandancy4] (cf=check_redandancy4) & ((redundancy_model84_cfblk1_0=v)|(redundancy_model84_cfblk1_0=c)) -> (cf'=cfblk1_Update_6_2);	// <-- 
	//Element cfblk1_Update_6_2, df inputs ['x_cfblk1_1_896681653', 'y_cfblk5_528014437'], cf transitions ['compare4']
	[cfblk1_Update_6_2] cf=cfblk1_Update_6_2 -> 1.0:(cf'=compare4);
	//Element cfblk1_Update_6_3, df inputs ['x_cfblk1_1_896681653', 'y_cfblk5_528014437'], cf transitions ['cfblk2_Update_7']
	[cfblk1_Update_6_3] cf=cfblk1_Update_6_3 -> 1.0:(cf'=cfblk2_Update_7);
	//Element compare4, df inputs ['redundancy_model84_cfblk1_0', 'x_cfblk1_1_896681653', 'x_cfblk2_1_2188149622_2_x_cfblk1_1_896681653_2_y_cfblk2_410608258_y_cfblk1_371472865'], cf transitions ['cfblk1_Update_6_3', 'cfblk2_Update_7', 'stop_system']
	[compare4] (cf=compare4) & (redundancy_model84_cfblk1_0=c) & (x_cfblk1_1_896681653=ok) & (x_cfblk2_1_2188149622_2_x_cfblk1_1_896681653_2_y_cfblk2_410608258_y_cfblk1_371472865=prop_1) -> (cf'=cfblk2_Update_7);	// <-- 
	[compare4] (cf=compare4) & (redundancy_model84_cfblk1_0=c) & ((x_cfblk1_1_896681653=error) | (x_cfblk2_1_2188149622_2_x_cfblk1_1_896681653_2_y_cfblk2_410608258_y_cfblk1_371472865=prop_2)) -> (cf'=stop_system);	// <-- 
	[compare4] (cf=compare4) & (redundancy_model84_cfblk1_0=v) & (x_cfblk1_1_896681653=ok) & (x_cfblk2_1_2188149622_2_x_cfblk1_1_896681653_2_y_cfblk2_410608258_y_cfblk1_371472865=prop_1) -> (cf'=cfblk2_Update_7);	// <-- 
	[compare4] (cf=compare4) & (redundancy_model84_cfblk1_0=v) & ((x_cfblk1_1_896681653=error) | (x_cfblk2_1_2188149622_2_x_cfblk1_1_896681653_2_y_cfblk2_410608258_y_cfblk1_371472865=prop_2)) -> (cf'=cfblk1_Update_6_3);	// <-- 
	//Element check_redandancy5, df inputs ['redundancy_model84_cfblk2_2'], cf transitions ['cfblk2_Update_7_2', 'cfblk1_Output_1']
	[check_redandancy5] (cf=check_redandancy5) & (redundancy_model84_cfblk2_2=no) -> (cf'=cfblk1_Output_1);	// <-- 
	[check_redandancy5] (cf=check_redandancy5) & ((redundancy_model84_cfblk2_2=v)|(redundancy_model84_cfblk2_2=c)) -> (cf'=cfblk2_Update_7_2);	// <-- 
	//Element cfblk2_Update_7_2, df inputs ['x_cfblk2_1_2188149622', 'y_cfblk5_528014437'], cf transitions ['compare5']
	[cfblk2_Update_7_2] cf=cfblk2_Update_7_2 -> 1.0:(cf'=compare5);
	//Element cfblk2_Update_7_3, df inputs ['x_cfblk2_1_2188149622', 'y_cfblk5_528014437'], cf transitions ['cfblk1_Output_1']
	[cfblk2_Update_7_3] cf=cfblk2_Update_7_3 -> 1.0:(cf'=cfblk1_Output_1);
	//Element compare5, df inputs ['x_cfblk2_1_2188149622', 'x_cfblk2_1_2188149622_2_x_cfblk1_1_896681653_2_y_cfblk2_410608258_y_cfblk1_371472865', 'redundancy_model84_cfblk2_2'], cf transitions ['cfblk2_Update_7_3', 'cfblk1_Output_1', 'stop_system']
	[compare5] (cf=compare5) & (redundancy_model84_cfblk2_2=c) & (x_cfblk2_1_2188149622=ok) & (x_cfblk2_1_2188149622_2_x_cfblk1_1_896681653_2_y_cfblk2_410608258_y_cfblk1_371472865=prop_1) -> (cf'=cfblk1_Output_1);	// <-- 
	[compare5] (cf=compare5) & (redundancy_model84_cfblk2_2=c) & ((x_cfblk2_1_2188149622=error) | (x_cfblk2_1_2188149622_2_x_cfblk1_1_896681653_2_y_cfblk2_410608258_y_cfblk1_371472865=prop_2)) -> (cf'=stop_system);	// <-- 
	[compare5] (cf=compare5) & (redundancy_model84_cfblk2_2=v) & (x_cfblk2_1_2188149622=ok) & (x_cfblk2_1_2188149622_2_x_cfblk1_1_896681653_2_y_cfblk2_410608258_y_cfblk1_371472865=prop_1) -> (cf'=cfblk1_Output_1);	// <-- 
	[compare5] (cf=compare5) & (redundancy_model84_cfblk2_2=v) & ((x_cfblk2_1_2188149622=error) | (x_cfblk2_1_2188149622_2_x_cfblk1_1_896681653_2_y_cfblk2_410608258_y_cfblk1_371472865=prop_2)) -> (cf'=cfblk2_Update_7_3);	// <-- 
endmodule
//Error propagation commands
module error_propagation
	y_cfblk5_528014437 : [0 .. 6] init ok;
	x_cfblk1_1_896681653 : [0 .. 6] init ok;
	x_cfblk2_1_2188149622 : [0 .. 6] init ok;
	redundancy_model84_cfblk1_0 : [0 .. 6] init v;
	redundancy_model84_cfblk2_2 : [0 .. 6] init v;
	y_cfblk2_410608258_2_y_cfblk1_371472865_2 : [0 .. 6] init prop_1;
	x_cfblk2_1_2188149622_2_x_cfblk1_1_896681653_2_y_cfblk2_410608258_y_cfblk1_371472865 : [0 .. 6] init prop_1;
	//Element cfblk1_Output_1, df inputs ['x_cfblk1_1_896681653', 'y_cfblk5_528014437'], df outputs ['x_cfblk2_1_2188149622_2_x_cfblk1_1_896681653_2_y_cfblk2_410608258_y_cfblk1_371472865']
	[cfblk1_Output_1] (y_cfblk5_528014437=ok) & (x_cfblk1_1_896681653=ok) -> 0.98:(x_cfblk2_1_2188149622_2_x_cfblk1_1_896681653_2_y_cfblk2_410608258_y_cfblk1_371472865'=prop_1) + 0.02:(x_cfblk2_1_2188149622_2_x_cfblk1_1_896681653_2_y_cfblk2_410608258_y_cfblk1_371472865'=prop_2);	// <-- 
	[cfblk1_Output_1] (y_cfblk5_528014437!=ok) | (x_cfblk1_1_896681653!=ok) -> (x_cfblk2_1_2188149622_2_x_cfblk1_1_896681653_2_y_cfblk2_410608258_y_cfblk1_371472865'=prop_2);	// <-- 
	//Element cfblk5_Output_2, df inputs ['x_cfblk2_1_2188149622_2_x_cfblk1_1_896681653_2_y_cfblk2_410608258_y_cfblk1_371472865'], df outputs ['y_cfblk5_528014437']
	[cfblk5_Output_2] (x_cfblk2_1_2188149622_2_x_cfblk1_1_896681653_2_y_cfblk2_410608258_y_cfblk1_371472865=prop_1) -> 0.974002239936:(y_cfblk5_528014437'=ok) + 0.025997760064:(y_cfblk5_528014437'=error);	// <-- 
	[cfblk5_Output_2] (x_cfblk2_1_2188149622_2_x_cfblk1_1_896681653_2_y_cfblk2_410608258_y_cfblk1_371472865!=prop_1) -> (y_cfblk5_528014437'=error);	// <-- 
	//Element cfblk2_Output_4, df inputs ['x_cfblk2_1_2188149622', 'y_cfblk5_528014437'], df outputs ['x_cfblk2_1_2188149622_2_x_cfblk1_1_896681653_2_y_cfblk2_410608258_y_cfblk1_371472865']
	[cfblk2_Output_4] (y_cfblk5_528014437=ok) & (x_cfblk2_1_2188149622=ok) -> 0.98:(x_cfblk2_1_2188149622_2_x_cfblk1_1_896681653_2_y_cfblk2_410608258_y_cfblk1_371472865'=prop_1) + 0.02:(x_cfblk2_1_2188149622_2_x_cfblk1_1_896681653_2_y_cfblk2_410608258_y_cfblk1_371472865'=prop_2);	// <-- 
	[cfblk2_Output_4] (y_cfblk5_528014437!=ok) | (x_cfblk2_1_2188149622!=ok) -> (x_cfblk2_1_2188149622_2_x_cfblk1_1_896681653_2_y_cfblk2_410608258_y_cfblk1_371472865'=prop_2);	// <-- 
	//Element cfblk1_Update_6, df inputs ['x_cfblk1_1_896681653', 'y_cfblk5_528014437'], df outputs ['x_cfblk1_1_896681653']
	[cfblk1_Update_6] (y_cfblk5_528014437=ok) & (x_cfblk1_1_896681653=ok) -> 0.98:(x_cfblk1_1_896681653'=ok) + 0.02:(x_cfblk1_1_896681653'=error);	// <-- 
	[cfblk1_Update_6] (y_cfblk5_528014437!=ok) | (x_cfblk1_1_896681653!=ok) -> (x_cfblk1_1_896681653'=error);	// <-- 
	//Element cfblk2_Update_7, df inputs ['x_cfblk2_1_2188149622', 'y_cfblk5_528014437'], df outputs ['x_cfblk2_1_2188149622']
	[cfblk2_Update_7] (y_cfblk5_528014437=ok) & (x_cfblk2_1_2188149622=ok) -> 0.98:(x_cfblk2_1_2188149622'=ok) + 0.02:(x_cfblk2_1_2188149622'=error);	// <-- 
	[cfblk2_Update_7] (y_cfblk5_528014437!=ok) | (x_cfblk2_1_2188149622!=ok) -> (x_cfblk2_1_2188149622'=error);	// <-- 
	//Element cfblk1_Output_1_2, df inputs ['x_cfblk1_1_896681653', 'y_cfblk5_528014437'], df outputs ['y_cfblk2_410608258_2_y_cfblk1_371472865_2']
	[cfblk1_Output_1_2] (y_cfblk5_528014437=ok) & (x_cfblk1_1_896681653=ok) -> 0.98:(y_cfblk2_410608258_2_y_cfblk1_371472865_2'=prop_1) + 0.02:(y_cfblk2_410608258_2_y_cfblk1_371472865_2'=prop_2);	// <-- 
	[cfblk1_Output_1_2] (y_cfblk5_528014437!=ok) | (x_cfblk1_1_896681653!=ok) -> (y_cfblk2_410608258_2_y_cfblk1_371472865_2'=prop_2);	// <-- 
	//Element cfblk1_Output_1_3, df inputs ['x_cfblk1_1_896681653', 'y_cfblk5_528014437'], df outputs ['x_cfblk2_1_2188149622_2_x_cfblk1_1_896681653_2_y_cfblk2_410608258_y_cfblk1_371472865']
	[cfblk1_Output_1_3] (y_cfblk5_528014437=ok) & (x_cfblk1_1_896681653=ok) -> 0.98:(x_cfblk2_1_2188149622_2_x_cfblk1_1_896681653_2_y_cfblk2_410608258_y_cfblk1_371472865'=prop_1) + 0.02:(x_cfblk2_1_2188149622_2_x_cfblk1_1_896681653_2_y_cfblk2_410608258_y_cfblk1_371472865'=prop_2);	// <-- 
	[cfblk1_Output_1_3] (y_cfblk5_528014437!=ok) | (x_cfblk1_1_896681653!=ok) -> (x_cfblk2_1_2188149622_2_x_cfblk1_1_896681653_2_y_cfblk2_410608258_y_cfblk1_371472865'=prop_2);	// <-- 
	//Element cfblk2_Output_4_2, df inputs ['x_cfblk2_1_2188149622', 'y_cfblk5_528014437'], df outputs ['y_cfblk2_410608258_2_y_cfblk1_371472865_2']
	[cfblk2_Output_4_2] (y_cfblk5_528014437=ok) & (x_cfblk2_1_2188149622=ok) -> 0.98:(y_cfblk2_410608258_2_y_cfblk1_371472865_2'=prop_1) + 0.02:(y_cfblk2_410608258_2_y_cfblk1_371472865_2'=prop_2);	// <-- 
	[cfblk2_Output_4_2] (y_cfblk5_528014437!=ok) | (x_cfblk2_1_2188149622!=ok) -> (y_cfblk2_410608258_2_y_cfblk1_371472865_2'=prop_2);	// <-- 
	//Element cfblk2_Output_4_3, df inputs ['x_cfblk2_1_2188149622', 'y_cfblk5_528014437'], df outputs ['x_cfblk2_1_2188149622_2_x_cfblk1_1_896681653_2_y_cfblk2_410608258_y_cfblk1_371472865']
	[cfblk2_Output_4_3] (y_cfblk5_528014437=ok) & (x_cfblk2_1_2188149622=ok) -> 0.98:(x_cfblk2_1_2188149622_2_x_cfblk1_1_896681653_2_y_cfblk2_410608258_y_cfblk1_371472865'=prop_1) + 0.02:(x_cfblk2_1_2188149622_2_x_cfblk1_1_896681653_2_y_cfblk2_410608258_y_cfblk1_371472865'=prop_2);	// <-- 
	[cfblk2_Output_4_3] (y_cfblk5_528014437!=ok) | (x_cfblk2_1_2188149622!=ok) -> (x_cfblk2_1_2188149622_2_x_cfblk1_1_896681653_2_y_cfblk2_410608258_y_cfblk1_371472865'=prop_2);	// <-- 
	//Element cfblk1_Update_6_2, df inputs ['x_cfblk1_1_896681653', 'y_cfblk5_528014437'], df outputs ['x_cfblk2_1_2188149622_2_x_cfblk1_1_896681653_2_y_cfblk2_410608258_y_cfblk1_371472865']
	[cfblk1_Update_6_2] (y_cfblk5_528014437=ok) & (x_cfblk1_1_896681653=ok) -> 0.98:(x_cfblk2_1_2188149622_2_x_cfblk1_1_896681653_2_y_cfblk2_410608258_y_cfblk1_371472865'=prop_1) + 0.02:(x_cfblk2_1_2188149622_2_x_cfblk1_1_896681653_2_y_cfblk2_410608258_y_cfblk1_371472865'=prop_2);	// <-- 
	[cfblk1_Update_6_2] (y_cfblk5_528014437!=ok) | (x_cfblk1_1_896681653!=ok) -> (x_cfblk2_1_2188149622_2_x_cfblk1_1_896681653_2_y_cfblk2_410608258_y_cfblk1_371472865'=prop_2);	// <-- 
	//Element cfblk1_Update_6_3, df inputs ['x_cfblk1_1_896681653', 'y_cfblk5_528014437'], df outputs ['x_cfblk1_1_896681653']
	[cfblk1_Update_6_3] (y_cfblk5_528014437=ok) & (x_cfblk1_1_896681653=ok) -> 0.98:(x_cfblk1_1_896681653'=ok) + 0.02:(x_cfblk1_1_896681653'=error);	// <-- 
	[cfblk1_Update_6_3] (y_cfblk5_528014437!=ok) | (x_cfblk1_1_896681653!=ok) -> (x_cfblk1_1_896681653'=error);	// <-- 
	//Element cfblk2_Update_7_2, df inputs ['x_cfblk2_1_2188149622', 'y_cfblk5_528014437'], df outputs ['x_cfblk2_1_2188149622_2_x_cfblk1_1_896681653_2_y_cfblk2_410608258_y_cfblk1_371472865']
	[cfblk2_Update_7_2] (y_cfblk5_528014437=ok) & (x_cfblk2_1_2188149622=ok) -> 0.98:(x_cfblk2_1_2188149622_2_x_cfblk1_1_896681653_2_y_cfblk2_410608258_y_cfblk1_371472865'=prop_1) + 0.02:(x_cfblk2_1_2188149622_2_x_cfblk1_1_896681653_2_y_cfblk2_410608258_y_cfblk1_371472865'=prop_2);	// <-- 
	[cfblk2_Update_7_2] (y_cfblk5_528014437!=ok) | (x_cfblk2_1_2188149622!=ok) -> (x_cfblk2_1_2188149622_2_x_cfblk1_1_896681653_2_y_cfblk2_410608258_y_cfblk1_371472865'=prop_2);	// <-- 
	//Element cfblk2_Update_7_3, df inputs ['x_cfblk2_1_2188149622', 'y_cfblk5_528014437'], df outputs ['x_cfblk2_1_2188149622']
	[cfblk2_Update_7_3] (y_cfblk5_528014437=ok) & (x_cfblk2_1_2188149622=ok) -> 0.98:(x_cfblk2_1_2188149622'=ok) + 0.02:(x_cfblk2_1_2188149622'=error);	// <-- 
	[cfblk2_Update_7_3] (y_cfblk5_528014437!=ok) | (x_cfblk2_1_2188149622!=ok) -> (x_cfblk2_1_2188149622'=error);	// <-- 
endmodule

//Failure formulas
formula failure = x_cfblk2_1_2188149622 = error;

rewards "time" true : 1; endrewards
