//Generated by ErrorPro
dtmc
//Element consts
const int cfblk1_Output_1=0;
const int cfblk5_Output_2=1;
const int cfblk3_Output_3=2;
const int cfblk2_Output_4=3;
const int cfblk4_Output_5=4;
const int cfblk1_Update_6=5;
const int cfblk5_Update_7=6;
const int cfblk4_Update_8=7;
const int check_redandancy0=8;
const int cfblk1_Output_1_2=9;
const int cfblk1_Output_1_3=10;
const int compare0=11;
const int stop_system=12;
const int check_redandancy1=13;
const int cfblk3_Output_3_2=14;
const int cfblk3_Output_3_3=15;
const int compare1=16;
const int check_redandancy2=17;
const int cfblk2_Output_4_2=18;
const int cfblk2_Output_4_3=19;
const int compare2=20;
const int check_redandancy3=21;
const int cfblk4_Output_5_2=22;
const int cfblk4_Output_5_3=23;
const int compare3=24;
const int check_redandancy4=25;
const int cfblk1_Update_6_2=26;
const int cfblk1_Update_6_3=27;
const int compare4=28;
const int check_redandancy5=29;
const int cfblk4_Update_8_2=30;
const int cfblk4_Update_8_3=31;
const int compare5=32;
//Data values consts
const int v=0;
const int prop_2=1;
const int prop_1=2;
const int ok=3;
const int no=4;
const int error=5;
const int c=6;
//Control flow commands
module control_flow
	cf:[0..33] init cfblk1_Output_1;
	//Element cfblk1_Output_1, df inputs ['y_cfblk2_1942730104', 'x_cfblk1_1_4212062326'], cf transitions ['check_redandancy0']
	[cfblk1_Output_1] cf=cfblk1_Output_1 -> 1.0:(cf'=check_redandancy0);
	//Element cfblk5_Output_2, df inputs ['x_cfblk5_1_787999612', 'y_cfblk4_2021000890'], cf transitions ['cfblk3_Output_3']
	[cfblk5_Output_2] cf=cfblk5_Output_2 -> 1.0:(cf'=cfblk3_Output_3);
	//Element cfblk3_Output_3, df inputs ['y_cfblk1_1903594711_2_y_cfblk5_2060136283'], cf transitions ['check_redandancy1']
	[cfblk3_Output_3] cf=cfblk3_Output_3 -> 1.0:(cf'=check_redandancy1);
	//Element cfblk2_Output_4, df inputs ['y_cfblk3_1981865497', 'x_cfblk4_1_3791498938_2_x_cfblk1_1_4212062326_2_y_cfblk4_2021000890_2_y_cfblk1_1903594711'], cf transitions ['check_redandancy2']
	[cfblk2_Output_4] cf=cfblk2_Output_4 -> 1.0:(cf'=check_redandancy2);
	//Element cfblk4_Output_5, df inputs ['y_cfblk1_1903594711_2_y_cfblk5_2060136283', 'x_cfblk4_1_3791498938'], cf transitions ['check_redandancy3']
	[cfblk4_Output_5] cf=cfblk4_Output_5 -> 1.0:(cf'=check_redandancy3);
	//Element cfblk1_Update_6, df inputs ['y_cfblk2_1942730104', 'x_cfblk1_1_4212062326'], cf transitions ['check_redandancy4']
	[cfblk1_Update_6] cf=cfblk1_Update_6 -> 1.0:(cf'=check_redandancy4);
	//Element cfblk5_Update_7, df inputs ['x_cfblk5_1_787999612', 'y_cfblk4_2021000890'], cf transitions ['cfblk4_Update_8']
	[cfblk5_Update_7] cf=cfblk5_Update_7 -> 1.0:(cf'=cfblk4_Update_8);
	//Element cfblk4_Update_8, df inputs ['y_cfblk1_1903594711_2_y_cfblk5_2060136283', 'x_cfblk4_1_3791498938'], cf transitions ['check_redandancy5']
	[cfblk4_Update_8] cf=cfblk4_Update_8 -> 1.0:(cf'=check_redandancy5);
	//Element check_redandancy0, df inputs ['redundancy_model59_cfblk1_0'], cf transitions ['cfblk1_Output_1_2', 'cfblk5_Output_2']
	[check_redandancy0] (cf=check_redandancy0) & (redundancy_model59_cfblk1_0=no) -> (cf'=cfblk5_Output_2);	// <-- 
	[check_redandancy0] (cf=check_redandancy0) & ((redundancy_model59_cfblk1_0=v)|(redundancy_model59_cfblk1_0=c)) -> (cf'=cfblk1_Output_1_2);	// <-- 
	//Element cfblk1_Output_1_2, df inputs ['y_cfblk2_1942730104', 'x_cfblk1_1_4212062326'], cf transitions ['compare0']
	[cfblk1_Output_1_2] cf=cfblk1_Output_1_2 -> 1.0:(cf'=compare0);
	//Element cfblk1_Output_1_3, df inputs ['y_cfblk2_1942730104', 'x_cfblk1_1_4212062326'], cf transitions ['cfblk5_Output_2']
	[cfblk1_Output_1_3] cf=cfblk1_Output_1_3 -> 1.0:(cf'=cfblk5_Output_2);
	//Element compare0, df inputs ['x_cfblk4_1_3791498938_2_x_cfblk1_1_4212062326_2_y_cfblk4_2021000890_2_y_cfblk1_1903594711', 'redundancy_model59_cfblk1_0', 'y_cfblk1_1903594711_2_y_cfblk5_2060136283'], cf transitions ['cfblk1_Output_1_3', 'cfblk5_Output_2', 'stop_system']
	[compare0] (cf=compare0) & (redundancy_model59_cfblk1_0=c) & (x_cfblk4_1_3791498938_2_x_cfblk1_1_4212062326_2_y_cfblk4_2021000890_2_y_cfblk1_1903594711=prop_1) & (y_cfblk1_1903594711_2_y_cfblk5_2060136283=prop_1) -> (cf'=cfblk5_Output_2);	// <-- 
	[compare0] (cf=compare0) & (redundancy_model59_cfblk1_0=c) & ((x_cfblk4_1_3791498938_2_x_cfblk1_1_4212062326_2_y_cfblk4_2021000890_2_y_cfblk1_1903594711=prop_2) | (y_cfblk1_1903594711_2_y_cfblk5_2060136283=prop_2)) -> (cf'=stop_system);	// <-- 
	[compare0] (cf=compare0) & (redundancy_model59_cfblk1_0=v) & (x_cfblk4_1_3791498938_2_x_cfblk1_1_4212062326_2_y_cfblk4_2021000890_2_y_cfblk1_1903594711=prop_1) & (y_cfblk1_1903594711_2_y_cfblk5_2060136283=prop_1) -> (cf'=cfblk5_Output_2);	// <-- 
	[compare0] (cf=compare0) & (redundancy_model59_cfblk1_0=v) & ((x_cfblk4_1_3791498938_2_x_cfblk1_1_4212062326_2_y_cfblk4_2021000890_2_y_cfblk1_1903594711=prop_2) | (y_cfblk1_1903594711_2_y_cfblk5_2060136283=prop_2)) -> (cf'=cfblk1_Output_1_3);	// <-- 
	//Element stop_system, cf transitions ['cfblk1_Output_1']
	[stop_system] cf=stop_system -> 1.0:(cf'=cfblk1_Output_1);
	//Element check_redandancy1, df inputs ['redundancy_model59_cfblk3_1'], cf transitions ['cfblk3_Output_3_2', 'cfblk2_Output_4']
	[check_redandancy1] (cf=check_redandancy1) & (redundancy_model59_cfblk3_1=no) -> (cf'=cfblk2_Output_4);	// <-- 
	[check_redandancy1] (cf=check_redandancy1) & ((redundancy_model59_cfblk3_1=v)|(redundancy_model59_cfblk3_1=c)) -> (cf'=cfblk3_Output_3_2);	// <-- 
	//Element cfblk3_Output_3_2, df inputs ['y_cfblk1_1903594711_2_y_cfblk5_2060136283'], cf transitions ['compare1']
	[cfblk3_Output_3_2] cf=cfblk3_Output_3_2 -> 1.0:(cf'=compare1);
	//Element cfblk3_Output_3_3, df inputs ['y_cfblk1_1903594711_2_y_cfblk5_2060136283'], cf transitions ['cfblk2_Output_4']
	[cfblk3_Output_3_3] cf=cfblk3_Output_3_3 -> 1.0:(cf'=cfblk2_Output_4);
	//Element compare1, df inputs ['y_cfblk3_1981865497', 'y_cfblk2_1942730104_2_y_cfblk3_1981865497_2', 'redundancy_model59_cfblk3_1'], cf transitions ['cfblk3_Output_3_3', 'cfblk2_Output_4', 'stop_system']
	[compare1] (cf=compare1) & (redundancy_model59_cfblk3_1=c) & (y_cfblk3_1981865497=ok) & (y_cfblk2_1942730104_2_y_cfblk3_1981865497_2=prop_1) -> (cf'=cfblk2_Output_4);	// <-- 
	[compare1] (cf=compare1) & (redundancy_model59_cfblk3_1=c) & ((y_cfblk3_1981865497=error) | (y_cfblk2_1942730104_2_y_cfblk3_1981865497_2=prop_2)) -> (cf'=stop_system);	// <-- 
	[compare1] (cf=compare1) & (redundancy_model59_cfblk3_1=v) & (y_cfblk3_1981865497=ok) & (y_cfblk2_1942730104_2_y_cfblk3_1981865497_2=prop_1) -> (cf'=cfblk2_Output_4);	// <-- 
	[compare1] (cf=compare1) & (redundancy_model59_cfblk3_1=v) & ((y_cfblk3_1981865497=error) | (y_cfblk2_1942730104_2_y_cfblk3_1981865497_2=prop_2)) -> (cf'=cfblk3_Output_3_3);	// <-- 
	//Element check_redandancy2, df inputs ['redundancy_model59_cfblk2_2'], cf transitions ['cfblk2_Output_4_2', 'cfblk4_Output_5']
	[check_redandancy2] (cf=check_redandancy2) & (redundancy_model59_cfblk2_2=no) -> (cf'=cfblk4_Output_5);	// <-- 
	[check_redandancy2] (cf=check_redandancy2) & ((redundancy_model59_cfblk2_2=v)|(redundancy_model59_cfblk2_2=c)) -> (cf'=cfblk2_Output_4_2);	// <-- 
	//Element cfblk2_Output_4_2, df inputs ['y_cfblk3_1981865497', 'x_cfblk4_1_3791498938_2_x_cfblk1_1_4212062326_2_y_cfblk4_2021000890_2_y_cfblk1_1903594711'], cf transitions ['compare2']
	[cfblk2_Output_4_2] cf=cfblk2_Output_4_2 -> 1.0:(cf'=compare2);
	//Element cfblk2_Output_4_3, df inputs ['y_cfblk3_1981865497', 'x_cfblk4_1_3791498938_2_x_cfblk1_1_4212062326_2_y_cfblk4_2021000890_2_y_cfblk1_1903594711'], cf transitions ['cfblk4_Output_5']
	[cfblk2_Output_4_3] cf=cfblk2_Output_4_3 -> 1.0:(cf'=cfblk4_Output_5);
	//Element compare2, df inputs ['y_cfblk2_1942730104_2_y_cfblk3_1981865497_2', 'y_cfblk2_1942730104', 'redundancy_model59_cfblk2_2'], cf transitions ['cfblk2_Output_4_3', 'cfblk4_Output_5', 'stop_system']
	[compare2] (cf=compare2) & (redundancy_model59_cfblk2_2=c) & (y_cfblk2_1942730104=ok) & (y_cfblk2_1942730104_2_y_cfblk3_1981865497_2=prop_1) -> (cf'=cfblk4_Output_5);	// <-- 
	[compare2] (cf=compare2) & (redundancy_model59_cfblk2_2=c) & ((y_cfblk2_1942730104=error) | (y_cfblk2_1942730104_2_y_cfblk3_1981865497_2=prop_2)) -> (cf'=stop_system);	// <-- 
	[compare2] (cf=compare2) & (redundancy_model59_cfblk2_2=v) & (y_cfblk2_1942730104=ok) & (y_cfblk2_1942730104_2_y_cfblk3_1981865497_2=prop_1) -> (cf'=cfblk4_Output_5);	// <-- 
	[compare2] (cf=compare2) & (redundancy_model59_cfblk2_2=v) & ((y_cfblk2_1942730104=error) | (y_cfblk2_1942730104_2_y_cfblk3_1981865497_2=prop_2)) -> (cf'=cfblk2_Output_4_3);	// <-- 
	//Element check_redandancy3, df inputs ['redundancy_model59_cfblk4_3'], cf transitions ['cfblk4_Output_5_2', 'cfblk1_Update_6']
	[check_redandancy3] (cf=check_redandancy3) & (redundancy_model59_cfblk4_3=no) -> (cf'=cfblk1_Update_6);	// <-- 
	[check_redandancy3] (cf=check_redandancy3) & ((redundancy_model59_cfblk4_3=v)|(redundancy_model59_cfblk4_3=c)) -> (cf'=cfblk4_Output_5_2);	// <-- 
	//Element cfblk4_Output_5_2, df inputs ['y_cfblk1_1903594711_2_y_cfblk5_2060136283', 'x_cfblk4_1_3791498938'], cf transitions ['compare3']
	[cfblk4_Output_5_2] cf=cfblk4_Output_5_2 -> 1.0:(cf'=compare3);
	//Element cfblk4_Output_5_3, df inputs ['y_cfblk1_1903594711_2_y_cfblk5_2060136283', 'x_cfblk4_1_3791498938'], cf transitions ['cfblk1_Update_6']
	[cfblk4_Output_5_3] cf=cfblk4_Output_5_3 -> 1.0:(cf'=cfblk1_Update_6);
	//Element compare3, df inputs ['x_cfblk4_1_3791498938_2_x_cfblk1_1_4212062326_2_y_cfblk4_2021000890_2_y_cfblk1_1903594711', 'y_cfblk4_2021000890', 'redundancy_model59_cfblk4_3'], cf transitions ['cfblk4_Output_5_3', 'cfblk1_Update_6', 'stop_system']
	[compare3] (cf=compare3) & (redundancy_model59_cfblk4_3=c) & (y_cfblk4_2021000890=ok) & (x_cfblk4_1_3791498938_2_x_cfblk1_1_4212062326_2_y_cfblk4_2021000890_2_y_cfblk1_1903594711=prop_1) -> (cf'=cfblk1_Update_6);	// <-- 
	[compare3] (cf=compare3) & (redundancy_model59_cfblk4_3=c) & ((y_cfblk4_2021000890=error) | (x_cfblk4_1_3791498938_2_x_cfblk1_1_4212062326_2_y_cfblk4_2021000890_2_y_cfblk1_1903594711=prop_2)) -> (cf'=stop_system);	// <-- 
	[compare3] (cf=compare3) & (redundancy_model59_cfblk4_3=v) & (y_cfblk4_2021000890=ok) & (x_cfblk4_1_3791498938_2_x_cfblk1_1_4212062326_2_y_cfblk4_2021000890_2_y_cfblk1_1903594711=prop_1) -> (cf'=cfblk1_Update_6);	// <-- 
	[compare3] (cf=compare3) & (redundancy_model59_cfblk4_3=v) & ((y_cfblk4_2021000890=error) | (x_cfblk4_1_3791498938_2_x_cfblk1_1_4212062326_2_y_cfblk4_2021000890_2_y_cfblk1_1903594711=prop_2)) -> (cf'=cfblk4_Output_5_3);	// <-- 
	//Element check_redandancy4, df inputs ['redundancy_model59_cfblk1_0'], cf transitions ['cfblk1_Update_6_2', 'cfblk5_Update_7']
	[check_redandancy4] (cf=check_redandancy4) & (redundancy_model59_cfblk1_0=no) -> (cf'=cfblk5_Update_7);	// <-- 
	[check_redandancy4] (cf=check_redandancy4) & ((redundancy_model59_cfblk1_0=v)|(redundancy_model59_cfblk1_0=c)) -> (cf'=cfblk1_Update_6_2);	// <-- 
	//Element cfblk1_Update_6_2, df inputs ['y_cfblk2_1942730104', 'x_cfblk1_1_4212062326'], cf transitions ['compare4']
	[cfblk1_Update_6_2] cf=cfblk1_Update_6_2 -> 1.0:(cf'=compare4);
	//Element cfblk1_Update_6_3, df inputs ['y_cfblk2_1942730104', 'x_cfblk1_1_4212062326'], cf transitions ['cfblk5_Update_7']
	[cfblk1_Update_6_3] cf=cfblk1_Update_6_3 -> 1.0:(cf'=cfblk5_Update_7);
	//Element compare4, df inputs ['x_cfblk1_1_4212062326', 'redundancy_model59_cfblk1_0', 'x_cfblk4_1_3791498938_2_x_cfblk1_1_4212062326_2_y_cfblk4_2021000890_2_y_cfblk1_1903594711'], cf transitions ['cfblk1_Update_6_3', 'cfblk5_Update_7', 'stop_system']
	[compare4] (cf=compare4) & (redundancy_model59_cfblk1_0=c) & (x_cfblk1_1_4212062326=ok) & (x_cfblk4_1_3791498938_2_x_cfblk1_1_4212062326_2_y_cfblk4_2021000890_2_y_cfblk1_1903594711=prop_1) -> (cf'=cfblk5_Update_7);	// <-- 
	[compare4] (cf=compare4) & (redundancy_model59_cfblk1_0=c) & ((x_cfblk1_1_4212062326=error) | (x_cfblk4_1_3791498938_2_x_cfblk1_1_4212062326_2_y_cfblk4_2021000890_2_y_cfblk1_1903594711=prop_2)) -> (cf'=stop_system);	// <-- 
	[compare4] (cf=compare4) & (redundancy_model59_cfblk1_0=v) & (x_cfblk1_1_4212062326=ok) & (x_cfblk4_1_3791498938_2_x_cfblk1_1_4212062326_2_y_cfblk4_2021000890_2_y_cfblk1_1903594711=prop_1) -> (cf'=cfblk5_Update_7);	// <-- 
	[compare4] (cf=compare4) & (redundancy_model59_cfblk1_0=v) & ((x_cfblk1_1_4212062326=error) | (x_cfblk4_1_3791498938_2_x_cfblk1_1_4212062326_2_y_cfblk4_2021000890_2_y_cfblk1_1903594711=prop_2)) -> (cf'=cfblk1_Update_6_3);	// <-- 
	//Element check_redandancy5, df inputs ['redundancy_model59_cfblk4_3'], cf transitions ['cfblk4_Update_8_2', 'cfblk1_Output_1']
	[check_redandancy5] (cf=check_redandancy5) & (redundancy_model59_cfblk4_3=no) -> (cf'=cfblk1_Output_1);	// <-- 
	[check_redandancy5] (cf=check_redandancy5) & ((redundancy_model59_cfblk4_3=v)|(redundancy_model59_cfblk4_3=c)) -> (cf'=cfblk4_Update_8_2);	// <-- 
	//Element cfblk4_Update_8_2, df inputs ['y_cfblk1_1903594711_2_y_cfblk5_2060136283', 'x_cfblk4_1_3791498938'], cf transitions ['compare5']
	[cfblk4_Update_8_2] cf=cfblk4_Update_8_2 -> 1.0:(cf'=compare5);
	//Element cfblk4_Update_8_3, df inputs ['y_cfblk1_1903594711_2_y_cfblk5_2060136283', 'x_cfblk4_1_3791498938'], cf transitions ['cfblk1_Output_1']
	[cfblk4_Update_8_3] cf=cfblk4_Update_8_3 -> 1.0:(cf'=cfblk1_Output_1);
	//Element compare5, df inputs ['x_cfblk4_1_3791498938_2_x_cfblk1_1_4212062326_2_y_cfblk4_2021000890_2_y_cfblk1_1903594711', 'x_cfblk4_1_3791498938', 'redundancy_model59_cfblk4_3'], cf transitions ['cfblk4_Update_8_3', 'cfblk1_Output_1', 'stop_system']
	[compare5] (cf=compare5) & (redundancy_model59_cfblk4_3=c) & (x_cfblk4_1_3791498938=ok) & (x_cfblk4_1_3791498938_2_x_cfblk1_1_4212062326_2_y_cfblk4_2021000890_2_y_cfblk1_1903594711=prop_1) -> (cf'=cfblk1_Output_1);	// <-- 
	[compare5] (cf=compare5) & (redundancy_model59_cfblk4_3=c) & ((x_cfblk4_1_3791498938=error) | (x_cfblk4_1_3791498938_2_x_cfblk1_1_4212062326_2_y_cfblk4_2021000890_2_y_cfblk1_1903594711=prop_2)) -> (cf'=stop_system);	// <-- 
	[compare5] (cf=compare5) & (redundancy_model59_cfblk4_3=v) & (x_cfblk4_1_3791498938=ok) & (x_cfblk4_1_3791498938_2_x_cfblk1_1_4212062326_2_y_cfblk4_2021000890_2_y_cfblk1_1903594711=prop_1) -> (cf'=cfblk1_Output_1);	// <-- 
	[compare5] (cf=compare5) & (redundancy_model59_cfblk4_3=v) & ((x_cfblk4_1_3791498938=error) | (x_cfblk4_1_3791498938_2_x_cfblk1_1_4212062326_2_y_cfblk4_2021000890_2_y_cfblk1_1903594711=prop_2)) -> (cf'=cfblk4_Update_8_3);	// <-- 
endmodule
//Error propagation commands
module error_propagation
	y_cfblk2_1942730104 : [0 .. 6] init ok;
	y_cfblk3_1981865497 : [0 .. 6] init ok;
	y_cfblk4_2021000890 : [0 .. 6] init ok;
	x_cfblk1_1_4212062326 : [0 .. 6] init ok;
	x_cfblk5_1_787999612 : [0 .. 6] init ok;
	x_cfblk4_1_3791498938 : [0 .. 6] init ok;
	redundancy_model59_cfblk1_0 : [0 .. 6] init no;
	redundancy_model59_cfblk3_1 : [0 .. 6] init no;
	redundancy_model59_cfblk2_2 : [0 .. 6] init c;
	redundancy_model59_cfblk4_3 : [0 .. 6] init no;
	y_cfblk2_1942730104_2_y_cfblk3_1981865497_2 : [0 .. 6] init prop_1;
	y_cfblk1_1903594711_2_y_cfblk5_2060136283 : [0 .. 6] init prop_1;
	x_cfblk4_1_3791498938_2_x_cfblk1_1_4212062326_2_y_cfblk4_2021000890_2_y_cfblk1_1903594711 : [0 .. 6] init prop_1;
	//Element cfblk1_Output_1, df inputs ['y_cfblk2_1942730104', 'x_cfblk1_1_4212062326'], df outputs ['x_cfblk4_1_3791498938_2_x_cfblk1_1_4212062326_2_y_cfblk4_2021000890_2_y_cfblk1_1903594711']
	[cfblk1_Output_1] (y_cfblk2_1942730104=ok) & (x_cfblk1_1_4212062326=ok) -> 0.98:(x_cfblk4_1_3791498938_2_x_cfblk1_1_4212062326_2_y_cfblk4_2021000890_2_y_cfblk1_1903594711'=prop_1) + 0.02:(x_cfblk4_1_3791498938_2_x_cfblk1_1_4212062326_2_y_cfblk4_2021000890_2_y_cfblk1_1903594711'=prop_2);	// <-- 
	[cfblk1_Output_1] (y_cfblk2_1942730104!=ok) | (x_cfblk1_1_4212062326!=ok) -> (x_cfblk4_1_3791498938_2_x_cfblk1_1_4212062326_2_y_cfblk4_2021000890_2_y_cfblk1_1903594711'=prop_2);	// <-- 
	//Element cfblk5_Output_2, df inputs ['x_cfblk5_1_787999612', 'y_cfblk4_2021000890'], df outputs ['y_cfblk1_1903594711_2_y_cfblk5_2060136283']
	[cfblk5_Output_2] (y_cfblk4_2021000890=ok) & (x_cfblk5_1_787999612=ok) -> 0.98:(y_cfblk1_1903594711_2_y_cfblk5_2060136283'=prop_1) + 0.02:(y_cfblk1_1903594711_2_y_cfblk5_2060136283'=prop_2);	// <-- 
	[cfblk5_Output_2] (y_cfblk4_2021000890!=ok) | (x_cfblk5_1_787999612!=ok) -> (y_cfblk1_1903594711_2_y_cfblk5_2060136283'=prop_2);	// <-- 
	//Element cfblk3_Output_3, df inputs ['y_cfblk1_1903594711_2_y_cfblk5_2060136283'], df outputs ['y_cfblk3_1981865497']
	[cfblk3_Output_3] (y_cfblk1_1903594711_2_y_cfblk5_2060136283=prop_1) -> 0.969003039904:(y_cfblk3_1981865497'=ok) + 0.030996960095999997:(y_cfblk3_1981865497'=error);	// <-- 
	[cfblk3_Output_3] (y_cfblk1_1903594711_2_y_cfblk5_2060136283!=prop_1) -> (y_cfblk3_1981865497'=error);	// <-- 
	//Element cfblk2_Output_4, df inputs ['y_cfblk3_1981865497', 'x_cfblk4_1_3791498938_2_x_cfblk1_1_4212062326_2_y_cfblk4_2021000890_2_y_cfblk1_1903594711'], df outputs ['y_cfblk2_1942730104']
	[cfblk2_Output_4] (x_cfblk4_1_3791498938_2_x_cfblk1_1_4212062326_2_y_cfblk4_2021000890_2_y_cfblk1_1903594711=prop_1) & (y_cfblk3_1981865497=ok) -> 0.974002239936:(y_cfblk2_1942730104'=ok) + 0.025997760064:(y_cfblk2_1942730104'=error);	// <-- 
	[cfblk2_Output_4] (x_cfblk4_1_3791498938_2_x_cfblk1_1_4212062326_2_y_cfblk4_2021000890_2_y_cfblk1_1903594711!=prop_1) | (y_cfblk3_1981865497!=ok) -> (y_cfblk2_1942730104'=error);	// <-- 
	//Element cfblk4_Output_5, df inputs ['y_cfblk1_1903594711_2_y_cfblk5_2060136283', 'x_cfblk4_1_3791498938'], df outputs ['y_cfblk4_2021000890']
	[cfblk4_Output_5] (y_cfblk1_1903594711_2_y_cfblk5_2060136283=prop_1) & (x_cfblk4_1_3791498938=ok) -> 0.98:(y_cfblk4_2021000890'=ok) + 0.02:(y_cfblk4_2021000890'=error);	// <-- 
	[cfblk4_Output_5] (y_cfblk1_1903594711_2_y_cfblk5_2060136283!=prop_1) | (x_cfblk4_1_3791498938!=ok) -> (y_cfblk4_2021000890'=error);	// <-- 
	//Element cfblk1_Update_6, df inputs ['y_cfblk2_1942730104', 'x_cfblk1_1_4212062326'], df outputs ['x_cfblk1_1_4212062326']
	[cfblk1_Update_6] (y_cfblk2_1942730104=ok) & (x_cfblk1_1_4212062326=ok) -> 0.98:(x_cfblk1_1_4212062326'=ok) + 0.02:(x_cfblk1_1_4212062326'=error);	// <-- 
	[cfblk1_Update_6] (y_cfblk2_1942730104!=ok) | (x_cfblk1_1_4212062326!=ok) -> (x_cfblk1_1_4212062326'=error);	// <-- 
	//Element cfblk5_Update_7, df inputs ['x_cfblk5_1_787999612', 'y_cfblk4_2021000890'], df outputs ['x_cfblk5_1_787999612']
	[cfblk5_Update_7] (y_cfblk4_2021000890=ok) & (x_cfblk5_1_787999612=ok) -> 0.98:(x_cfblk5_1_787999612'=ok) + 0.02:(x_cfblk5_1_787999612'=error);	// <-- 
	[cfblk5_Update_7] (y_cfblk4_2021000890!=ok) | (x_cfblk5_1_787999612!=ok) -> (x_cfblk5_1_787999612'=error);	// <-- 
	//Element cfblk4_Update_8, df inputs ['y_cfblk1_1903594711_2_y_cfblk5_2060136283', 'x_cfblk4_1_3791498938'], df outputs ['x_cfblk4_1_3791498938']
	[cfblk4_Update_8] (y_cfblk1_1903594711_2_y_cfblk5_2060136283=prop_1) & (x_cfblk4_1_3791498938=ok) -> 0.98:(x_cfblk4_1_3791498938'=ok) + 0.02:(x_cfblk4_1_3791498938'=error);	// <-- 
	[cfblk4_Update_8] (y_cfblk1_1903594711_2_y_cfblk5_2060136283!=prop_1) | (x_cfblk4_1_3791498938!=ok) -> (x_cfblk4_1_3791498938'=error);	// <-- 
	//Element cfblk1_Output_1_2, df inputs ['y_cfblk2_1942730104', 'x_cfblk1_1_4212062326'], df outputs ['y_cfblk1_1903594711_2_y_cfblk5_2060136283']
	[cfblk1_Output_1_2] (y_cfblk2_1942730104=ok) & (x_cfblk1_1_4212062326=ok) -> 0.98:(y_cfblk1_1903594711_2_y_cfblk5_2060136283'=prop_1) + 0.02:(y_cfblk1_1903594711_2_y_cfblk5_2060136283'=prop_2);	// <-- 
	[cfblk1_Output_1_2] (y_cfblk2_1942730104!=ok) | (x_cfblk1_1_4212062326!=ok) -> (y_cfblk1_1903594711_2_y_cfblk5_2060136283'=prop_2);	// <-- 
	//Element cfblk1_Output_1_3, df inputs ['y_cfblk2_1942730104', 'x_cfblk1_1_4212062326'], df outputs ['x_cfblk4_1_3791498938_2_x_cfblk1_1_4212062326_2_y_cfblk4_2021000890_2_y_cfblk1_1903594711']
	[cfblk1_Output_1_3] (y_cfblk2_1942730104=ok) & (x_cfblk1_1_4212062326=ok) -> 0.98:(x_cfblk4_1_3791498938_2_x_cfblk1_1_4212062326_2_y_cfblk4_2021000890_2_y_cfblk1_1903594711'=prop_1) + 0.02:(x_cfblk4_1_3791498938_2_x_cfblk1_1_4212062326_2_y_cfblk4_2021000890_2_y_cfblk1_1903594711'=prop_2);	// <-- 
	[cfblk1_Output_1_3] (y_cfblk2_1942730104!=ok) | (x_cfblk1_1_4212062326!=ok) -> (x_cfblk4_1_3791498938_2_x_cfblk1_1_4212062326_2_y_cfblk4_2021000890_2_y_cfblk1_1903594711'=prop_2);	// <-- 
	//Element cfblk3_Output_3_2, df inputs ['y_cfblk1_1903594711_2_y_cfblk5_2060136283'], df outputs ['y_cfblk2_1942730104_2_y_cfblk3_1981865497_2']
	[cfblk3_Output_3_2] (y_cfblk1_1903594711_2_y_cfblk5_2060136283=prop_1) -> 0.969003039904:(y_cfblk2_1942730104_2_y_cfblk3_1981865497_2'=prop_1) + 0.030996960095999997:(y_cfblk2_1942730104_2_y_cfblk3_1981865497_2'=prop_2);	// <-- 
	[cfblk3_Output_3_2] (y_cfblk1_1903594711_2_y_cfblk5_2060136283!=prop_1) -> (y_cfblk2_1942730104_2_y_cfblk3_1981865497_2'=prop_2);	// <-- 
	//Element cfblk3_Output_3_3, df inputs ['y_cfblk1_1903594711_2_y_cfblk5_2060136283'], df outputs ['y_cfblk3_1981865497']
	[cfblk3_Output_3_3] (y_cfblk1_1903594711_2_y_cfblk5_2060136283=prop_1) -> 0.969003039904:(y_cfblk3_1981865497'=ok) + 0.030996960095999997:(y_cfblk3_1981865497'=error);	// <-- 
	[cfblk3_Output_3_3] (y_cfblk1_1903594711_2_y_cfblk5_2060136283!=prop_1) -> (y_cfblk3_1981865497'=error);	// <-- 
	//Element cfblk2_Output_4_2, df inputs ['y_cfblk3_1981865497', 'x_cfblk4_1_3791498938_2_x_cfblk1_1_4212062326_2_y_cfblk4_2021000890_2_y_cfblk1_1903594711'], df outputs ['y_cfblk2_1942730104_2_y_cfblk3_1981865497_2']
	[cfblk2_Output_4_2] (x_cfblk4_1_3791498938_2_x_cfblk1_1_4212062326_2_y_cfblk4_2021000890_2_y_cfblk1_1903594711=prop_1) & (y_cfblk3_1981865497=ok) -> 0.974002239936:(y_cfblk2_1942730104_2_y_cfblk3_1981865497_2'=prop_1) + 0.025997760064:(y_cfblk2_1942730104_2_y_cfblk3_1981865497_2'=prop_2);	// <-- 
	[cfblk2_Output_4_2] (x_cfblk4_1_3791498938_2_x_cfblk1_1_4212062326_2_y_cfblk4_2021000890_2_y_cfblk1_1903594711!=prop_1) | (y_cfblk3_1981865497!=ok) -> (y_cfblk2_1942730104_2_y_cfblk3_1981865497_2'=prop_2);	// <-- 
	//Element cfblk2_Output_4_3, df inputs ['y_cfblk3_1981865497', 'x_cfblk4_1_3791498938_2_x_cfblk1_1_4212062326_2_y_cfblk4_2021000890_2_y_cfblk1_1903594711'], df outputs ['y_cfblk2_1942730104']
	[cfblk2_Output_4_3] (x_cfblk4_1_3791498938_2_x_cfblk1_1_4212062326_2_y_cfblk4_2021000890_2_y_cfblk1_1903594711=prop_1) & (y_cfblk3_1981865497=ok) -> 0.974002239936:(y_cfblk2_1942730104'=ok) + 0.025997760064:(y_cfblk2_1942730104'=error);	// <-- 
	[cfblk2_Output_4_3] (x_cfblk4_1_3791498938_2_x_cfblk1_1_4212062326_2_y_cfblk4_2021000890_2_y_cfblk1_1903594711!=prop_1) | (y_cfblk3_1981865497!=ok) -> (y_cfblk2_1942730104'=error);	// <-- 
	//Element cfblk4_Output_5_2, df inputs ['y_cfblk1_1903594711_2_y_cfblk5_2060136283', 'x_cfblk4_1_3791498938'], df outputs ['x_cfblk4_1_3791498938_2_x_cfblk1_1_4212062326_2_y_cfblk4_2021000890_2_y_cfblk1_1903594711']
	[cfblk4_Output_5_2] (y_cfblk1_1903594711_2_y_cfblk5_2060136283=prop_1) & (x_cfblk4_1_3791498938=ok) -> 0.98:(x_cfblk4_1_3791498938_2_x_cfblk1_1_4212062326_2_y_cfblk4_2021000890_2_y_cfblk1_1903594711'=prop_1) + 0.02:(x_cfblk4_1_3791498938_2_x_cfblk1_1_4212062326_2_y_cfblk4_2021000890_2_y_cfblk1_1903594711'=prop_2);	// <-- 
	[cfblk4_Output_5_2] (y_cfblk1_1903594711_2_y_cfblk5_2060136283!=prop_1) | (x_cfblk4_1_3791498938!=ok) -> (x_cfblk4_1_3791498938_2_x_cfblk1_1_4212062326_2_y_cfblk4_2021000890_2_y_cfblk1_1903594711'=prop_2);	// <-- 
	//Element cfblk4_Output_5_3, df inputs ['y_cfblk1_1903594711_2_y_cfblk5_2060136283', 'x_cfblk4_1_3791498938'], df outputs ['y_cfblk4_2021000890']
	[cfblk4_Output_5_3] (y_cfblk1_1903594711_2_y_cfblk5_2060136283=prop_1) & (x_cfblk4_1_3791498938=ok) -> 0.98:(y_cfblk4_2021000890'=ok) + 0.02:(y_cfblk4_2021000890'=error);	// <-- 
	[cfblk4_Output_5_3] (y_cfblk1_1903594711_2_y_cfblk5_2060136283!=prop_1) | (x_cfblk4_1_3791498938!=ok) -> (y_cfblk4_2021000890'=error);	// <-- 
	//Element cfblk1_Update_6_2, df inputs ['y_cfblk2_1942730104', 'x_cfblk1_1_4212062326'], df outputs ['x_cfblk4_1_3791498938_2_x_cfblk1_1_4212062326_2_y_cfblk4_2021000890_2_y_cfblk1_1903594711']
	[cfblk1_Update_6_2] (y_cfblk2_1942730104=ok) & (x_cfblk1_1_4212062326=ok) -> 0.98:(x_cfblk4_1_3791498938_2_x_cfblk1_1_4212062326_2_y_cfblk4_2021000890_2_y_cfblk1_1903594711'=prop_1) + 0.02:(x_cfblk4_1_3791498938_2_x_cfblk1_1_4212062326_2_y_cfblk4_2021000890_2_y_cfblk1_1903594711'=prop_2);	// <-- 
	[cfblk1_Update_6_2] (y_cfblk2_1942730104!=ok) | (x_cfblk1_1_4212062326!=ok) -> (x_cfblk4_1_3791498938_2_x_cfblk1_1_4212062326_2_y_cfblk4_2021000890_2_y_cfblk1_1903594711'=prop_2);	// <-- 
	//Element cfblk1_Update_6_3, df inputs ['y_cfblk2_1942730104', 'x_cfblk1_1_4212062326'], df outputs ['x_cfblk1_1_4212062326']
	[cfblk1_Update_6_3] (y_cfblk2_1942730104=ok) & (x_cfblk1_1_4212062326=ok) -> 0.98:(x_cfblk1_1_4212062326'=ok) + 0.02:(x_cfblk1_1_4212062326'=error);	// <-- 
	[cfblk1_Update_6_3] (y_cfblk2_1942730104!=ok) | (x_cfblk1_1_4212062326!=ok) -> (x_cfblk1_1_4212062326'=error);	// <-- 
	//Element cfblk4_Update_8_2, df inputs ['y_cfblk1_1903594711_2_y_cfblk5_2060136283', 'x_cfblk4_1_3791498938'], df outputs ['x_cfblk4_1_3791498938_2_x_cfblk1_1_4212062326_2_y_cfblk4_2021000890_2_y_cfblk1_1903594711']
	[cfblk4_Update_8_2] (y_cfblk1_1903594711_2_y_cfblk5_2060136283=prop_1) & (x_cfblk4_1_3791498938=ok) -> 0.98:(x_cfblk4_1_3791498938_2_x_cfblk1_1_4212062326_2_y_cfblk4_2021000890_2_y_cfblk1_1903594711'=prop_1) + 0.02:(x_cfblk4_1_3791498938_2_x_cfblk1_1_4212062326_2_y_cfblk4_2021000890_2_y_cfblk1_1903594711'=prop_2);	// <-- 
	[cfblk4_Update_8_2] (y_cfblk1_1903594711_2_y_cfblk5_2060136283!=prop_1) | (x_cfblk4_1_3791498938!=ok) -> (x_cfblk4_1_3791498938_2_x_cfblk1_1_4212062326_2_y_cfblk4_2021000890_2_y_cfblk1_1903594711'=prop_2);	// <-- 
	//Element cfblk4_Update_8_3, df inputs ['y_cfblk1_1903594711_2_y_cfblk5_2060136283', 'x_cfblk4_1_3791498938'], df outputs ['x_cfblk4_1_3791498938']
	[cfblk4_Update_8_3] (y_cfblk1_1903594711_2_y_cfblk5_2060136283=prop_1) & (x_cfblk4_1_3791498938=ok) -> 0.98:(x_cfblk4_1_3791498938'=ok) + 0.02:(x_cfblk4_1_3791498938'=error);	// <-- 
	[cfblk4_Update_8_3] (y_cfblk1_1903594711_2_y_cfblk5_2060136283!=prop_1) | (x_cfblk4_1_3791498938!=ok) -> (x_cfblk4_1_3791498938'=error);	// <-- 
endmodule

//Failure formulas
formula failure = x_cfblk4_1_3791498938 = error;

rewards "time" true : 1; endrewards
