//Generated by ErrorPro
dtmc
//Element consts
const int cfblk5_Output_1=0;
const int cfblk1_Output_2=1;
const int cfblk4_Output_3=2;
const int cfblk2_Output_4=3;
const int cfblk3_Output_5=4;
const int cfblk5_Update_6=5;
const int check_redandancy1=6;
const int cfblk4_Output_3_2=7;
const int cfblk4_Output_3_3=8;
const int compare1=9;
const int stop_system=10;
//Data values consts
const int v=0;
const int ok=1;
const int no=2;
const int error=3;
const int c=4;
//Control flow commands
module control_flow
	cf:[0..11] init cfblk5_Output_1;
	//Element cfblk5_Output_1, df inputs ['y_cfblk4_3918921016', 'x_cfblk5_1_3289821640'], cf transitions ['cfblk1_Output_2']
	[cfblk5_Output_1] cf=cfblk5_Output_1 -> 1.0:(cf'=cfblk1_Output_2);
	//Element cfblk1_Output_2, df inputs ['y_cfblk5_3958056409'], cf transitions ['cfblk4_Output_3']
	[cfblk1_Output_2] cf=cfblk1_Output_2 -> 1.0:(cf'=cfblk4_Output_3);
	//Element cfblk4_Output_3, cf transitions ['check_redandancy1']
	[cfblk4_Output_3] cf=cfblk4_Output_3 -> 1.0:(cf'=check_redandancy1);
	//Element cfblk2_Output_4, df inputs ['y_cfblk4_3918921016'], cf transitions ['cfblk3_Output_5']
	[cfblk2_Output_4] cf=cfblk2_Output_4 -> 1.0:(cf'=cfblk3_Output_5);
	//Element cfblk3_Output_5, df inputs ['y_cfblk4_3918921016'], cf transitions ['cfblk5_Update_6']
	[cfblk3_Output_5] cf=cfblk3_Output_5 -> 1.0:(cf'=cfblk5_Update_6);
	//Element cfblk5_Update_6, df inputs ['y_cfblk4_3918921016', 'x_cfblk5_1_3289821640'], cf transitions ['cfblk5_Output_1']
	[cfblk5_Update_6] cf=cfblk5_Update_6 -> 1.0:(cf'=cfblk5_Output_1);
	//Element check_redandancy1, df inputs ['redundancy_model81_cfblk4_1'], cf transitions ['cfblk4_Output_3_2', 'cfblk2_Output_4']
	[check_redandancy1] (cf=check_redandancy1) & (redundancy_model81_cfblk4_1=no) -> (cf'=cfblk2_Output_4);	// <-- 
	[check_redandancy1] (cf=check_redandancy1) & ((redundancy_model81_cfblk4_1=v)|(redundancy_model81_cfblk4_1=c)) -> (cf'=cfblk4_Output_3_2);	// <-- 
	//Element cfblk4_Output_3_2, cf transitions ['compare1']
	[cfblk4_Output_3_2] cf=cfblk4_Output_3_2 -> 1.0:(cf'=compare1);
	//Element cfblk4_Output_3_3, cf transitions ['cfblk2_Output_4']
	[cfblk4_Output_3_3] cf=cfblk4_Output_3_3 -> 1.0:(cf'=cfblk2_Output_4);
	//Element compare1, df inputs ['redundancy_model81_cfblk4_1', 'y_cfblk4_3918921016_2', 'y_cfblk4_3918921016'], cf transitions ['cfblk4_Output_3_3', 'cfblk2_Output_4', 'stop_system']
	[compare1] (cf=compare1) & (redundancy_model81_cfblk4_1=c) & (y_cfblk4_3918921016=ok) & (y_cfblk4_3918921016_2=ok) -> (cf'=cfblk2_Output_4);	// <-- 
	[compare1] (cf=compare1) & (redundancy_model81_cfblk4_1=c) & ((y_cfblk4_3918921016=error) | (y_cfblk4_3918921016_2=error)) -> (cf'=stop_system);	// <-- 
	[compare1] (cf=compare1) & (redundancy_model81_cfblk4_1=v) & (y_cfblk4_3918921016=ok) & (y_cfblk4_3918921016_2=ok) -> (cf'=cfblk2_Output_4);	// <-- 
	[compare1] (cf=compare1) & (redundancy_model81_cfblk4_1=v) & ((y_cfblk4_3918921016=error) | (y_cfblk4_3918921016_2=error)) -> (cf'=cfblk4_Output_3_3);	// <-- 
	//Element stop_system, cf transitions ['cfblk5_Output_1']
	[stop_system] cf=stop_system -> 1.0:(cf'=cfblk5_Output_1);
endmodule
//Error propagation commands
module error_propagation
	y_cfblk4_3918921016 : [0 .. 4] init ok;
	y_cfblk5_3958056409 : [0 .. 4] init ok;
	x_cfblk5_1_3289821640 : [0 .. 4] init ok;
	redundancy_model81_cfblk4_1 : [0 .. 4] init c;
	y_cfblk4_3918921016_2 : [0 .. 4] init ok;
	//Element cfblk5_Output_1, df inputs ['y_cfblk4_3918921016', 'x_cfblk5_1_3289821640'], df outputs ['y_cfblk5_3958056409']
	[cfblk5_Output_1] (y_cfblk4_3918921016=ok) & (x_cfblk5_1_3289821640=ok) -> 0.98:(y_cfblk5_3958056409'=ok) + 0.02:(y_cfblk5_3958056409'=error);	// <-- 
	[cfblk5_Output_1] (y_cfblk4_3918921016!=ok) | (x_cfblk5_1_3289821640!=ok) -> (y_cfblk5_3958056409'=error);	// <-- 
	//Element cfblk4_Output_3, df outputs ['y_cfblk4_3918921016']
	[cfblk4_Output_3] (true) -> 1:(y_cfblk4_3918921016'=ok);	// <-- 
	//Element cfblk5_Update_6, df inputs ['y_cfblk4_3918921016', 'x_cfblk5_1_3289821640'], df outputs ['x_cfblk5_1_3289821640']
	[cfblk5_Update_6] (y_cfblk4_3918921016=ok) & (x_cfblk5_1_3289821640=ok) -> 0.98:(x_cfblk5_1_3289821640'=ok) + 0.02:(x_cfblk5_1_3289821640'=error);	// <-- 
	[cfblk5_Update_6] (y_cfblk4_3918921016!=ok) | (x_cfblk5_1_3289821640!=ok) -> (x_cfblk5_1_3289821640'=error);	// <-- 
	//Element cfblk4_Output_3_2, df outputs ['y_cfblk4_3918921016_2']
	[cfblk4_Output_3_2] (true) -> 1:(y_cfblk4_3918921016_2'=ok);	// <-- 
	//Element cfblk4_Output_3_3, df outputs ['y_cfblk4_3918921016']
	[cfblk4_Output_3_3] (true) -> 1:(y_cfblk4_3918921016'=ok);	// <-- 
endmodule

//Failure formulas
formula failure = x_cfblk5_1_3289821640 = error;

rewards "time" true : 1; endrewards
