//Generated by ErrorPro
dtmc
//Element consts
const int cfblk5_Output_1=0;
const int cfblk1_Output_2=1;
const int cfblk4_Output_3=2;
const int cfblk2_Output_4=3;
const int cfblk3_Output_5=4;
const int cfblk5_Update_6=5;
const int cfblk1_Update_7=6;
const int check_redandancy0=7;
const int cfblk1_Output_2_2=8;
const int cfblk1_Output_2_3=9;
const int compare0=10;
const int stop_system=11;
const int check_redandancy1=12;
const int cfblk4_Output_3_2=13;
const int cfblk4_Output_3_3=14;
const int compare1=15;
const int check_redandancy3=16;
const int cfblk3_Output_5_2=17;
const int cfblk3_Output_5_3=18;
const int compare3=19;
const int check_redandancy4=20;
const int cfblk1_Update_7_2=21;
const int cfblk1_Update_7_3=22;
const int compare4=23;
//Data values consts
const int v=0;
const int prop_2=1;
const int prop_1=2;
const int ok=3;
const int no=4;
const int error=5;
const int c=6;
//Control flow commands
module control_flow
	cf:[0..24] init cfblk5_Output_1;
	//Element cfblk5_Output_1, df inputs ['x_cfblk5_1_1548702784', 'y_cfblk4_221945164'], cf transitions ['cfblk1_Output_2']
	[cfblk5_Output_1] cf=cfblk5_Output_1 -> 1.0:(cf'=cfblk1_Output_2);
	//Element cfblk1_Output_2, df inputs ['x_cfblk1_1_677798203', 'y_cfblk3_182809771'], cf transitions ['check_redandancy0']
	[cfblk1_Output_2] cf=cfblk1_Output_2 -> 1.0:(cf'=check_redandancy0);
	//Element cfblk4_Output_3, df inputs ['x_cfblk1_1_677798203_2_y_cfblk1_104538985', 'y_cfblk3_182809771_2_y_cfblk5_261080557'], cf transitions ['check_redandancy1']
	[cfblk4_Output_3] cf=cfblk4_Output_3 -> 1.0:(cf'=check_redandancy1);
	//Element cfblk2_Output_4, df inputs ['y_cfblk4_221945164'], cf transitions ['cfblk3_Output_5']
	[cfblk2_Output_4] cf=cfblk2_Output_4 -> 1.0:(cf'=cfblk3_Output_5);
	//Element cfblk3_Output_5, df inputs ['x_cfblk1_1_677798203_2_y_cfblk1_104538985', 'y_cfblk4_221945164'], cf transitions ['check_redandancy3']
	[cfblk3_Output_5] cf=cfblk3_Output_5 -> 1.0:(cf'=check_redandancy3);
	//Element cfblk5_Update_6, df inputs ['x_cfblk5_1_1548702784', 'y_cfblk4_221945164'], cf transitions ['cfblk1_Update_7']
	[cfblk5_Update_6] cf=cfblk5_Update_6 -> 1.0:(cf'=cfblk1_Update_7);
	//Element cfblk1_Update_7, df inputs ['x_cfblk1_1_677798203', 'y_cfblk3_182809771'], cf transitions ['check_redandancy4']
	[cfblk1_Update_7] cf=cfblk1_Update_7 -> 1.0:(cf'=check_redandancy4);
	//Element check_redandancy0, df inputs ['redundancy_model41_cfblk1_0'], cf transitions ['cfblk1_Output_2_2', 'cfblk4_Output_3']
	[check_redandancy0] (cf=check_redandancy0) & (redundancy_model41_cfblk1_0=no) -> (cf'=cfblk4_Output_3);	// <-- 
	[check_redandancy0] (cf=check_redandancy0) & ((redundancy_model41_cfblk1_0=v)|(redundancy_model41_cfblk1_0=c)) -> (cf'=cfblk1_Output_2_2);	// <-- 
	//Element cfblk1_Output_2_2, df inputs ['x_cfblk1_1_677798203', 'y_cfblk3_182809771'], cf transitions ['compare0']
	[cfblk1_Output_2_2] cf=cfblk1_Output_2_2 -> 1.0:(cf'=compare0);
	//Element cfblk1_Output_2_3, df inputs ['x_cfblk1_1_677798203', 'y_cfblk3_182809771'], cf transitions ['cfblk4_Output_3']
	[cfblk1_Output_2_3] cf=cfblk1_Output_2_3 -> 1.0:(cf'=cfblk4_Output_3);
	//Element compare0, df inputs ['x_cfblk1_1_677798203_2_y_cfblk1_104538985', 'redundancy_model41_cfblk1_0', 'y_cfblk4_221945164_2_y_cfblk1_104538985_2'], cf transitions ['cfblk1_Output_2_3', 'cfblk4_Output_3', 'stop_system']
	[compare0] (cf=compare0) & (redundancy_model41_cfblk1_0=c) & (x_cfblk1_1_677798203_2_y_cfblk1_104538985=prop_1) & (y_cfblk4_221945164_2_y_cfblk1_104538985_2=prop_1) -> (cf'=cfblk4_Output_3);	// <-- 
	[compare0] (cf=compare0) & (redundancy_model41_cfblk1_0=c) & ((x_cfblk1_1_677798203_2_y_cfblk1_104538985=prop_2) | (y_cfblk4_221945164_2_y_cfblk1_104538985_2=prop_2)) -> (cf'=stop_system);	// <-- 
	[compare0] (cf=compare0) & (redundancy_model41_cfblk1_0=v) & (x_cfblk1_1_677798203_2_y_cfblk1_104538985=prop_1) & (y_cfblk4_221945164_2_y_cfblk1_104538985_2=prop_1) -> (cf'=cfblk4_Output_3);	// <-- 
	[compare0] (cf=compare0) & (redundancy_model41_cfblk1_0=v) & ((x_cfblk1_1_677798203_2_y_cfblk1_104538985=prop_2) | (y_cfblk4_221945164_2_y_cfblk1_104538985_2=prop_2)) -> (cf'=cfblk1_Output_2_3);	// <-- 
	//Element stop_system, cf transitions ['cfblk5_Output_1']
	[stop_system] cf=stop_system -> 1.0:(cf'=cfblk5_Output_1);
	//Element check_redandancy1, df inputs ['redundancy_model41_cfblk4_1'], cf transitions ['cfblk4_Output_3_2', 'cfblk2_Output_4']
	[check_redandancy1] (cf=check_redandancy1) & (redundancy_model41_cfblk4_1=no) -> (cf'=cfblk2_Output_4);	// <-- 
	[check_redandancy1] (cf=check_redandancy1) & ((redundancy_model41_cfblk4_1=v)|(redundancy_model41_cfblk4_1=c)) -> (cf'=cfblk4_Output_3_2);	// <-- 
	//Element cfblk4_Output_3_2, df inputs ['x_cfblk1_1_677798203_2_y_cfblk1_104538985', 'y_cfblk3_182809771_2_y_cfblk5_261080557'], cf transitions ['compare1']
	[cfblk4_Output_3_2] cf=cfblk4_Output_3_2 -> 1.0:(cf'=compare1);
	//Element cfblk4_Output_3_3, df inputs ['x_cfblk1_1_677798203_2_y_cfblk1_104538985', 'y_cfblk3_182809771_2_y_cfblk5_261080557'], cf transitions ['cfblk2_Output_4']
	[cfblk4_Output_3_3] cf=cfblk4_Output_3_3 -> 1.0:(cf'=cfblk2_Output_4);
	//Element compare1, df inputs ['y_cfblk4_221945164_2_y_cfblk1_104538985_2', 'redundancy_model41_cfblk4_1', 'y_cfblk4_221945164'], cf transitions ['cfblk4_Output_3_3', 'cfblk2_Output_4', 'stop_system']
	[compare1] (cf=compare1) & (redundancy_model41_cfblk4_1=c) & (y_cfblk4_221945164=ok) & (y_cfblk4_221945164_2_y_cfblk1_104538985_2=prop_1) -> (cf'=cfblk2_Output_4);	// <-- 
	[compare1] (cf=compare1) & (redundancy_model41_cfblk4_1=c) & ((y_cfblk4_221945164=error) | (y_cfblk4_221945164_2_y_cfblk1_104538985_2=prop_2)) -> (cf'=stop_system);	// <-- 
	[compare1] (cf=compare1) & (redundancy_model41_cfblk4_1=v) & (y_cfblk4_221945164=ok) & (y_cfblk4_221945164_2_y_cfblk1_104538985_2=prop_1) -> (cf'=cfblk2_Output_4);	// <-- 
	[compare1] (cf=compare1) & (redundancy_model41_cfblk4_1=v) & ((y_cfblk4_221945164=error) | (y_cfblk4_221945164_2_y_cfblk1_104538985_2=prop_2)) -> (cf'=cfblk4_Output_3_3);	// <-- 
	//Element check_redandancy3, df inputs ['redundancy_model41_cfblk3_3'], cf transitions ['cfblk3_Output_5_2', 'cfblk5_Update_6']
	[check_redandancy3] (cf=check_redandancy3) & (redundancy_model41_cfblk3_3=no) -> (cf'=cfblk5_Update_6);	// <-- 
	[check_redandancy3] (cf=check_redandancy3) & ((redundancy_model41_cfblk3_3=v)|(redundancy_model41_cfblk3_3=c)) -> (cf'=cfblk3_Output_5_2);	// <-- 
	//Element cfblk3_Output_5_2, df inputs ['x_cfblk1_1_677798203_2_y_cfblk1_104538985', 'y_cfblk4_221945164'], cf transitions ['compare3']
	[cfblk3_Output_5_2] cf=cfblk3_Output_5_2 -> 1.0:(cf'=compare3);
	//Element cfblk3_Output_5_3, df inputs ['x_cfblk1_1_677798203_2_y_cfblk1_104538985', 'y_cfblk4_221945164'], cf transitions ['cfblk5_Update_6']
	[cfblk3_Output_5_3] cf=cfblk3_Output_5_3 -> 1.0:(cf'=cfblk5_Update_6);
	//Element compare3, df inputs ['y_cfblk3_182809771_2_y_cfblk5_261080557', 'redundancy_model41_cfblk3_3', 'y_cfblk3_182809771'], cf transitions ['cfblk3_Output_5_3', 'cfblk5_Update_6', 'stop_system']
	[compare3] (cf=compare3) & (redundancy_model41_cfblk3_3=c) & (y_cfblk3_182809771=ok) & (y_cfblk3_182809771_2_y_cfblk5_261080557=prop_1) -> (cf'=cfblk5_Update_6);	// <-- 
	[compare3] (cf=compare3) & (redundancy_model41_cfblk3_3=c) & ((y_cfblk3_182809771=error) | (y_cfblk3_182809771_2_y_cfblk5_261080557=prop_2)) -> (cf'=stop_system);	// <-- 
	[compare3] (cf=compare3) & (redundancy_model41_cfblk3_3=v) & (y_cfblk3_182809771=ok) & (y_cfblk3_182809771_2_y_cfblk5_261080557=prop_1) -> (cf'=cfblk5_Update_6);	// <-- 
	[compare3] (cf=compare3) & (redundancy_model41_cfblk3_3=v) & ((y_cfblk3_182809771=error) | (y_cfblk3_182809771_2_y_cfblk5_261080557=prop_2)) -> (cf'=cfblk3_Output_5_3);	// <-- 
	//Element check_redandancy4, df inputs ['redundancy_model41_cfblk1_0'], cf transitions ['cfblk1_Update_7_2', 'cfblk5_Output_1']
	[check_redandancy4] (cf=check_redandancy4) & (redundancy_model41_cfblk1_0=no) -> (cf'=cfblk5_Output_1);	// <-- 
	[check_redandancy4] (cf=check_redandancy4) & ((redundancy_model41_cfblk1_0=v)|(redundancy_model41_cfblk1_0=c)) -> (cf'=cfblk1_Update_7_2);	// <-- 
	//Element cfblk1_Update_7_2, df inputs ['x_cfblk1_1_677798203', 'y_cfblk3_182809771'], cf transitions ['compare4']
	[cfblk1_Update_7_2] cf=cfblk1_Update_7_2 -> 1.0:(cf'=compare4);
	//Element cfblk1_Update_7_3, df inputs ['x_cfblk1_1_677798203', 'y_cfblk3_182809771'], cf transitions ['cfblk5_Output_1']
	[cfblk1_Update_7_3] cf=cfblk1_Update_7_3 -> 1.0:(cf'=cfblk5_Output_1);
	//Element compare4, df inputs ['x_cfblk1_1_677798203_2_y_cfblk1_104538985', 'redundancy_model41_cfblk1_0', 'x_cfblk1_1_677798203'], cf transitions ['cfblk1_Update_7_3', 'cfblk5_Output_1', 'stop_system']
	[compare4] (cf=compare4) & (redundancy_model41_cfblk1_0=c) & (x_cfblk1_1_677798203=ok) & (x_cfblk1_1_677798203_2_y_cfblk1_104538985=prop_1) -> (cf'=cfblk5_Output_1);	// <-- 
	[compare4] (cf=compare4) & (redundancy_model41_cfblk1_0=c) & ((x_cfblk1_1_677798203=error) | (x_cfblk1_1_677798203_2_y_cfblk1_104538985=prop_2)) -> (cf'=stop_system);	// <-- 
	[compare4] (cf=compare4) & (redundancy_model41_cfblk1_0=v) & (x_cfblk1_1_677798203=ok) & (x_cfblk1_1_677798203_2_y_cfblk1_104538985=prop_1) -> (cf'=cfblk5_Output_1);	// <-- 
	[compare4] (cf=compare4) & (redundancy_model41_cfblk1_0=v) & ((x_cfblk1_1_677798203=error) | (x_cfblk1_1_677798203_2_y_cfblk1_104538985=prop_2)) -> (cf'=cfblk1_Update_7_3);	// <-- 
endmodule
//Error propagation commands
module error_propagation
	y_cfblk3_182809771 : [0 .. 6] init ok;
	y_cfblk4_221945164 : [0 .. 6] init ok;
	x_cfblk5_1_1548702784 : [0 .. 6] init ok;
	x_cfblk1_1_677798203 : [0 .. 6] init ok;
	redundancy_model41_cfblk1_0 : [0 .. 6] init no;
	redundancy_model41_cfblk4_1 : [0 .. 6] init no;
	redundancy_model41_cfblk3_3 : [0 .. 6] init v;
	y_cfblk4_221945164_2_y_cfblk1_104538985_2 : [0 .. 6] init prop_1;
	y_cfblk3_182809771_2_y_cfblk5_261080557 : [0 .. 6] init prop_1;
	x_cfblk1_1_677798203_2_y_cfblk1_104538985 : [0 .. 6] init prop_1;
	//Element cfblk5_Output_1, df inputs ['x_cfblk5_1_1548702784', 'y_cfblk4_221945164'], df outputs ['y_cfblk3_182809771_2_y_cfblk5_261080557']
	[cfblk5_Output_1] (y_cfblk4_221945164=ok) & (x_cfblk5_1_1548702784=ok) -> 0.98:(y_cfblk3_182809771_2_y_cfblk5_261080557'=prop_1) + 0.02:(y_cfblk3_182809771_2_y_cfblk5_261080557'=prop_2);	// <-- 
	[cfblk5_Output_1] (y_cfblk4_221945164!=ok) | (x_cfblk5_1_1548702784!=ok) -> (y_cfblk3_182809771_2_y_cfblk5_261080557'=prop_2);	// <-- 
	//Element cfblk1_Output_2, df inputs ['x_cfblk1_1_677798203', 'y_cfblk3_182809771'], df outputs ['x_cfblk1_1_677798203_2_y_cfblk1_104538985']
	[cfblk1_Output_2] (y_cfblk3_182809771=ok) & (x_cfblk1_1_677798203=ok) -> 0.98:(x_cfblk1_1_677798203_2_y_cfblk1_104538985'=prop_1) + 0.02:(x_cfblk1_1_677798203_2_y_cfblk1_104538985'=prop_2);	// <-- 
	[cfblk1_Output_2] (y_cfblk3_182809771!=ok) | (x_cfblk1_1_677798203!=ok) -> (x_cfblk1_1_677798203_2_y_cfblk1_104538985'=prop_2);	// <-- 
	//Element cfblk4_Output_3, df inputs ['x_cfblk1_1_677798203_2_y_cfblk1_104538985', 'y_cfblk3_182809771_2_y_cfblk5_261080557'], df outputs ['y_cfblk4_221945164']
	[cfblk4_Output_3] (x_cfblk1_1_677798203_2_y_cfblk1_104538985=prop_1) & (y_cfblk3_182809771_2_y_cfblk5_261080557=prop_1) -> 0.974002239936:(y_cfblk4_221945164'=ok) + 0.025997760064:(y_cfblk4_221945164'=error);	// <-- 
	[cfblk4_Output_3] (x_cfblk1_1_677798203_2_y_cfblk1_104538985!=prop_1) | (y_cfblk3_182809771_2_y_cfblk5_261080557!=prop_1) -> (y_cfblk4_221945164'=error);	// <-- 
	//Element cfblk3_Output_5, df inputs ['x_cfblk1_1_677798203_2_y_cfblk1_104538985', 'y_cfblk4_221945164'], df outputs ['y_cfblk3_182809771']
	[cfblk3_Output_5] (x_cfblk1_1_677798203_2_y_cfblk1_104538985=prop_1) & (y_cfblk4_221945164=ok) -> 0.974002239936:(y_cfblk3_182809771'=ok) + 0.025997760064:(y_cfblk3_182809771'=error);	// <-- 
	[cfblk3_Output_5] (x_cfblk1_1_677798203_2_y_cfblk1_104538985!=prop_1) | (y_cfblk4_221945164!=ok) -> (y_cfblk3_182809771'=error);	// <-- 
	//Element cfblk5_Update_6, df inputs ['x_cfblk5_1_1548702784', 'y_cfblk4_221945164'], df outputs ['x_cfblk5_1_1548702784']
	[cfblk5_Update_6] (y_cfblk4_221945164=ok) & (x_cfblk5_1_1548702784=ok) -> 0.98:(x_cfblk5_1_1548702784'=ok) + 0.02:(x_cfblk5_1_1548702784'=error);	// <-- 
	[cfblk5_Update_6] (y_cfblk4_221945164!=ok) | (x_cfblk5_1_1548702784!=ok) -> (x_cfblk5_1_1548702784'=error);	// <-- 
	//Element cfblk1_Update_7, df inputs ['x_cfblk1_1_677798203', 'y_cfblk3_182809771'], df outputs ['x_cfblk1_1_677798203']
	[cfblk1_Update_7] (y_cfblk3_182809771=ok) & (x_cfblk1_1_677798203=ok) -> 0.98:(x_cfblk1_1_677798203'=ok) + 0.02:(x_cfblk1_1_677798203'=error);	// <-- 
	[cfblk1_Update_7] (y_cfblk3_182809771!=ok) | (x_cfblk1_1_677798203!=ok) -> (x_cfblk1_1_677798203'=error);	// <-- 
	//Element cfblk1_Output_2_2, df inputs ['x_cfblk1_1_677798203', 'y_cfblk3_182809771'], df outputs ['y_cfblk4_221945164_2_y_cfblk1_104538985_2']
	[cfblk1_Output_2_2] (y_cfblk3_182809771=ok) & (x_cfblk1_1_677798203=ok) -> 0.98:(y_cfblk4_221945164_2_y_cfblk1_104538985_2'=prop_1) + 0.02:(y_cfblk4_221945164_2_y_cfblk1_104538985_2'=prop_2);	// <-- 
	[cfblk1_Output_2_2] (y_cfblk3_182809771!=ok) | (x_cfblk1_1_677798203!=ok) -> (y_cfblk4_221945164_2_y_cfblk1_104538985_2'=prop_2);	// <-- 
	//Element cfblk1_Output_2_3, df inputs ['x_cfblk1_1_677798203', 'y_cfblk3_182809771'], df outputs ['x_cfblk1_1_677798203_2_y_cfblk1_104538985']
	[cfblk1_Output_2_3] (y_cfblk3_182809771=ok) & (x_cfblk1_1_677798203=ok) -> 0.98:(x_cfblk1_1_677798203_2_y_cfblk1_104538985'=prop_1) + 0.02:(x_cfblk1_1_677798203_2_y_cfblk1_104538985'=prop_2);	// <-- 
	[cfblk1_Output_2_3] (y_cfblk3_182809771!=ok) | (x_cfblk1_1_677798203!=ok) -> (x_cfblk1_1_677798203_2_y_cfblk1_104538985'=prop_2);	// <-- 
	//Element cfblk4_Output_3_2, df inputs ['x_cfblk1_1_677798203_2_y_cfblk1_104538985', 'y_cfblk3_182809771_2_y_cfblk5_261080557'], df outputs ['y_cfblk4_221945164_2_y_cfblk1_104538985_2']
	[cfblk4_Output_3_2] (x_cfblk1_1_677798203_2_y_cfblk1_104538985=prop_1) & (y_cfblk3_182809771_2_y_cfblk5_261080557=prop_1) -> 0.974002239936:(y_cfblk4_221945164_2_y_cfblk1_104538985_2'=prop_1) + 0.025997760064:(y_cfblk4_221945164_2_y_cfblk1_104538985_2'=prop_2);	// <-- 
	[cfblk4_Output_3_2] (x_cfblk1_1_677798203_2_y_cfblk1_104538985!=prop_1) | (y_cfblk3_182809771_2_y_cfblk5_261080557!=prop_1) -> (y_cfblk4_221945164_2_y_cfblk1_104538985_2'=prop_2);	// <-- 
	//Element cfblk4_Output_3_3, df inputs ['x_cfblk1_1_677798203_2_y_cfblk1_104538985', 'y_cfblk3_182809771_2_y_cfblk5_261080557'], df outputs ['y_cfblk4_221945164']
	[cfblk4_Output_3_3] (x_cfblk1_1_677798203_2_y_cfblk1_104538985=prop_1) & (y_cfblk3_182809771_2_y_cfblk5_261080557=prop_1) -> 0.974002239936:(y_cfblk4_221945164'=ok) + 0.025997760064:(y_cfblk4_221945164'=error);	// <-- 
	[cfblk4_Output_3_3] (x_cfblk1_1_677798203_2_y_cfblk1_104538985!=prop_1) | (y_cfblk3_182809771_2_y_cfblk5_261080557!=prop_1) -> (y_cfblk4_221945164'=error);	// <-- 
	//Element cfblk3_Output_5_2, df inputs ['x_cfblk1_1_677798203_2_y_cfblk1_104538985', 'y_cfblk4_221945164'], df outputs ['y_cfblk3_182809771_2_y_cfblk5_261080557']
	[cfblk3_Output_5_2] (x_cfblk1_1_677798203_2_y_cfblk1_104538985=prop_1) & (y_cfblk4_221945164=ok) -> 0.974002239936:(y_cfblk3_182809771_2_y_cfblk5_261080557'=prop_1) + 0.025997760064:(y_cfblk3_182809771_2_y_cfblk5_261080557'=prop_2);	// <-- 
	[cfblk3_Output_5_2] (x_cfblk1_1_677798203_2_y_cfblk1_104538985!=prop_1) | (y_cfblk4_221945164!=ok) -> (y_cfblk3_182809771_2_y_cfblk5_261080557'=prop_2);	// <-- 
	//Element cfblk3_Output_5_3, df inputs ['x_cfblk1_1_677798203_2_y_cfblk1_104538985', 'y_cfblk4_221945164'], df outputs ['y_cfblk3_182809771']
	[cfblk3_Output_5_3] (x_cfblk1_1_677798203_2_y_cfblk1_104538985=prop_1) & (y_cfblk4_221945164=ok) -> 0.974002239936:(y_cfblk3_182809771'=ok) + 0.025997760064:(y_cfblk3_182809771'=error);	// <-- 
	[cfblk3_Output_5_3] (x_cfblk1_1_677798203_2_y_cfblk1_104538985!=prop_1) | (y_cfblk4_221945164!=ok) -> (y_cfblk3_182809771'=error);	// <-- 
	//Element cfblk1_Update_7_2, df inputs ['x_cfblk1_1_677798203', 'y_cfblk3_182809771'], df outputs ['x_cfblk1_1_677798203_2_y_cfblk1_104538985']
	[cfblk1_Update_7_2] (y_cfblk3_182809771=ok) & (x_cfblk1_1_677798203=ok) -> 0.98:(x_cfblk1_1_677798203_2_y_cfblk1_104538985'=prop_1) + 0.02:(x_cfblk1_1_677798203_2_y_cfblk1_104538985'=prop_2);	// <-- 
	[cfblk1_Update_7_2] (y_cfblk3_182809771!=ok) | (x_cfblk1_1_677798203!=ok) -> (x_cfblk1_1_677798203_2_y_cfblk1_104538985'=prop_2);	// <-- 
	//Element cfblk1_Update_7_3, df inputs ['x_cfblk1_1_677798203', 'y_cfblk3_182809771'], df outputs ['x_cfblk1_1_677798203']
	[cfblk1_Update_7_3] (y_cfblk3_182809771=ok) & (x_cfblk1_1_677798203=ok) -> 0.98:(x_cfblk1_1_677798203'=ok) + 0.02:(x_cfblk1_1_677798203'=error);	// <-- 
	[cfblk1_Update_7_3] (y_cfblk3_182809771!=ok) | (x_cfblk1_1_677798203!=ok) -> (x_cfblk1_1_677798203'=error);	// <-- 
endmodule

//Failure formulas
formula failure = x_cfblk1_1_677798203 = error;

rewards "time" true : 1; endrewards
