//Generated by ErrorPro
dtmc
//Element consts
const int cfblk5_Output_1=0;
const int cfblk1_Output_2=1;
const int cfblk2_Output_3=2;
const int cfblk4_Output_4=3;
const int cfblk3_Output_5=4;
const int cfblk5_Update_6=5;
const int check_redandancy1=6;
const int cfblk2_Output_3_2=7;
const int cfblk2_Output_3_3=8;
const int compare1=9;
const int stop_system=10;
const int check_redandancy2=11;
const int cfblk4_Output_4_2=12;
const int cfblk4_Output_4_3=13;
const int compare2=14;
const int check_redandancy3=15;
const int cfblk3_Output_5_2=16;
const int cfblk3_Output_5_3=17;
const int compare3=18;
//Data values consts
const int v=0;
const int prop_2=1;
const int prop_1=2;
const int ok=3;
const int no=4;
const int error=5;
const int c=6;
//Control flow commands
module control_flow
	cf:[0..19] init cfblk5_Output_1;
	//Element cfblk5_Output_1, df inputs ['x_cfblk5_1_80151913', 'y_cfblk3_919211374'], cf transitions ['cfblk1_Output_2']
	[cfblk5_Output_1] cf=cfblk5_Output_1 -> 1.0:(cf'=cfblk1_Output_2);
	//Element cfblk1_Output_2, df inputs ['y_cfblk5_997482160_y_cfblk2_880075981'], cf transitions ['cfblk2_Output_3']
	[cfblk1_Output_2] cf=cfblk1_Output_2 -> 1.0:(cf'=cfblk2_Output_3);
	//Element cfblk2_Output_3, cf transitions ['check_redandancy1']
	[cfblk2_Output_3] cf=cfblk2_Output_3 -> 1.0:(cf'=check_redandancy1);
	//Element cfblk4_Output_4, df inputs ['y_cfblk5_997482160_y_cfblk2_880075981'], cf transitions ['check_redandancy2']
	[cfblk4_Output_4] cf=cfblk4_Output_4 -> 1.0:(cf'=check_redandancy2);
	//Element cfblk3_Output_5, df inputs ['y_cfblk2_880075981_2_y_cfblk4_958346767', 'y_cfblk5_997482160_y_cfblk2_880075981'], cf transitions ['check_redandancy3']
	[cfblk3_Output_5] cf=cfblk3_Output_5 -> 1.0:(cf'=check_redandancy3);
	//Element cfblk5_Update_6, df inputs ['x_cfblk5_1_80151913', 'y_cfblk3_919211374'], cf transitions ['cfblk5_Output_1']
	[cfblk5_Update_6] cf=cfblk5_Update_6 -> 1.0:(cf'=cfblk5_Output_1);
	//Element check_redandancy1, df inputs ['redundancy_model25_cfblk2_1'], cf transitions ['cfblk2_Output_3_2', 'cfblk4_Output_4']
	[check_redandancy1] (cf=check_redandancy1) & (redundancy_model25_cfblk2_1=no) -> (cf'=cfblk4_Output_4);	// <-- 
	[check_redandancy1] (cf=check_redandancy1) & ((redundancy_model25_cfblk2_1=v)|(redundancy_model25_cfblk2_1=c)) -> (cf'=cfblk2_Output_3_2);	// <-- 
	//Element cfblk2_Output_3_2, cf transitions ['compare1']
	[cfblk2_Output_3_2] cf=cfblk2_Output_3_2 -> 1.0:(cf'=compare1);
	//Element cfblk2_Output_3_3, cf transitions ['cfblk4_Output_4']
	[cfblk2_Output_3_3] cf=cfblk2_Output_3_3 -> 1.0:(cf'=cfblk4_Output_4);
	//Element compare1, df inputs ['y_cfblk5_997482160_y_cfblk2_880075981', 'y_cfblk2_880075981_2_y_cfblk4_958346767', 'redundancy_model25_cfblk2_1'], cf transitions ['cfblk2_Output_3_3', 'cfblk4_Output_4', 'stop_system']
	[compare1] (cf=compare1) & (redundancy_model25_cfblk2_1=c) & (y_cfblk5_997482160_y_cfblk2_880075981=prop_1) & (y_cfblk2_880075981_2_y_cfblk4_958346767=prop_1) -> (cf'=cfblk4_Output_4);	// <-- 
	[compare1] (cf=compare1) & (redundancy_model25_cfblk2_1=c) & ((y_cfblk5_997482160_y_cfblk2_880075981=prop_2) | (y_cfblk2_880075981_2_y_cfblk4_958346767=prop_2)) -> (cf'=stop_system);	// <-- 
	[compare1] (cf=compare1) & (redundancy_model25_cfblk2_1=v) & (y_cfblk5_997482160_y_cfblk2_880075981=prop_1) & (y_cfblk2_880075981_2_y_cfblk4_958346767=prop_1) -> (cf'=cfblk4_Output_4);	// <-- 
	[compare1] (cf=compare1) & (redundancy_model25_cfblk2_1=v) & ((y_cfblk5_997482160_y_cfblk2_880075981=prop_2) | (y_cfblk2_880075981_2_y_cfblk4_958346767=prop_2)) -> (cf'=cfblk2_Output_3_3);	// <-- 
	//Element stop_system, cf transitions ['cfblk5_Output_1']
	[stop_system] cf=stop_system -> 1.0:(cf'=cfblk5_Output_1);
	//Element check_redandancy2, df inputs ['redundancy_model25_cfblk4_2'], cf transitions ['cfblk4_Output_4_2', 'cfblk3_Output_5']
	[check_redandancy2] (cf=check_redandancy2) & (redundancy_model25_cfblk4_2=no) -> (cf'=cfblk3_Output_5);	// <-- 
	[check_redandancy2] (cf=check_redandancy2) & ((redundancy_model25_cfblk4_2=v)|(redundancy_model25_cfblk4_2=c)) -> (cf'=cfblk4_Output_4_2);	// <-- 
	//Element cfblk4_Output_4_2, df inputs ['y_cfblk5_997482160_y_cfblk2_880075981'], cf transitions ['compare2']
	[cfblk4_Output_4_2] cf=cfblk4_Output_4_2 -> 1.0:(cf'=compare2);
	//Element cfblk4_Output_4_3, df inputs ['y_cfblk5_997482160_y_cfblk2_880075981'], cf transitions ['cfblk3_Output_5']
	[cfblk4_Output_4_3] cf=cfblk4_Output_4_3 -> 1.0:(cf'=cfblk3_Output_5);
	//Element compare2, df inputs ['y_cfblk3_919211374_2_y_cfblk4_958346767_2', 'y_cfblk2_880075981_2_y_cfblk4_958346767', 'redundancy_model25_cfblk4_2'], cf transitions ['cfblk4_Output_4_3', 'cfblk3_Output_5', 'stop_system']
	[compare2] (cf=compare2) & (redundancy_model25_cfblk4_2=c) & (y_cfblk2_880075981_2_y_cfblk4_958346767=prop_1) & (y_cfblk3_919211374_2_y_cfblk4_958346767_2=prop_1) -> (cf'=cfblk3_Output_5);	// <-- 
	[compare2] (cf=compare2) & (redundancy_model25_cfblk4_2=c) & ((y_cfblk2_880075981_2_y_cfblk4_958346767=prop_2) | (y_cfblk3_919211374_2_y_cfblk4_958346767_2=prop_2)) -> (cf'=stop_system);	// <-- 
	[compare2] (cf=compare2) & (redundancy_model25_cfblk4_2=v) & (y_cfblk2_880075981_2_y_cfblk4_958346767=prop_1) & (y_cfblk3_919211374_2_y_cfblk4_958346767_2=prop_1) -> (cf'=cfblk3_Output_5);	// <-- 
	[compare2] (cf=compare2) & (redundancy_model25_cfblk4_2=v) & ((y_cfblk2_880075981_2_y_cfblk4_958346767=prop_2) | (y_cfblk3_919211374_2_y_cfblk4_958346767_2=prop_2)) -> (cf'=cfblk4_Output_4_3);	// <-- 
	//Element check_redandancy3, df inputs ['redundancy_model25_cfblk3_3'], cf transitions ['cfblk3_Output_5_2', 'cfblk5_Update_6']
	[check_redandancy3] (cf=check_redandancy3) & (redundancy_model25_cfblk3_3=no) -> (cf'=cfblk5_Update_6);	// <-- 
	[check_redandancy3] (cf=check_redandancy3) & ((redundancy_model25_cfblk3_3=v)|(redundancy_model25_cfblk3_3=c)) -> (cf'=cfblk3_Output_5_2);	// <-- 
	//Element cfblk3_Output_5_2, df inputs ['y_cfblk2_880075981_2_y_cfblk4_958346767', 'y_cfblk5_997482160_y_cfblk2_880075981'], cf transitions ['compare3']
	[cfblk3_Output_5_2] cf=cfblk3_Output_5_2 -> 1.0:(cf'=compare3);
	//Element cfblk3_Output_5_3, df inputs ['y_cfblk2_880075981_2_y_cfblk4_958346767', 'y_cfblk5_997482160_y_cfblk2_880075981'], cf transitions ['cfblk5_Update_6']
	[cfblk3_Output_5_3] cf=cfblk3_Output_5_3 -> 1.0:(cf'=cfblk5_Update_6);
	//Element compare3, df inputs ['redundancy_model25_cfblk3_3', 'y_cfblk3_919211374', 'y_cfblk3_919211374_2_y_cfblk4_958346767_2'], cf transitions ['cfblk3_Output_5_3', 'cfblk5_Update_6', 'stop_system']
	[compare3] (cf=compare3) & (redundancy_model25_cfblk3_3=c) & (y_cfblk3_919211374=ok) & (y_cfblk3_919211374_2_y_cfblk4_958346767_2=prop_1) -> (cf'=cfblk5_Update_6);	// <-- 
	[compare3] (cf=compare3) & (redundancy_model25_cfblk3_3=c) & ((y_cfblk3_919211374=error) | (y_cfblk3_919211374_2_y_cfblk4_958346767_2=prop_2)) -> (cf'=stop_system);	// <-- 
	[compare3] (cf=compare3) & (redundancy_model25_cfblk3_3=v) & (y_cfblk3_919211374=ok) & (y_cfblk3_919211374_2_y_cfblk4_958346767_2=prop_1) -> (cf'=cfblk5_Update_6);	// <-- 
	[compare3] (cf=compare3) & (redundancy_model25_cfblk3_3=v) & ((y_cfblk3_919211374=error) | (y_cfblk3_919211374_2_y_cfblk4_958346767_2=prop_2)) -> (cf'=cfblk3_Output_5_3);	// <-- 
endmodule
//Error propagation commands
module error_propagation
	y_cfblk3_919211374 : [0 .. 6] init ok;
	x_cfblk5_1_80151913 : [0 .. 6] init ok;
	redundancy_model25_cfblk2_1 : [0 .. 6] init v;
	redundancy_model25_cfblk4_2 : [0 .. 6] init v;
	redundancy_model25_cfblk3_3 : [0 .. 6] init no;
	y_cfblk3_919211374_2_y_cfblk4_958346767_2 : [0 .. 6] init prop_1;
	y_cfblk2_880075981_2_y_cfblk4_958346767 : [0 .. 6] init prop_1;
	y_cfblk5_997482160_y_cfblk2_880075981 : [0 .. 6] init prop_1;
	//Element cfblk5_Output_1, df inputs ['x_cfblk5_1_80151913', 'y_cfblk3_919211374'], df outputs ['y_cfblk5_997482160_y_cfblk2_880075981']
	[cfblk5_Output_1] (y_cfblk3_919211374=ok) & (x_cfblk5_1_80151913=ok) -> 0.98:(y_cfblk5_997482160_y_cfblk2_880075981'=prop_1) + 0.02:(y_cfblk5_997482160_y_cfblk2_880075981'=prop_2);	// <-- 
	[cfblk5_Output_1] (y_cfblk3_919211374!=ok) | (x_cfblk5_1_80151913!=ok) -> (y_cfblk5_997482160_y_cfblk2_880075981'=prop_2);	// <-- 
	//Element cfblk2_Output_3, df outputs ['y_cfblk5_997482160_y_cfblk2_880075981']
	[cfblk2_Output_3] (true) -> 1:(y_cfblk5_997482160_y_cfblk2_880075981'=prop_1);	// <-- 
	//Element cfblk4_Output_4, df inputs ['y_cfblk5_997482160_y_cfblk2_880075981'], df outputs ['y_cfblk2_880075981_2_y_cfblk4_958346767']
	[cfblk4_Output_4] (y_cfblk5_997482160_y_cfblk2_880075981=prop_1) -> 0.969003039904:(y_cfblk2_880075981_2_y_cfblk4_958346767'=prop_1) + 0.030996960095999997:(y_cfblk2_880075981_2_y_cfblk4_958346767'=prop_2);	// <-- 
	[cfblk4_Output_4] (y_cfblk5_997482160_y_cfblk2_880075981!=prop_1) -> (y_cfblk2_880075981_2_y_cfblk4_958346767'=prop_2);	// <-- 
	//Element cfblk3_Output_5, df inputs ['y_cfblk2_880075981_2_y_cfblk4_958346767', 'y_cfblk5_997482160_y_cfblk2_880075981'], df outputs ['y_cfblk3_919211374']
	[cfblk3_Output_5] (y_cfblk5_997482160_y_cfblk2_880075981=prop_1) & (y_cfblk2_880075981_2_y_cfblk4_958346767=prop_1) -> 0.974002239936:(y_cfblk3_919211374'=ok) + 0.025997760064:(y_cfblk3_919211374'=error);	// <-- 
	[cfblk3_Output_5] (y_cfblk5_997482160_y_cfblk2_880075981!=prop_1) | (y_cfblk2_880075981_2_y_cfblk4_958346767!=prop_1) -> (y_cfblk3_919211374'=error);	// <-- 
	//Element cfblk5_Update_6, df inputs ['x_cfblk5_1_80151913', 'y_cfblk3_919211374'], df outputs ['x_cfblk5_1_80151913']
	[cfblk5_Update_6] (y_cfblk3_919211374=ok) & (x_cfblk5_1_80151913=ok) -> 0.98:(x_cfblk5_1_80151913'=ok) + 0.02:(x_cfblk5_1_80151913'=error);	// <-- 
	[cfblk5_Update_6] (y_cfblk3_919211374!=ok) | (x_cfblk5_1_80151913!=ok) -> (x_cfblk5_1_80151913'=error);	// <-- 
	//Element cfblk2_Output_3_2, df outputs ['y_cfblk2_880075981_2_y_cfblk4_958346767']
	[cfblk2_Output_3_2] (true) -> 1:(y_cfblk2_880075981_2_y_cfblk4_958346767'=prop_1);	// <-- 
	//Element cfblk2_Output_3_3, df outputs ['y_cfblk5_997482160_y_cfblk2_880075981']
	[cfblk2_Output_3_3] (true) -> 1:(y_cfblk5_997482160_y_cfblk2_880075981'=prop_1);	// <-- 
	//Element cfblk4_Output_4_2, df inputs ['y_cfblk5_997482160_y_cfblk2_880075981'], df outputs ['y_cfblk3_919211374_2_y_cfblk4_958346767_2']
	[cfblk4_Output_4_2] (y_cfblk5_997482160_y_cfblk2_880075981=prop_1) -> 0.969003039904:(y_cfblk3_919211374_2_y_cfblk4_958346767_2'=prop_1) + 0.030996960095999997:(y_cfblk3_919211374_2_y_cfblk4_958346767_2'=prop_2);	// <-- 
	[cfblk4_Output_4_2] (y_cfblk5_997482160_y_cfblk2_880075981!=prop_1) -> (y_cfblk3_919211374_2_y_cfblk4_958346767_2'=prop_2);	// <-- 
	//Element cfblk4_Output_4_3, df inputs ['y_cfblk5_997482160_y_cfblk2_880075981'], df outputs ['y_cfblk2_880075981_2_y_cfblk4_958346767']
	[cfblk4_Output_4_3] (y_cfblk5_997482160_y_cfblk2_880075981=prop_1) -> 0.969003039904:(y_cfblk2_880075981_2_y_cfblk4_958346767'=prop_1) + 0.030996960095999997:(y_cfblk2_880075981_2_y_cfblk4_958346767'=prop_2);	// <-- 
	[cfblk4_Output_4_3] (y_cfblk5_997482160_y_cfblk2_880075981!=prop_1) -> (y_cfblk2_880075981_2_y_cfblk4_958346767'=prop_2);	// <-- 
	//Element cfblk3_Output_5_2, df inputs ['y_cfblk2_880075981_2_y_cfblk4_958346767', 'y_cfblk5_997482160_y_cfblk2_880075981'], df outputs ['y_cfblk3_919211374_2_y_cfblk4_958346767_2']
	[cfblk3_Output_5_2] (y_cfblk5_997482160_y_cfblk2_880075981=prop_1) & (y_cfblk2_880075981_2_y_cfblk4_958346767=prop_1) -> 0.974002239936:(y_cfblk3_919211374_2_y_cfblk4_958346767_2'=prop_1) + 0.025997760064:(y_cfblk3_919211374_2_y_cfblk4_958346767_2'=prop_2);	// <-- 
	[cfblk3_Output_5_2] (y_cfblk5_997482160_y_cfblk2_880075981!=prop_1) | (y_cfblk2_880075981_2_y_cfblk4_958346767!=prop_1) -> (y_cfblk3_919211374_2_y_cfblk4_958346767_2'=prop_2);	// <-- 
	//Element cfblk3_Output_5_3, df inputs ['y_cfblk2_880075981_2_y_cfblk4_958346767', 'y_cfblk5_997482160_y_cfblk2_880075981'], df outputs ['y_cfblk3_919211374']
	[cfblk3_Output_5_3] (y_cfblk5_997482160_y_cfblk2_880075981=prop_1) & (y_cfblk2_880075981_2_y_cfblk4_958346767=prop_1) -> 0.974002239936:(y_cfblk3_919211374'=ok) + 0.025997760064:(y_cfblk3_919211374'=error);	// <-- 
	[cfblk3_Output_5_3] (y_cfblk5_997482160_y_cfblk2_880075981!=prop_1) | (y_cfblk2_880075981_2_y_cfblk4_958346767!=prop_1) -> (y_cfblk3_919211374'=error);	// <-- 
endmodule

//Failure formulas
formula failure = x_cfblk5_1_80151913 = error;

rewards "time" true : 1; endrewards
