//Generated by ErrorPro
dtmc
//Element consts
const int cfblk1_Output_1=0;
const int cfblk2_Output_2=1;
const int cfblk3_Output_3=2;
const int cfblk5_Output_4=3;
const int cfblk4_Output_5=4;
const int cfblk1_Update_6=5;
const int check_redandancy0=6;
const int cfblk1_Output_1_2=7;
const int cfblk1_Output_1_3=8;
const int compare0=9;
const int stop_system=10;
const int check_redandancy1=11;
const int cfblk2_Output_2_2=12;
const int cfblk2_Output_2_3=13;
const int compare1=14;
const int check_redandancy2=15;
const int cfblk3_Output_3_2=16;
const int cfblk3_Output_3_3=17;
const int compare2=18;
const int check_redandancy3=19;
const int cfblk4_Output_5_2=20;
const int cfblk4_Output_5_3=21;
const int compare3=22;
const int check_redandancy4=23;
const int cfblk1_Update_6_2=24;
const int cfblk1_Update_6_3=25;
const int compare4=26;
//Data values consts
const int v=0;
const int prop_2=1;
const int prop_1=2;
const int ok=3;
const int no=4;
const int error=5;
const int c=6;
//Control flow commands
module control_flow
	cf:[0..27] init cfblk1_Output_1;
	//Element cfblk1_Output_1, df inputs ['y_cfblk4_231831604', 'x_cfblk1_1_1004050723'], cf transitions ['check_redandancy0']
	[cfblk1_Output_1] cf=cfblk1_Output_1 -> 1.0:(cf'=check_redandancy0);
	//Element cfblk2_Output_2, cf transitions ['check_redandancy1']
	[cfblk2_Output_2] cf=cfblk2_Output_2 -> 1.0:(cf'=check_redandancy1);
	//Element cfblk3_Output_3, df inputs ['y_cfblk5_270966997_y_cfblk1_114425425'], cf transitions ['check_redandancy2']
	[cfblk3_Output_3] cf=cfblk3_Output_3 -> 1.0:(cf'=check_redandancy2);
	//Element cfblk5_Output_4, df inputs ['y_cfblk4_231831604_2_y_cfblk2_153560818_2_y_cfblk3_192696211'], cf transitions ['cfblk4_Output_5']
	[cfblk5_Output_4] cf=cfblk5_Output_4 -> 1.0:(cf'=cfblk4_Output_5);
	//Element cfblk4_Output_5, df inputs ['x_cfblk1_1_1004050723_2_y_cfblk1_114425425_2_y_cfblk2_153560818', 'y_cfblk5_270966997_y_cfblk1_114425425'], cf transitions ['check_redandancy3']
	[cfblk4_Output_5] cf=cfblk4_Output_5 -> 1.0:(cf'=check_redandancy3);
	//Element cfblk1_Update_6, df inputs ['y_cfblk4_231831604', 'x_cfblk1_1_1004050723'], cf transitions ['check_redandancy4']
	[cfblk1_Update_6] cf=cfblk1_Update_6 -> 1.0:(cf'=check_redandancy4);
	//Element check_redandancy0, df inputs ['redundancy_model46_cfblk1_0'], cf transitions ['cfblk1_Output_1_2', 'cfblk2_Output_2']
	[check_redandancy0] (cf=check_redandancy0) & (redundancy_model46_cfblk1_0=no) -> (cf'=cfblk2_Output_2);	// <-- 
	[check_redandancy0] (cf=check_redandancy0) & ((redundancy_model46_cfblk1_0=v)|(redundancy_model46_cfblk1_0=c)) -> (cf'=cfblk1_Output_1_2);	// <-- 
	//Element cfblk1_Output_1_2, df inputs ['y_cfblk4_231831604', 'x_cfblk1_1_1004050723'], cf transitions ['compare0']
	[cfblk1_Output_1_2] cf=cfblk1_Output_1_2 -> 1.0:(cf'=compare0);
	//Element cfblk1_Output_1_3, df inputs ['y_cfblk4_231831604', 'x_cfblk1_1_1004050723'], cf transitions ['cfblk2_Output_2']
	[cfblk1_Output_1_3] cf=cfblk1_Output_1_3 -> 1.0:(cf'=cfblk2_Output_2);
	//Element compare0, df inputs ['y_cfblk5_270966997_y_cfblk1_114425425', 'x_cfblk1_1_1004050723_2_y_cfblk1_114425425_2_y_cfblk2_153560818', 'redundancy_model46_cfblk1_0'], cf transitions ['cfblk1_Output_1_3', 'cfblk2_Output_2', 'stop_system']
	[compare0] (cf=compare0) & (redundancy_model46_cfblk1_0=c) & (y_cfblk5_270966997_y_cfblk1_114425425=prop_1) & (x_cfblk1_1_1004050723_2_y_cfblk1_114425425_2_y_cfblk2_153560818=prop_1) -> (cf'=cfblk2_Output_2);	// <-- 
	[compare0] (cf=compare0) & (redundancy_model46_cfblk1_0=c) & ((y_cfblk5_270966997_y_cfblk1_114425425=prop_2) | (x_cfblk1_1_1004050723_2_y_cfblk1_114425425_2_y_cfblk2_153560818=prop_2)) -> (cf'=stop_system);	// <-- 
	[compare0] (cf=compare0) & (redundancy_model46_cfblk1_0=v) & (y_cfblk5_270966997_y_cfblk1_114425425=prop_1) & (x_cfblk1_1_1004050723_2_y_cfblk1_114425425_2_y_cfblk2_153560818=prop_1) -> (cf'=cfblk2_Output_2);	// <-- 
	[compare0] (cf=compare0) & (redundancy_model46_cfblk1_0=v) & ((y_cfblk5_270966997_y_cfblk1_114425425=prop_2) | (x_cfblk1_1_1004050723_2_y_cfblk1_114425425_2_y_cfblk2_153560818=prop_2)) -> (cf'=cfblk1_Output_1_3);	// <-- 
	//Element stop_system, cf transitions ['cfblk1_Output_1']
	[stop_system] cf=stop_system -> 1.0:(cf'=cfblk1_Output_1);
	//Element check_redandancy1, df inputs ['redundancy_model46_cfblk2_1'], cf transitions ['cfblk2_Output_2_2', 'cfblk3_Output_3']
	[check_redandancy1] (cf=check_redandancy1) & (redundancy_model46_cfblk2_1=no) -> (cf'=cfblk3_Output_3);	// <-- 
	[check_redandancy1] (cf=check_redandancy1) & ((redundancy_model46_cfblk2_1=v)|(redundancy_model46_cfblk2_1=c)) -> (cf'=cfblk2_Output_2_2);	// <-- 
	//Element cfblk2_Output_2_2, cf transitions ['compare1']
	[cfblk2_Output_2_2] cf=cfblk2_Output_2_2 -> 1.0:(cf'=compare1);
	//Element cfblk2_Output_2_3, cf transitions ['cfblk3_Output_3']
	[cfblk2_Output_2_3] cf=cfblk2_Output_2_3 -> 1.0:(cf'=cfblk3_Output_3);
	//Element compare1, df inputs ['y_cfblk4_231831604_2_y_cfblk2_153560818_2_y_cfblk3_192696211', 'x_cfblk1_1_1004050723_2_y_cfblk1_114425425_2_y_cfblk2_153560818', 'redundancy_model46_cfblk2_1'], cf transitions ['cfblk2_Output_2_3', 'cfblk3_Output_3', 'stop_system']
	[compare1] (cf=compare1) & (redundancy_model46_cfblk2_1=c) & (x_cfblk1_1_1004050723_2_y_cfblk1_114425425_2_y_cfblk2_153560818=prop_1) & (y_cfblk4_231831604_2_y_cfblk2_153560818_2_y_cfblk3_192696211=prop_1) -> (cf'=cfblk3_Output_3);	// <-- 
	[compare1] (cf=compare1) & (redundancy_model46_cfblk2_1=c) & ((x_cfblk1_1_1004050723_2_y_cfblk1_114425425_2_y_cfblk2_153560818=prop_2) | (y_cfblk4_231831604_2_y_cfblk2_153560818_2_y_cfblk3_192696211=prop_2)) -> (cf'=stop_system);	// <-- 
	[compare1] (cf=compare1) & (redundancy_model46_cfblk2_1=v) & (x_cfblk1_1_1004050723_2_y_cfblk1_114425425_2_y_cfblk2_153560818=prop_1) & (y_cfblk4_231831604_2_y_cfblk2_153560818_2_y_cfblk3_192696211=prop_1) -> (cf'=cfblk3_Output_3);	// <-- 
	[compare1] (cf=compare1) & (redundancy_model46_cfblk2_1=v) & ((x_cfblk1_1_1004050723_2_y_cfblk1_114425425_2_y_cfblk2_153560818=prop_2) | (y_cfblk4_231831604_2_y_cfblk2_153560818_2_y_cfblk3_192696211=prop_2)) -> (cf'=cfblk2_Output_2_3);	// <-- 
	//Element check_redandancy2, df inputs ['redundancy_model46_cfblk3_2'], cf transitions ['cfblk3_Output_3_2', 'cfblk5_Output_4']
	[check_redandancy2] (cf=check_redandancy2) & (redundancy_model46_cfblk3_2=no) -> (cf'=cfblk5_Output_4);	// <-- 
	[check_redandancy2] (cf=check_redandancy2) & ((redundancy_model46_cfblk3_2=v)|(redundancy_model46_cfblk3_2=c)) -> (cf'=cfblk3_Output_3_2);	// <-- 
	//Element cfblk3_Output_3_2, df inputs ['y_cfblk5_270966997_y_cfblk1_114425425'], cf transitions ['compare2']
	[cfblk3_Output_3_2] cf=cfblk3_Output_3_2 -> 1.0:(cf'=compare2);
	//Element cfblk3_Output_3_3, df inputs ['y_cfblk5_270966997_y_cfblk1_114425425'], cf transitions ['cfblk5_Output_4']
	[cfblk3_Output_3_3] cf=cfblk3_Output_3_3 -> 1.0:(cf'=cfblk5_Output_4);
	//Element compare2, df inputs ['redundancy_model46_cfblk3_2', 'y_cfblk4_231831604_2_y_cfblk2_153560818_2_y_cfblk3_192696211', 'y_cfblk3_192696211_2'], cf transitions ['cfblk3_Output_3_3', 'cfblk5_Output_4', 'stop_system']
	[compare2] (cf=compare2) & (redundancy_model46_cfblk3_2=c) & (y_cfblk4_231831604_2_y_cfblk2_153560818_2_y_cfblk3_192696211=prop_1) & (y_cfblk3_192696211_2=ok) -> (cf'=cfblk5_Output_4);	// <-- 
	[compare2] (cf=compare2) & (redundancy_model46_cfblk3_2=c) & ((y_cfblk4_231831604_2_y_cfblk2_153560818_2_y_cfblk3_192696211=prop_2) | (y_cfblk3_192696211_2=error)) -> (cf'=stop_system);	// <-- 
	[compare2] (cf=compare2) & (redundancy_model46_cfblk3_2=v) & (y_cfblk4_231831604_2_y_cfblk2_153560818_2_y_cfblk3_192696211=prop_1) & (y_cfblk3_192696211_2=ok) -> (cf'=cfblk5_Output_4);	// <-- 
	[compare2] (cf=compare2) & (redundancy_model46_cfblk3_2=v) & ((y_cfblk4_231831604_2_y_cfblk2_153560818_2_y_cfblk3_192696211=prop_2) | (y_cfblk3_192696211_2=error)) -> (cf'=cfblk3_Output_3_3);	// <-- 
	//Element check_redandancy3, df inputs ['redundancy_model46_cfblk4_3'], cf transitions ['cfblk4_Output_5_2', 'cfblk1_Update_6']
	[check_redandancy3] (cf=check_redandancy3) & (redundancy_model46_cfblk4_3=no) -> (cf'=cfblk1_Update_6);	// <-- 
	[check_redandancy3] (cf=check_redandancy3) & ((redundancy_model46_cfblk4_3=v)|(redundancy_model46_cfblk4_3=c)) -> (cf'=cfblk4_Output_5_2);	// <-- 
	//Element cfblk4_Output_5_2, df inputs ['x_cfblk1_1_1004050723_2_y_cfblk1_114425425_2_y_cfblk2_153560818', 'y_cfblk5_270966997_y_cfblk1_114425425'], cf transitions ['compare3']
	[cfblk4_Output_5_2] cf=cfblk4_Output_5_2 -> 1.0:(cf'=compare3);
	//Element cfblk4_Output_5_3, df inputs ['x_cfblk1_1_1004050723_2_y_cfblk1_114425425_2_y_cfblk2_153560818', 'y_cfblk5_270966997_y_cfblk1_114425425'], cf transitions ['cfblk1_Update_6']
	[cfblk4_Output_5_3] cf=cfblk4_Output_5_3 -> 1.0:(cf'=cfblk1_Update_6);
	//Element compare3, df inputs ['redundancy_model46_cfblk4_3', 'y_cfblk4_231831604', 'y_cfblk4_231831604_2_y_cfblk2_153560818_2_y_cfblk3_192696211'], cf transitions ['cfblk4_Output_5_3', 'cfblk1_Update_6', 'stop_system']
	[compare3] (cf=compare3) & (redundancy_model46_cfblk4_3=c) & (y_cfblk4_231831604=ok) & (y_cfblk4_231831604_2_y_cfblk2_153560818_2_y_cfblk3_192696211=prop_1) -> (cf'=cfblk1_Update_6);	// <-- 
	[compare3] (cf=compare3) & (redundancy_model46_cfblk4_3=c) & ((y_cfblk4_231831604=error) | (y_cfblk4_231831604_2_y_cfblk2_153560818_2_y_cfblk3_192696211=prop_2)) -> (cf'=stop_system);	// <-- 
	[compare3] (cf=compare3) & (redundancy_model46_cfblk4_3=v) & (y_cfblk4_231831604=ok) & (y_cfblk4_231831604_2_y_cfblk2_153560818_2_y_cfblk3_192696211=prop_1) -> (cf'=cfblk1_Update_6);	// <-- 
	[compare3] (cf=compare3) & (redundancy_model46_cfblk4_3=v) & ((y_cfblk4_231831604=error) | (y_cfblk4_231831604_2_y_cfblk2_153560818_2_y_cfblk3_192696211=prop_2)) -> (cf'=cfblk4_Output_5_3);	// <-- 
	//Element check_redandancy4, df inputs ['redundancy_model46_cfblk1_0'], cf transitions ['cfblk1_Update_6_2', 'cfblk1_Output_1']
	[check_redandancy4] (cf=check_redandancy4) & (redundancy_model46_cfblk1_0=no) -> (cf'=cfblk1_Output_1);	// <-- 
	[check_redandancy4] (cf=check_redandancy4) & ((redundancy_model46_cfblk1_0=v)|(redundancy_model46_cfblk1_0=c)) -> (cf'=cfblk1_Update_6_2);	// <-- 
	//Element cfblk1_Update_6_2, df inputs ['y_cfblk4_231831604', 'x_cfblk1_1_1004050723'], cf transitions ['compare4']
	[cfblk1_Update_6_2] cf=cfblk1_Update_6_2 -> 1.0:(cf'=compare4);
	//Element cfblk1_Update_6_3, df inputs ['y_cfblk4_231831604', 'x_cfblk1_1_1004050723'], cf transitions ['cfblk1_Output_1']
	[cfblk1_Update_6_3] cf=cfblk1_Update_6_3 -> 1.0:(cf'=cfblk1_Output_1);
	//Element compare4, df inputs ['x_cfblk1_1_1004050723_2_y_cfblk1_114425425_2_y_cfblk2_153560818', 'redundancy_model46_cfblk1_0', 'x_cfblk1_1_1004050723'], cf transitions ['cfblk1_Update_6_3', 'cfblk1_Output_1', 'stop_system']
	[compare4] (cf=compare4) & (redundancy_model46_cfblk1_0=c) & (x_cfblk1_1_1004050723=ok) & (x_cfblk1_1_1004050723_2_y_cfblk1_114425425_2_y_cfblk2_153560818=prop_1) -> (cf'=cfblk1_Output_1);	// <-- 
	[compare4] (cf=compare4) & (redundancy_model46_cfblk1_0=c) & ((x_cfblk1_1_1004050723=error) | (x_cfblk1_1_1004050723_2_y_cfblk1_114425425_2_y_cfblk2_153560818=prop_2)) -> (cf'=stop_system);	// <-- 
	[compare4] (cf=compare4) & (redundancy_model46_cfblk1_0=v) & (x_cfblk1_1_1004050723=ok) & (x_cfblk1_1_1004050723_2_y_cfblk1_114425425_2_y_cfblk2_153560818=prop_1) -> (cf'=cfblk1_Output_1);	// <-- 
	[compare4] (cf=compare4) & (redundancy_model46_cfblk1_0=v) & ((x_cfblk1_1_1004050723=error) | (x_cfblk1_1_1004050723_2_y_cfblk1_114425425_2_y_cfblk2_153560818=prop_2)) -> (cf'=cfblk1_Update_6_3);	// <-- 
endmodule
//Error propagation commands
module error_propagation
	y_cfblk4_231831604 : [0 .. 6] init ok;
	x_cfblk1_1_1004050723 : [0 .. 6] init ok;
	redundancy_model46_cfblk1_0 : [0 .. 6] init v;
	redundancy_model46_cfblk2_1 : [0 .. 6] init v;
	redundancy_model46_cfblk3_2 : [0 .. 6] init no;
	y_cfblk3_192696211_2 : [0 .. 6] init ok;
	redundancy_model46_cfblk4_3 : [0 .. 6] init v;
	y_cfblk5_270966997_y_cfblk1_114425425 : [0 .. 6] init prop_1;
	y_cfblk4_231831604_2_y_cfblk2_153560818_2_y_cfblk3_192696211 : [0 .. 6] init prop_1;
	x_cfblk1_1_1004050723_2_y_cfblk1_114425425_2_y_cfblk2_153560818 : [0 .. 6] init prop_1;
	//Element cfblk1_Output_1, df inputs ['y_cfblk4_231831604', 'x_cfblk1_1_1004050723'], df outputs ['y_cfblk5_270966997_y_cfblk1_114425425']
	[cfblk1_Output_1] (y_cfblk4_231831604=ok) & (x_cfblk1_1_1004050723=ok) -> 0.98:(y_cfblk5_270966997_y_cfblk1_114425425'=prop_1) + 0.02:(y_cfblk5_270966997_y_cfblk1_114425425'=prop_2);	// <-- 
	[cfblk1_Output_1] (y_cfblk4_231831604!=ok) | (x_cfblk1_1_1004050723!=ok) -> (y_cfblk5_270966997_y_cfblk1_114425425'=prop_2);	// <-- 
	//Element cfblk2_Output_2, df outputs ['x_cfblk1_1_1004050723_2_y_cfblk1_114425425_2_y_cfblk2_153560818']
	[cfblk2_Output_2] (true) -> 1:(x_cfblk1_1_1004050723_2_y_cfblk1_114425425_2_y_cfblk2_153560818'=prop_1);	// <-- 
	//Element cfblk3_Output_3, df inputs ['y_cfblk5_270966997_y_cfblk1_114425425'], df outputs ['y_cfblk4_231831604_2_y_cfblk2_153560818_2_y_cfblk3_192696211']
	[cfblk3_Output_3] (y_cfblk5_270966997_y_cfblk1_114425425=prop_1) -> 0.974002239936:(y_cfblk4_231831604_2_y_cfblk2_153560818_2_y_cfblk3_192696211'=prop_1) + 0.025997760064:(y_cfblk4_231831604_2_y_cfblk2_153560818_2_y_cfblk3_192696211'=prop_2);	// <-- 
	[cfblk3_Output_3] (y_cfblk5_270966997_y_cfblk1_114425425!=prop_1) -> (y_cfblk4_231831604_2_y_cfblk2_153560818_2_y_cfblk3_192696211'=prop_2);	// <-- 
	//Element cfblk5_Output_4, df inputs ['y_cfblk4_231831604_2_y_cfblk2_153560818_2_y_cfblk3_192696211'], df outputs ['y_cfblk5_270966997_y_cfblk1_114425425']
	[cfblk5_Output_4] (y_cfblk4_231831604_2_y_cfblk2_153560818_2_y_cfblk3_192696211=prop_1) -> 0.969003039904:(y_cfblk5_270966997_y_cfblk1_114425425'=prop_1) + 0.030996960095999997:(y_cfblk5_270966997_y_cfblk1_114425425'=prop_2);	// <-- 
	[cfblk5_Output_4] (y_cfblk4_231831604_2_y_cfblk2_153560818_2_y_cfblk3_192696211!=prop_1) -> (y_cfblk5_270966997_y_cfblk1_114425425'=prop_2);	// <-- 
	//Element cfblk4_Output_5, df inputs ['x_cfblk1_1_1004050723_2_y_cfblk1_114425425_2_y_cfblk2_153560818', 'y_cfblk5_270966997_y_cfblk1_114425425'], df outputs ['y_cfblk4_231831604']
	[cfblk4_Output_5] (x_cfblk1_1_1004050723_2_y_cfblk1_114425425_2_y_cfblk2_153560818=prop_1) & (y_cfblk5_270966997_y_cfblk1_114425425=prop_1) -> 0.974002239936:(y_cfblk4_231831604'=ok) + 0.025997760064:(y_cfblk4_231831604'=error);	// <-- 
	[cfblk4_Output_5] (x_cfblk1_1_1004050723_2_y_cfblk1_114425425_2_y_cfblk2_153560818!=prop_1) | (y_cfblk5_270966997_y_cfblk1_114425425!=prop_1) -> (y_cfblk4_231831604'=error);	// <-- 
	//Element cfblk1_Update_6, df inputs ['y_cfblk4_231831604', 'x_cfblk1_1_1004050723'], df outputs ['x_cfblk1_1_1004050723']
	[cfblk1_Update_6] (y_cfblk4_231831604=ok) & (x_cfblk1_1_1004050723=ok) -> 0.98:(x_cfblk1_1_1004050723'=ok) + 0.02:(x_cfblk1_1_1004050723'=error);	// <-- 
	[cfblk1_Update_6] (y_cfblk4_231831604!=ok) | (x_cfblk1_1_1004050723!=ok) -> (x_cfblk1_1_1004050723'=error);	// <-- 
	//Element cfblk1_Output_1_2, df inputs ['y_cfblk4_231831604', 'x_cfblk1_1_1004050723'], df outputs ['x_cfblk1_1_1004050723_2_y_cfblk1_114425425_2_y_cfblk2_153560818']
	[cfblk1_Output_1_2] (y_cfblk4_231831604=ok) & (x_cfblk1_1_1004050723=ok) -> 0.98:(x_cfblk1_1_1004050723_2_y_cfblk1_114425425_2_y_cfblk2_153560818'=prop_1) + 0.02:(x_cfblk1_1_1004050723_2_y_cfblk1_114425425_2_y_cfblk2_153560818'=prop_2);	// <-- 
	[cfblk1_Output_1_2] (y_cfblk4_231831604!=ok) | (x_cfblk1_1_1004050723!=ok) -> (x_cfblk1_1_1004050723_2_y_cfblk1_114425425_2_y_cfblk2_153560818'=prop_2);	// <-- 
	//Element cfblk1_Output_1_3, df inputs ['y_cfblk4_231831604', 'x_cfblk1_1_1004050723'], df outputs ['y_cfblk5_270966997_y_cfblk1_114425425']
	[cfblk1_Output_1_3] (y_cfblk4_231831604=ok) & (x_cfblk1_1_1004050723=ok) -> 0.98:(y_cfblk5_270966997_y_cfblk1_114425425'=prop_1) + 0.02:(y_cfblk5_270966997_y_cfblk1_114425425'=prop_2);	// <-- 
	[cfblk1_Output_1_3] (y_cfblk4_231831604!=ok) | (x_cfblk1_1_1004050723!=ok) -> (y_cfblk5_270966997_y_cfblk1_114425425'=prop_2);	// <-- 
	//Element cfblk2_Output_2_2, df outputs ['y_cfblk4_231831604_2_y_cfblk2_153560818_2_y_cfblk3_192696211']
	[cfblk2_Output_2_2] (true) -> 1:(y_cfblk4_231831604_2_y_cfblk2_153560818_2_y_cfblk3_192696211'=prop_1);	// <-- 
	//Element cfblk2_Output_2_3, df outputs ['x_cfblk1_1_1004050723_2_y_cfblk1_114425425_2_y_cfblk2_153560818']
	[cfblk2_Output_2_3] (true) -> 1:(x_cfblk1_1_1004050723_2_y_cfblk1_114425425_2_y_cfblk2_153560818'=prop_1);	// <-- 
	//Element cfblk3_Output_3_2, df inputs ['y_cfblk5_270966997_y_cfblk1_114425425'], df outputs ['y_cfblk3_192696211_2']
	[cfblk3_Output_3_2] (y_cfblk5_270966997_y_cfblk1_114425425=prop_1) -> 0.974002239936:(y_cfblk3_192696211_2'=ok) + 0.025997760064:(y_cfblk3_192696211_2'=error);	// <-- 
	[cfblk3_Output_3_2] (y_cfblk5_270966997_y_cfblk1_114425425!=prop_1) -> (y_cfblk3_192696211_2'=error);	// <-- 
	//Element cfblk3_Output_3_3, df inputs ['y_cfblk5_270966997_y_cfblk1_114425425'], df outputs ['y_cfblk4_231831604_2_y_cfblk2_153560818_2_y_cfblk3_192696211']
	[cfblk3_Output_3_3] (y_cfblk5_270966997_y_cfblk1_114425425=prop_1) -> 0.974002239936:(y_cfblk4_231831604_2_y_cfblk2_153560818_2_y_cfblk3_192696211'=prop_1) + 0.025997760064:(y_cfblk4_231831604_2_y_cfblk2_153560818_2_y_cfblk3_192696211'=prop_2);	// <-- 
	[cfblk3_Output_3_3] (y_cfblk5_270966997_y_cfblk1_114425425!=prop_1) -> (y_cfblk4_231831604_2_y_cfblk2_153560818_2_y_cfblk3_192696211'=prop_2);	// <-- 
	//Element cfblk4_Output_5_2, df inputs ['x_cfblk1_1_1004050723_2_y_cfblk1_114425425_2_y_cfblk2_153560818', 'y_cfblk5_270966997_y_cfblk1_114425425'], df outputs ['y_cfblk4_231831604_2_y_cfblk2_153560818_2_y_cfblk3_192696211']
	[cfblk4_Output_5_2] (x_cfblk1_1_1004050723_2_y_cfblk1_114425425_2_y_cfblk2_153560818=prop_1) & (y_cfblk5_270966997_y_cfblk1_114425425=prop_1) -> 0.974002239936:(y_cfblk4_231831604_2_y_cfblk2_153560818_2_y_cfblk3_192696211'=prop_1) + 0.025997760064:(y_cfblk4_231831604_2_y_cfblk2_153560818_2_y_cfblk3_192696211'=prop_2);	// <-- 
	[cfblk4_Output_5_2] (x_cfblk1_1_1004050723_2_y_cfblk1_114425425_2_y_cfblk2_153560818!=prop_1) | (y_cfblk5_270966997_y_cfblk1_114425425!=prop_1) -> (y_cfblk4_231831604_2_y_cfblk2_153560818_2_y_cfblk3_192696211'=prop_2);	// <-- 
	//Element cfblk4_Output_5_3, df inputs ['x_cfblk1_1_1004050723_2_y_cfblk1_114425425_2_y_cfblk2_153560818', 'y_cfblk5_270966997_y_cfblk1_114425425'], df outputs ['y_cfblk4_231831604']
	[cfblk4_Output_5_3] (x_cfblk1_1_1004050723_2_y_cfblk1_114425425_2_y_cfblk2_153560818=prop_1) & (y_cfblk5_270966997_y_cfblk1_114425425=prop_1) -> 0.974002239936:(y_cfblk4_231831604'=ok) + 0.025997760064:(y_cfblk4_231831604'=error);	// <-- 
	[cfblk4_Output_5_3] (x_cfblk1_1_1004050723_2_y_cfblk1_114425425_2_y_cfblk2_153560818!=prop_1) | (y_cfblk5_270966997_y_cfblk1_114425425!=prop_1) -> (y_cfblk4_231831604'=error);	// <-- 
	//Element cfblk1_Update_6_2, df inputs ['y_cfblk4_231831604', 'x_cfblk1_1_1004050723'], df outputs ['x_cfblk1_1_1004050723_2_y_cfblk1_114425425_2_y_cfblk2_153560818']
	[cfblk1_Update_6_2] (y_cfblk4_231831604=ok) & (x_cfblk1_1_1004050723=ok) -> 0.98:(x_cfblk1_1_1004050723_2_y_cfblk1_114425425_2_y_cfblk2_153560818'=prop_1) + 0.02:(x_cfblk1_1_1004050723_2_y_cfblk1_114425425_2_y_cfblk2_153560818'=prop_2);	// <-- 
	[cfblk1_Update_6_2] (y_cfblk4_231831604!=ok) | (x_cfblk1_1_1004050723!=ok) -> (x_cfblk1_1_1004050723_2_y_cfblk1_114425425_2_y_cfblk2_153560818'=prop_2);	// <-- 
	//Element cfblk1_Update_6_3, df inputs ['y_cfblk4_231831604', 'x_cfblk1_1_1004050723'], df outputs ['x_cfblk1_1_1004050723']
	[cfblk1_Update_6_3] (y_cfblk4_231831604=ok) & (x_cfblk1_1_1004050723=ok) -> 0.98:(x_cfblk1_1_1004050723'=ok) + 0.02:(x_cfblk1_1_1004050723'=error);	// <-- 
	[cfblk1_Update_6_3] (y_cfblk4_231831604!=ok) | (x_cfblk1_1_1004050723!=ok) -> (x_cfblk1_1_1004050723'=error);	// <-- 
endmodule

//Failure formulas
formula failure = x_cfblk1_1_1004050723 = error;

rewards "time" true : 1; endrewards
