//Generated by ErrorPro
dtmc
//Element consts
const int cfblk3_Output_1=0;
const int cfblk1_Output_2=1;
const int cfblk5_Output_3=2;
const int cfblk2_Output_4=3;
const int cfblk4_Output_5=4;
const int cfblk1_Update_6=5;
const int check_redandancy0=6;
const int cfblk3_Output_1_2=7;
const int cfblk3_Output_1_3=8;
const int compare0=9;
const int stop_system=10;
const int check_redandancy1=11;
const int cfblk1_Output_2_2=12;
const int cfblk1_Output_2_3=13;
const int compare1=14;
const int check_redandancy3=15;
const int cfblk4_Output_5_2=16;
const int cfblk4_Output_5_3=17;
const int compare3=18;
const int check_redandancy4=19;
const int cfblk1_Update_6_2=20;
const int cfblk1_Update_6_3=21;
const int compare4=22;
//Data values consts
const int v=0;
const int ok=1;
const int no=2;
const int error=3;
const int c=4;
//Control flow commands
module control_flow
	cf:[0..23] init cfblk3_Output_1;
	//Element cfblk3_Output_1, cf transitions ['check_redandancy0']
	[cfblk3_Output_1] cf=cfblk3_Output_1 -> 1.0:(cf'=check_redandancy0);
	//Element cfblk1_Output_2, df inputs ['y_cfblk4_2198956810', 'x_cfblk1_1_1494673096'], cf transitions ['check_redandancy1']
	[cfblk1_Output_2] cf=cfblk1_Output_2 -> 1.0:(cf'=check_redandancy1);
	//Element cfblk5_Output_3, df inputs ['y_cfblk1_2081550631', 'y_cfblk3_2159821417'], cf transitions ['cfblk2_Output_4']
	[cfblk5_Output_3] cf=cfblk5_Output_3 -> 1.0:(cf'=cfblk2_Output_4);
	//Element cfblk2_Output_4, df inputs ['y_cfblk5_2238092203'], cf transitions ['cfblk4_Output_5']
	[cfblk2_Output_4] cf=cfblk2_Output_4 -> 1.0:(cf'=cfblk4_Output_5);
	//Element cfblk4_Output_5, df inputs ['y_cfblk1_2081550631'], cf transitions ['check_redandancy3']
	[cfblk4_Output_5] cf=cfblk4_Output_5 -> 1.0:(cf'=check_redandancy3);
	//Element cfblk1_Update_6, df inputs ['y_cfblk4_2198956810', 'x_cfblk1_1_1494673096'], cf transitions ['check_redandancy4']
	[cfblk1_Update_6] cf=cfblk1_Update_6 -> 1.0:(cf'=check_redandancy4);
	//Element check_redandancy0, df inputs ['redundancy_model80_cfblk3_0'], cf transitions ['cfblk3_Output_1_2', 'cfblk1_Output_2']
	[check_redandancy0] (cf=check_redandancy0) & (redundancy_model80_cfblk3_0=no) -> (cf'=cfblk1_Output_2);	// <-- 
	[check_redandancy0] (cf=check_redandancy0) & ((redundancy_model80_cfblk3_0=v)|(redundancy_model80_cfblk3_0=c)) -> (cf'=cfblk3_Output_1_2);	// <-- 
	//Element cfblk3_Output_1_2, cf transitions ['compare0']
	[cfblk3_Output_1_2] cf=cfblk3_Output_1_2 -> 1.0:(cf'=compare0);
	//Element cfblk3_Output_1_3, cf transitions ['cfblk1_Output_2']
	[cfblk3_Output_1_3] cf=cfblk3_Output_1_3 -> 1.0:(cf'=cfblk1_Output_2);
	//Element compare0, df inputs ['redundancy_model80_cfblk3_0', 'y_cfblk3_2159821417_2', 'y_cfblk3_2159821417'], cf transitions ['cfblk3_Output_1_3', 'cfblk1_Output_2', 'stop_system']
	[compare0] (cf=compare0) & (redundancy_model80_cfblk3_0=c) & (y_cfblk3_2159821417=ok) & (y_cfblk3_2159821417_2=ok) -> (cf'=cfblk1_Output_2);	// <-- 
	[compare0] (cf=compare0) & (redundancy_model80_cfblk3_0=c) & ((y_cfblk3_2159821417=error) | (y_cfblk3_2159821417_2=error)) -> (cf'=stop_system);	// <-- 
	[compare0] (cf=compare0) & (redundancy_model80_cfblk3_0=v) & (y_cfblk3_2159821417=ok) & (y_cfblk3_2159821417_2=ok) -> (cf'=cfblk1_Output_2);	// <-- 
	[compare0] (cf=compare0) & (redundancy_model80_cfblk3_0=v) & ((y_cfblk3_2159821417=error) | (y_cfblk3_2159821417_2=error)) -> (cf'=cfblk3_Output_1_3);	// <-- 
	//Element stop_system, cf transitions ['cfblk3_Output_1']
	[stop_system] cf=stop_system -> 1.0:(cf'=cfblk3_Output_1);
	//Element check_redandancy1, df inputs ['redundancy_model80_cfblk1_1'], cf transitions ['cfblk1_Output_2_2', 'cfblk5_Output_3']
	[check_redandancy1] (cf=check_redandancy1) & (redundancy_model80_cfblk1_1=no) -> (cf'=cfblk5_Output_3);	// <-- 
	[check_redandancy1] (cf=check_redandancy1) & ((redundancy_model80_cfblk1_1=v)|(redundancy_model80_cfblk1_1=c)) -> (cf'=cfblk1_Output_2_2);	// <-- 
	//Element cfblk1_Output_2_2, df inputs ['y_cfblk4_2198956810', 'x_cfblk1_1_1494673096'], cf transitions ['compare1']
	[cfblk1_Output_2_2] cf=cfblk1_Output_2_2 -> 1.0:(cf'=compare1);
	//Element cfblk1_Output_2_3, df inputs ['y_cfblk4_2198956810', 'x_cfblk1_1_1494673096'], cf transitions ['cfblk5_Output_3']
	[cfblk1_Output_2_3] cf=cfblk1_Output_2_3 -> 1.0:(cf'=cfblk5_Output_3);
	//Element compare1, df inputs ['redundancy_model80_cfblk1_1', 'y_cfblk1_2081550631_2', 'y_cfblk1_2081550631'], cf transitions ['cfblk1_Output_2_3', 'cfblk5_Output_3', 'stop_system']
	[compare1] (cf=compare1) & (redundancy_model80_cfblk1_1=c) & (y_cfblk1_2081550631=ok) & (y_cfblk1_2081550631_2=ok) -> (cf'=cfblk5_Output_3);	// <-- 
	[compare1] (cf=compare1) & (redundancy_model80_cfblk1_1=c) & ((y_cfblk1_2081550631=error) | (y_cfblk1_2081550631_2=error)) -> (cf'=stop_system);	// <-- 
	[compare1] (cf=compare1) & (redundancy_model80_cfblk1_1=v) & (y_cfblk1_2081550631=ok) & (y_cfblk1_2081550631_2=ok) -> (cf'=cfblk5_Output_3);	// <-- 
	[compare1] (cf=compare1) & (redundancy_model80_cfblk1_1=v) & ((y_cfblk1_2081550631=error) | (y_cfblk1_2081550631_2=error)) -> (cf'=cfblk1_Output_2_3);	// <-- 
	//Element check_redandancy3, df inputs ['redundancy_model80_cfblk4_3'], cf transitions ['cfblk4_Output_5_2', 'cfblk1_Update_6']
	[check_redandancy3] (cf=check_redandancy3) & (redundancy_model80_cfblk4_3=no) -> (cf'=cfblk1_Update_6);	// <-- 
	[check_redandancy3] (cf=check_redandancy3) & ((redundancy_model80_cfblk4_3=v)|(redundancy_model80_cfblk4_3=c)) -> (cf'=cfblk4_Output_5_2);	// <-- 
	//Element cfblk4_Output_5_2, df inputs ['y_cfblk1_2081550631'], cf transitions ['compare3']
	[cfblk4_Output_5_2] cf=cfblk4_Output_5_2 -> 1.0:(cf'=compare3);
	//Element cfblk4_Output_5_3, df inputs ['y_cfblk1_2081550631'], cf transitions ['cfblk1_Update_6']
	[cfblk4_Output_5_3] cf=cfblk4_Output_5_3 -> 1.0:(cf'=cfblk1_Update_6);
	//Element compare3, df inputs ['redundancy_model80_cfblk4_3', 'y_cfblk4_2198956810_2', 'y_cfblk4_2198956810'], cf transitions ['cfblk4_Output_5_3', 'cfblk1_Update_6', 'stop_system']
	[compare3] (cf=compare3) & (redundancy_model80_cfblk4_3=c) & (y_cfblk4_2198956810=ok) & (y_cfblk4_2198956810_2=ok) -> (cf'=cfblk1_Update_6);	// <-- 
	[compare3] (cf=compare3) & (redundancy_model80_cfblk4_3=c) & ((y_cfblk4_2198956810=error) | (y_cfblk4_2198956810_2=error)) -> (cf'=stop_system);	// <-- 
	[compare3] (cf=compare3) & (redundancy_model80_cfblk4_3=v) & (y_cfblk4_2198956810=ok) & (y_cfblk4_2198956810_2=ok) -> (cf'=cfblk1_Update_6);	// <-- 
	[compare3] (cf=compare3) & (redundancy_model80_cfblk4_3=v) & ((y_cfblk4_2198956810=error) | (y_cfblk4_2198956810_2=error)) -> (cf'=cfblk4_Output_5_3);	// <-- 
	//Element check_redandancy4, df inputs ['redundancy_model80_cfblk1_1'], cf transitions ['cfblk1_Update_6_2', 'cfblk3_Output_1']
	[check_redandancy4] (cf=check_redandancy4) & (redundancy_model80_cfblk1_1=no) -> (cf'=cfblk3_Output_1);	// <-- 
	[check_redandancy4] (cf=check_redandancy4) & ((redundancy_model80_cfblk1_1=v)|(redundancy_model80_cfblk1_1=c)) -> (cf'=cfblk1_Update_6_2);	// <-- 
	//Element cfblk1_Update_6_2, df inputs ['y_cfblk4_2198956810', 'x_cfblk1_1_1494673096'], cf transitions ['compare4']
	[cfblk1_Update_6_2] cf=cfblk1_Update_6_2 -> 1.0:(cf'=compare4);
	//Element cfblk1_Update_6_3, df inputs ['y_cfblk4_2198956810', 'x_cfblk1_1_1494673096'], cf transitions ['cfblk3_Output_1']
	[cfblk1_Update_6_3] cf=cfblk1_Update_6_3 -> 1.0:(cf'=cfblk3_Output_1);
	//Element compare4, df inputs ['redundancy_model80_cfblk1_1', 'x_cfblk1_1_1494673096_2', 'x_cfblk1_1_1494673096'], cf transitions ['cfblk1_Update_6_3', 'cfblk3_Output_1', 'stop_system']
	[compare4] (cf=compare4) & (redundancy_model80_cfblk1_1=c) & (x_cfblk1_1_1494673096=ok) & (x_cfblk1_1_1494673096_2=ok) -> (cf'=cfblk3_Output_1);	// <-- 
	[compare4] (cf=compare4) & (redundancy_model80_cfblk1_1=c) & ((x_cfblk1_1_1494673096=error) | (x_cfblk1_1_1494673096_2=error)) -> (cf'=stop_system);	// <-- 
	[compare4] (cf=compare4) & (redundancy_model80_cfblk1_1=v) & (x_cfblk1_1_1494673096=ok) & (x_cfblk1_1_1494673096_2=ok) -> (cf'=cfblk3_Output_1);	// <-- 
	[compare4] (cf=compare4) & (redundancy_model80_cfblk1_1=v) & ((x_cfblk1_1_1494673096=error) | (x_cfblk1_1_1494673096_2=error)) -> (cf'=cfblk1_Update_6_3);	// <-- 
endmodule
//Error propagation commands
module error_propagation
	y_cfblk1_2081550631 : [0 .. 4] init ok;
	y_cfblk3_2159821417 : [0 .. 4] init ok;
	y_cfblk4_2198956810 : [0 .. 4] init ok;
	y_cfblk5_2238092203 : [0 .. 4] init ok;
	x_cfblk1_1_1494673096 : [0 .. 4] init ok;
	redundancy_model80_cfblk3_0 : [0 .. 4] init no;
	y_cfblk3_2159821417_2 : [0 .. 4] init ok;
	redundancy_model80_cfblk1_1 : [0 .. 4] init c;
	y_cfblk1_2081550631_2 : [0 .. 4] init ok;
	redundancy_model80_cfblk4_3 : [0 .. 4] init v;
	y_cfblk4_2198956810_2 : [0 .. 4] init ok;
	x_cfblk1_1_1494673096_2 : [0 .. 4] init ok;
	//Element cfblk3_Output_1, df outputs ['y_cfblk3_2159821417']
	[cfblk3_Output_1] (true) -> 1:(y_cfblk3_2159821417'=ok);	// <-- 
	//Element cfblk1_Output_2, df inputs ['y_cfblk4_2198956810', 'x_cfblk1_1_1494673096'], df outputs ['y_cfblk1_2081550631']
	[cfblk1_Output_2] (y_cfblk4_2198956810=ok) & (x_cfblk1_1_1494673096=ok) -> 0.98:(y_cfblk1_2081550631'=ok) + 0.02:(y_cfblk1_2081550631'=error);	// <-- 
	[cfblk1_Output_2] (y_cfblk4_2198956810!=ok) | (x_cfblk1_1_1494673096!=ok) -> (y_cfblk1_2081550631'=error);	// <-- 
	//Element cfblk5_Output_3, df inputs ['y_cfblk1_2081550631', 'y_cfblk3_2159821417'], df outputs ['y_cfblk5_2238092203']
	[cfblk5_Output_3] (y_cfblk1_2081550631=ok) & (y_cfblk3_2159821417=ok) -> 0.974002239936:(y_cfblk5_2238092203'=ok) + 0.025997760064:(y_cfblk5_2238092203'=error);	// <-- 
	[cfblk5_Output_3] (y_cfblk1_2081550631!=ok) | (y_cfblk3_2159821417!=ok) -> (y_cfblk5_2238092203'=error);	// <-- 
	//Element cfblk4_Output_5, df inputs ['y_cfblk1_2081550631'], df outputs ['y_cfblk4_2198956810']
	[cfblk4_Output_5] (y_cfblk1_2081550631=ok) -> 0.974002239936:(y_cfblk4_2198956810'=ok) + 0.025997760064:(y_cfblk4_2198956810'=error);	// <-- 
	[cfblk4_Output_5] (y_cfblk1_2081550631!=ok) -> (y_cfblk4_2198956810'=error);	// <-- 
	//Element cfblk1_Update_6, df inputs ['y_cfblk4_2198956810', 'x_cfblk1_1_1494673096'], df outputs ['x_cfblk1_1_1494673096']
	[cfblk1_Update_6] (y_cfblk4_2198956810=ok) & (x_cfblk1_1_1494673096=ok) -> 0.98:(x_cfblk1_1_1494673096'=ok) + 0.02:(x_cfblk1_1_1494673096'=error);	// <-- 
	[cfblk1_Update_6] (y_cfblk4_2198956810!=ok) | (x_cfblk1_1_1494673096!=ok) -> (x_cfblk1_1_1494673096'=error);	// <-- 
	//Element cfblk3_Output_1_2, df outputs ['y_cfblk3_2159821417_2']
	[cfblk3_Output_1_2] (true) -> 1:(y_cfblk3_2159821417_2'=ok);	// <-- 
	//Element cfblk3_Output_1_3, df outputs ['y_cfblk3_2159821417']
	[cfblk3_Output_1_3] (true) -> 1:(y_cfblk3_2159821417'=ok);	// <-- 
	//Element cfblk1_Output_2_2, df inputs ['y_cfblk4_2198956810', 'x_cfblk1_1_1494673096'], df outputs ['y_cfblk1_2081550631_2']
	[cfblk1_Output_2_2] (y_cfblk4_2198956810=ok) & (x_cfblk1_1_1494673096=ok) -> 0.98:(y_cfblk1_2081550631_2'=ok) + 0.02:(y_cfblk1_2081550631_2'=error);	// <-- 
	[cfblk1_Output_2_2] (y_cfblk4_2198956810!=ok) | (x_cfblk1_1_1494673096!=ok) -> (y_cfblk1_2081550631_2'=error);	// <-- 
	//Element cfblk1_Output_2_3, df inputs ['y_cfblk4_2198956810', 'x_cfblk1_1_1494673096'], df outputs ['y_cfblk1_2081550631']
	[cfblk1_Output_2_3] (y_cfblk4_2198956810=ok) & (x_cfblk1_1_1494673096=ok) -> 0.98:(y_cfblk1_2081550631'=ok) + 0.02:(y_cfblk1_2081550631'=error);	// <-- 
	[cfblk1_Output_2_3] (y_cfblk4_2198956810!=ok) | (x_cfblk1_1_1494673096!=ok) -> (y_cfblk1_2081550631'=error);	// <-- 
	//Element cfblk4_Output_5_2, df inputs ['y_cfblk1_2081550631'], df outputs ['y_cfblk4_2198956810_2']
	[cfblk4_Output_5_2] (y_cfblk1_2081550631=ok) -> 0.974002239936:(y_cfblk4_2198956810_2'=ok) + 0.025997760064:(y_cfblk4_2198956810_2'=error);	// <-- 
	[cfblk4_Output_5_2] (y_cfblk1_2081550631!=ok) -> (y_cfblk4_2198956810_2'=error);	// <-- 
	//Element cfblk4_Output_5_3, df inputs ['y_cfblk1_2081550631'], df outputs ['y_cfblk4_2198956810']
	[cfblk4_Output_5_3] (y_cfblk1_2081550631=ok) -> 0.974002239936:(y_cfblk4_2198956810'=ok) + 0.025997760064:(y_cfblk4_2198956810'=error);	// <-- 
	[cfblk4_Output_5_3] (y_cfblk1_2081550631!=ok) -> (y_cfblk4_2198956810'=error);	// <-- 
	//Element cfblk1_Update_6_2, df inputs ['y_cfblk4_2198956810', 'x_cfblk1_1_1494673096'], df outputs ['x_cfblk1_1_1494673096_2']
	[cfblk1_Update_6_2] (y_cfblk4_2198956810=ok) & (x_cfblk1_1_1494673096=ok) -> 0.98:(x_cfblk1_1_1494673096_2'=ok) + 0.02:(x_cfblk1_1_1494673096_2'=error);	// <-- 
	[cfblk1_Update_6_2] (y_cfblk4_2198956810!=ok) | (x_cfblk1_1_1494673096!=ok) -> (x_cfblk1_1_1494673096_2'=error);	// <-- 
	//Element cfblk1_Update_6_3, df inputs ['y_cfblk4_2198956810', 'x_cfblk1_1_1494673096'], df outputs ['x_cfblk1_1_1494673096']
	[cfblk1_Update_6_3] (y_cfblk4_2198956810=ok) & (x_cfblk1_1_1494673096=ok) -> 0.98:(x_cfblk1_1_1494673096'=ok) + 0.02:(x_cfblk1_1_1494673096'=error);	// <-- 
	[cfblk1_Update_6_3] (y_cfblk4_2198956810!=ok) | (x_cfblk1_1_1494673096!=ok) -> (x_cfblk1_1_1494673096'=error);	// <-- 
endmodule

//Failure formulas
formula failure = x_cfblk1_1_1494673096 = error;

rewards "time" true : 1; endrewards
